FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["SecurityService/SecurityService.csproj", "./"]
RUN dotnet restore "./SecurityService.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "SecurityService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SecurityService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SecurityService.dll"]