// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorSearchController.php L28-106 → MapGet /search
        grp.MapGet("/search", async (
            [FromQuery] string? firstname,
            [FromQuery] string? lastname,
            [FromQuery] int employment_type,
            [FromQuery] int cca,
            [FromQuery] string? customer_name,
            [FromQuery] string? is_ts_direct,
            [FromQuery] string? is_active,
            AppDbContext db,
            ILogger<ContractorPlacementEndpoints> logger) =>
        {
            // L32-37 → searchType dispatch: if map=true, delegate to searchMap
            // (not translated here — separate endpoint)
    
            // L41 → initialize result collection
            var results = new List<ContractorPlacementSearchResult>();
    
            // L43-50 → firstname/lastname filters (LIKE search)
            var whereConditions = new List<string>();
            var parameters = new List<SqlParameter>();
            var paramIndex = 0;
    
            foreach (var field in new[] { "firstname", "lastname" })
            {
                var value = field == "firstname" ? firstname : lastname;
                var n = (value ?? "").Trim();
                if (!string.IsNullOrEmpty(n))
                {
                    whereConditions.Add($"c.{field} LIKE @p{paramIndex}");
                    parameters.Add(new SqlParameter($"@p{paramIndex}", $"%{n}%"));
                    paramIndex++;
                }
            }
    
            // L51-54 → employment_type filter (exact match)
            if (employment_type != 0)
            {
                whereConditions.Add($"et.id = @p{paramIndex}");
                parameters.Add(new SqlParameter($"@p{paramIndex}", employment_type));
                paramIndex++;
            }
    
            // L55-58 → cca filter (employee id, sentinel 1 = "any")
            if (cca != 1)
            {
                whereConditions.Add($"e.id = @p{paramIndex}");
                parameters.Add(new SqlParameter($"@p{paramIndex}", cca));
                paramIndex++;
            }
    
            // L60-64 → customer_name filter (LIKE search)
            var custName = (customer_name ?? "").Trim();
            if (!string.IsNullOrEmpty(custName))
            {
                whereConditions.Add($"cc.name LIKE @p{paramIndex}");
                parameters.Add(new SqlParameter($"@p{paramIndex}", $"%{custName}%"));
                paramIndex++;
            }
    
            // L66 → is_ts_direct filter: empty string = no filter, otherwise exact match
            var isTsDirect = (is_ts_direct ?? "").Trim();
            if (!string.IsNullOrEmpty(isTsDirect))
            {
                whereConditions.Add($"cp.is_ts_direct = @p{paramIndex}");
                parameters.Add(new SqlParameter($"@p{paramIndex}", isTsDirect));
                paramIndex++;
            }
    
            // L67 → is_active filter: empty string = no filter, otherwise exact match
            var isActive = (is_active ?? "").Trim();
            if (!string.IsNullOrEmpty(isActive))
            {
                whereConditions.Add($"cp.is_active = @p{paramIndex}");
                parameters.Add(new SqlParameter($"@p{paramIndex}", isActive));
                paramIndex++;
            }
    
            // L68-69 → portal customer IDs filter
            var portalCustIds = await GetPortalCustomerIds(db);
            var validPortalIds = portalCustIds
                .Where(id => int.TryParse(id, out var numId) && numId > 0)
                .ToList();
    
            // L70-101 → construct and execute the raw SQL query
            var whereClause = whereConditions.Count > 0
                ? " AND (" + string.Join(" AND ", whereConditions) + ")"
                : "";
    
            var portalClause = validPortalIds.Count > 0
                ? " AND cc.id IN (" + string.Join(",", validPortalIds) + ")"
                : "";
    
            var sql = @"
                SELECT DISTINCT
                    cp.id AS placement_id,
                    CONCAT(c.firstname, ' ', c.lastname, ' (', CASE WHEN cp.is_active = 'Y' THEN 'Active' ELSE 'In-active' END, ' / ', cp.id, ')') AS name,
                    et.name AS employment_type,
                    c.id AS id,
                    c.lastwelcomeemail AS welcomets,
                    cc.name AS customer,
                    cc.id AS customer_id,
                    cp.name AS placement,
                    cp.deactivation_date AS deactivation_date,
                    cp.is_active AS active,
                    CASE WHEN ccn.id != 1 THEN CONCAT(ccn.firstname, ' ', ccn.lastname, ' / ', ccn.email) ELSE '(Not Set)' END AS approver,
                    CASE WHEN e.id != 1 THEN CONCAT(e.firstname, ' ', e.lastname, ' / ', e.email) ELSE '(Not Set)' END AS cca,
                    CASE WHEN ccn.id != 1 THEN 1 ELSE 0 END AS show_checkbox,
                    cp.is_ts_direct AS is_ts_direct,
                    cp.start_date AS start_date
                FROM contractor c
                INNER JOIN contractor_placement cp ON cp.contractor_id = c.id
                INNER JOIN profile p ON p.contractor_placement_id = cp.id
                INNER JOIN employee_profile_map epm ON epm.profile_id = p.id
                INNER JOIN employee e ON epm.employee_id = e.id
                INNER JOIN employment_type et ON p.employment_type_id = et.id
                INNER JOIN customer cc ON cp.customer_id = cc.id
                INNER JOIN customer_contact ccn ON ccn.id = cp.approver_id
                WHERE cp.contractor_id = c.id
                  AND cp.customer_id = cc.id
                  AND ccn.id = cp.approver_id
                  AND p.contractor_placement_id = cp.id
                  AND p.id = (SELECT TOP 1 id FROM profile WHERE contractor_placement_id = cp.id ORDER BY created_at DESC)
                  AND p.employment_type_id != 1
                  AND cp.is_ref_only = 'N'
                  AND epm.profile_id = p.id
                  AND epm.description = 'CCA'
                  AND epm.employee_id = e.id
                  AND p.employment_type_id = et.id
                  AND c.id != 1
                " + whereClause + portalClause + @"
                GROUP BY cp.id
                ORDER BY cp.id
            ";
    
            try
            {
                var connection = db.Database.GetDbConnection();
                using (var cmd = connection.CreateCommand())
                {
                    cmd.CommandText = sql;
                    foreach (var param in parameters)
                    {
                        cmd.Parameters.Add(param);
                    }
            
                    if (connection.State != System.Data.ConnectionState.Open)
                    {
                        await connection.OpenAsync();
                    }
            
                    using (var reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            results.Add(new ContractorPlacementSearchResult
                            {
                                PlacementId = reader.GetString(0),
                                Name = reader.GetString(1),
                                EmploymentType = reader.IsDBNull(2) ? null : reader.GetString(2),
                                Id = reader.GetString(3),
                                WelcomeTs = reader.IsDBNull(4) ? null : reader.GetDateTime(4),
                                Customer = reader.GetString(5),
                                CustomerId = reader.GetString(6),
                                Placement = reader.GetString(7),
                                DeactivationDate = reader.IsDBNull(8) ? null : reader.GetDateTime(8),
                                Active = reader.GetString(9),
                                Approver = reader.GetString(10),
                                Cca = reader.GetString(11),
                                ShowCheckbox = reader.GetInt32(12),
                                IsTsDirect = reader.GetString(13),
                                StartDate = reader.IsDBNull(14) ? null : reader.GetDateTime(14),
                            });
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error executing contractor placement search query");
                return Results.BadRequest(new { error = "Search failed", detail = ex.Message });
            }
    
            // L105 → return count of results (legacy parity)
            return Results.Ok(new { data = results, count = results.Count });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        return app;
    }

    // ContractorSearchController.php L28-106 → search
    // Helper to fetch portal customer IDs (legacy Custmaster::getPCIPortalCustomerIDs)
    private static async Task<List<string>> GetPortalCustomerIds(AppDbContext db)
    {
        // Legacy: Custmaster::getPCIPortalCustomerIDs() returns comma-separated IDs
        // of customers marked as portal customers. Assuming a Config or similar
        // entity stores this; adjust per actual schema.
        var config = await db.Set<Config>()
            .FirstOrDefaultAsync(c => c.Key == "portal_customer_ids");
    
        if (config?.Value == null)
            return new List<string>();
    
        return config.Value
            .Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .ToList();
    }
}

public sealed record ContractorPlacementSearchResult
{
    public string PlacementId { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string? EmploymentType { get; init; }
    public string Id { get; init; } = string.Empty;
    public DateTime? WelcomeTs { get; init; }
    public string Customer { get; init; } = string.Empty;
    public string CustomerId { get; init; } = string.Empty;
    public string Placement { get; init; } = string.Empty;
    public DateTime? DeactivationDate { get; init; }
    public string Active { get; init; } = string.Empty;
    public string Approver { get; init; } = string.Empty;
    public string Cca { get; init; } = string.Empty;
    public int ShowCheckbox { get; init; }
    public string IsTsDirect { get; init; } = string.Empty;
    public DateTime? StartDate { get; init; }
}
