// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
        app.MapPost("/api/v1/contractor-placement-hr-checklist-details-search/run", async (HttpContext ctx, [FromServices] IExcelService excelService) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<RequestDto>();
            var includeExport = ctx.RequestServices.GetService<IConfiguration>().GetValue<bool>("IncludeExport");

            if (request == null) return Results.BadRequest(new { error = "Invalid request" });

            if (BoolValue(request.Data.GetValueOrDefault("prepare_excel")))
            {
                excelService.CreateCsv = false;
            }

            if (includeExport && BoolValue(request.Data.GetValueOrDefault("download_xlsx")))
            {
                excelService.CreateCsv = false;
                excelService.PreDownload();
            }

            var model = new Model
            {
                Param = request.Data,
                Label = new List<string>(),
                Data = new List<object>()
            };

            if (ShouldStorePrevRequest(request, ctx))
            {
                StorePrevRequest(ctx);
            }

            var hideOptBox = BoolValue(request.Data.GetValueOrDefault("hideoptbox")) || BoolValue(request.Data.GetValueOrDefault("hide_option_box"));

            ResetMessage();
            PreSearch(true);

            if (true)
            {
                SetExecuteStart();
                model.Data.Clear();
                var label = new List<string>();

                if (Search() < 1)
                {
                    AddMessage("Nothing Found");
                }
                else
                {
                    ConvertLabelsToObjects();
                }

                SetExecuteFinish();
            }

            if (includeExport && BoolValue(request.Data.GetValueOrDefault("download_xlsx")))
            {
                return RunDownload(request, true);
            }

            Organize();
            return Display();
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (HttpContext ctx, IDbConnection dbConnection) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L28-40 → SQL query
            var query = @"
                SELECT cphcm.contractor_placement_id AS contractor_placement_id,
                       cphcm.onb_hr_checklist_type_id AS onb_hr_checklist_type_id,
                       cp.name AS placement,
                       ohct.name AS onb_hr_checklist_type,
                       cphcm.completion_date AS completion_date
                  FROM contractor_placement_hr_checklist_details_map cphcm
                  JOIN contractor_placement cp ON cphcm.contractor_placement_id = cp.id
                  JOIN onb_hr_checklist_type ohct ON cphcm.onb_hr_checklist_type_id = ohct.id
                 WHERE cphcm.is_active = 'Y'
                   AND cphcm.is_customer_mapped = 'Y'
              ORDER BY cphcm.contractor_placement_id DESC";

            var data = await dbConnection.QueryAsync(query);

            // Contractor_placement_hr_checklist_detailsSearchController.php L42-43 → set model data
            var modelData = data.ToList();

            // Inline parent SearchController.php L350-360
            if (modelData.Any() && boolValue(ctx.Request.Query["createcsv"]))
            {
                var csv = new Csv(ctx.Request.Query["resultfile"], false, "w");
                csv.Write(modelData.First());
                foreach (var line in modelData.Skip(1))
                {
                    csv.Write(line);
                }
            }

            return Results.Json(new { status = modelData.Count });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
        app.MapGet("/api/v1/contractor-placement-hr-checklist-details/label", (ContractorPlacementHrChecklistDetailsModel model) =>
        {
            model.Label = new Dictionary<string, object[]>
            {
                { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
                { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
                { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", $"{model.Server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
            };
            return Results.Ok(true);
        });

        return app;
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
    private static bool BoolValue(JsonElement element)
    {
        return element.ValueKind == JsonValueKind.True || (element.ValueKind == JsonValueKind.String && element.GetString() == "true");
    }

    private static bool ShouldStorePrevRequest(RequestDto request, HttpContext ctx)
    {
        var xhr = request.Data.GetValueOrDefault("HTTP_X_REQUESTED_WITH").GetString();
        return string.IsNullOrEmpty(xhr) && xhr?.ToLower() != "xmlhttprequest" &&
               request.Data.GetValueOrDefault("response").GetString() != "json" &&
               request.Data.GetValueOrDefault("op").GetString() != "download" &&
               request.Data.GetValueOrDefault("op").GetString() != "delete" &&
               !BoolValue(request.Data.GetValueOrDefault("embed")) &&
               !request.Data.GetValueOrDefault("request").GetString().EndsWith(".json");
    }

    private static void StorePrevRequest(HttpContext ctx)
    {
        var url = CreateUrl(ctx.Request.Path, ctx.Request.Query);
        ctx.Session.SetString("PREVREQUEST", RemoveUrlParam(url, new[] { "password" }));
    }

    private static string CreateUrl(string path, IQueryCollection query)
    {
        // Implementation to create URL from path and query
        return string.Empty;
    }

    private static string RemoveUrlParam(string url, string[] paramsToRemove)
    {
        // Implementation to remove parameters from URL
        return url;
    }

    private static void ResetMessage()
    {
        // Implementation to reset messages
    }

    private static void PreSearch(bool perform)
    {
        // Implementation for pre-search logic
    }

    private static void SetExecuteStart()
    {
        // Implementation to set execute start
    }

    private static int Search()
    {
        // Implementation for search logic
        return 0;
    }

    private static void AddMessage(string message)
    {
        // Implementation to add message
    }

    private static void ConvertLabelsToObjects()
    {
        // Implementation to convert labels to objects
    }

    private static void SetExecuteFinish()
    {
        // Implementation to set execute finish
    }

    private static IResult RunDownload(RequestDto request, bool perform)
    {
        // Implementation for running download
        return Results.Ok();
    }

    private static void Organize()
    {
        // Implementation to organize
    }

    private static IResult Display()
    {
        // Implementation to display
        return Results.Ok();
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
    // Helper function to convert string to bool
    private static bool boolValue(string value)
    {
        return !string.IsNullOrEmpty(value) && (value.Equals("true", StringComparison.OrdinalIgnoreCase) || value == "1");
    }

    // Csv class stub for writing CSV files
    public class Csv
    {
        private readonly string _filePath;
        private readonly bool _append;
        private readonly string _mode;

        public Csv(string filePath, bool append, string mode)
        {
            _filePath = filePath;
            _append = append;
            _mode = mode;
        }

        public void Write(object line)
        {
            // Implement CSV writing logic here
        }
    }
}

public class RequestDto
{
    public Dictionary<string, JsonElement> Data { get; set; }
}
