// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace Application.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorEntityController.php L22-26 → MapGet
        grp.MapGet("/headline", async ([FromQuery] string text, AppDbContext db) =>
        {
            // L24 → default to 'Contractor' if text is empty
            var str = string.IsNullOrEmpty(text) ? "Contractor" : text;
            return Results.Ok(str);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L198-208 → MapGet
        grp.MapGet("/links", async () =>
        {
            // L200-207 → build links list
            var list = new List<Dictionary<string, string>>();
            list.Add(new Dictionary<string, string>
            {
                { "0", "Search" },
                { "1", "{server}/search/contractor" },
                { "2", "" }
            });
            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L210-281 → validate
        protected async Task<Contractor> Validate(ContractorCreateDto dto, bool isNew = false)
        {
            var obj = new Contractor();

            if (isNew)
            {
                obj.Id = null;
                obj.CreateTs = DateTime.UtcNow;
                obj.LastWelcomeEmail = new DateTime(2000, 1, 1);
            }
            else
            {
                obj.Id = dto.Id;
                if (obj.Id == 0)
                {
                    throw new ArgumentException("ID must be set to Update Entry");
                }
                // Load existing object from the database
                obj = await db.Set<Contractor>().FindAsync(obj.Id);
                if (obj == null)
                {
                    throw new ArgumentException("ID provided for Update does not exist");
                }
            }

            obj.Notes = dto.Notes?.Trim();
            obj.Mi = dto.Mi?.Trim();
            obj.IsActive = dto.IsActive ?? 'N';
            obj.AddressId = dto.AddressId ?? 1;
            obj.VisaStatusTypeId = dto.VisaStatusTypeId ?? 1;
            if (obj.VisaStatusTypeId < 1)
            {
                throw new ArgumentException("Visa is invalid");
            }

            if (isNew)
            {
                foreach (var field in new[] { "Firstname", "Lastname", "Email", "FileNum", "CompCode" })
                {
                    var value = dto.GetType().GetProperty(field)?.GetValue(dto)?.ToString();
                    if (string.IsNullOrWhiteSpace(value))
                    {
                        throw new ArgumentException($"{field} cannot be empty");
                    }
                    obj.GetType().GetProperty(field)?.SetValue(obj, value);
                }
            }
            else
            {
                obj.Email = dto.Email;
                if (string.IsNullOrWhiteSpace(obj.Email))
                {
                    throw new ArgumentException("Email cannot be empty");
                }
            }

            if (!IsValidEmail(obj.Email))
            {
                throw new ArgumentException("Please enter valid Email");
            }

            var exists = isNew ? await Contractor.ActiveByEmailAsync(obj.Email) : await Contractor.ExistsActiveAsync(obj.Id, obj.Email);
            if (exists)
            {
                throw new ArgumentException("This email is already taken");
            }

            if (!string.IsNullOrWhiteSpace(obj.Email))
            {
                obj.Username = obj.Email;
            }

            obj.TermDate = FromDisplayDate(dto.TermDate);
            if (obj.IsActive != 'Y' && obj.TermDate <= new DateTime(2000, 1, 1))
            {
                throw new ArgumentException("Term Date is invalid");
            }

            return obj;
        }

        return app;
    }

    // ContractorEntityController.php L210-281 → validate
    private bool IsValidEmail(string email)
    {
        return !string.IsNullOrWhiteSpace(email) && new EmailAddressAttribute().IsValid(email);
    }

    private DateTime FromDisplayDate(string date)
    {
        return DateTime.TryParse(date, out var result) ? result : DateTime.MinValue;
    }
}

public sealed record ContractorCreateDto(
    int Id,
    string? Notes,
    string? Mi,
    string? IsActive,
    int? AddressId,
    int? VisaStatusTypeId,
    string Firstname,
    string Lastname,
    string Email,
    string FileNum,
    string CompCode,
    string TermDate);
