// SPDX-License-Identifier: Apache-2.0
// Generated by CrudResourceExpander (deterministic — no LLM call)
//
// Resource:        /api/v1/contractor
// Entity:          Magicbox.Api.Domain.Contractor
// Source PHP:      Controller/ContractorEntityController.php
// Translated slots already in ContractorEndpoints.cs (suppressed here): []
// Scaffold types:  CreateDto=True, UpdateDto=True, ResponseDto=True, AuthPolicies.Contractor{Read,Write,Delete}=True,True,True

// HITL: prune slots, refine body projection, wire validators.
//
using FluentValidation;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Magicbox.Api.Auth;
using Magicbox.Api.Data;
using Magicbox.Api.Domain;
using Magicbox.Api.Dtos;

namespace Application.Endpoints;

public static class ContractorCrudEndpoints
{
    public static IEndpointRouteBuilder MapContractorCrudEndpoints(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // LIST — paginated; replace .Take(500) with caller-driven page size
        g.MapGet("/", async (AppDbContext db) =>
        {
            var rows = await db.Set<Contractor>()
                .OrderByDescending(x => x.CreatedAt)
                .Take(500)
                .ToListAsync();
            var cca_names = await LookupCcaNamesAsync(db, rows);
            var lookups = new { cca_names };
            return Results.Ok(new { records = rows, lookups, count = rows.Count });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // SEARCH — filters derived from scaffold (JWM step not available for this controller)
        // Query parameters (auto-derived from entity properties — JWM not populated):
        //   ?address_id=… → exact match on Contractor.AddressId
        //   ?visa_status_type_id=… → exact match on Contractor.VisaStatusTypeId
        //   ?term_date_from=YYYY-MM-DD&term_date_to=YYYY-MM-DD → range filter on Contractor.TermDate
        //   ?is_active=true|false → exact match on Contractor.IsActive
        //   ?mi=… → case-insensitive contains on Contractor.Mi
        //   ?notes=… → case-insensitive contains on Contractor.Notes
        //   ?email=… → case-insensitive contains on Contractor.Email
        //   ?cca_id=… → exact match on Contractor.CcaId
        g.MapGet("/search", async (HttpRequest req, AppDbContext db) =>
        {
            var query = db.Set<Contractor>().AsQueryable();
            var address_id = (req.Query["address_id"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(address_id)) query = query.Where(x => x.AddressId == address_id);
            var visa_status_type_id = (req.Query["visa_status_type_id"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(visa_status_type_id)) query = query.Where(x => x.VisaStatusTypeId == visa_status_type_id);
            if (DateOnly.TryParse(req.Query["term_date_from"].ToString(), out var term_dateFrom)) query = query.Where(x => x.TermDate != null && x.TermDate >= term_dateFrom);
            if (DateOnly.TryParse(req.Query["term_date_to"].ToString(), out var term_dateTo)) query = query.Where(x => x.TermDate != null && x.TermDate <= term_dateTo);
            var is_activeRaw = (req.Query["is_active"].ToString() ?? "").Trim().ToLowerInvariant();
            if (is_activeRaw == "true" || is_activeRaw == "false") { var is_active = is_activeRaw == "true"; query = query.Where(x => x.IsActive == is_active); }
            var mi = (req.Query["mi"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(mi)) { var __mi = mi.ToLowerInvariant(); query = query.Where(x => x.Mi != null && x.Mi.ToLower().Contains(__mi)); }
            var notes = (req.Query["notes"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(notes)) { var __notes = notes.ToLowerInvariant(); query = query.Where(x => x.Notes != null && x.Notes.ToLower().Contains(__notes)); }
            var email = (req.Query["email"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(email)) { var __email = email.ToLowerInvariant(); query = query.Where(x => x.Email != null && x.Email.ToLower().Contains(__email)); }
            var cca_id = (req.Query["cca_id"].ToString() ?? "").Trim();
            if (!string.IsNullOrEmpty(cca_id)) query = query.Where(x => x.CcaId == cca_id);
            var rows = await query.OrderByDescending(x => x.CreatedAt).Take(500).ToListAsync();
            var cca_names = await LookupCcaNamesAsync(db, rows);
            var lookups = new { cca_names };
            return Results.Ok(new { records = rows, lookups, count = rows.Count });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // DETAIL
        g.MapGet("/{id}", async (string id, AppDbContext db) =>
        {
            var row = await db.Set<Contractor>().FindAsync(id);
            if (row is null) return Results.NotFound();
            var cca_names = await LookupCcaNamesOneAsync(db, row.CcaId);
            var lookups = new { cca_names };
            return Results.Ok(new { row, lookups });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // CREATE
        g.MapPost("/", async (
            ContractorCreateDto dto,
            IValidator<ContractorCreateDto> validator,
            AppDbContext db) =>
        {
            var result = await validator.ValidateAsync(dto);
            if (!result.IsValid) return Results.ValidationProblem(result.ToDictionary());
            var row = new Contractor
            {
                AddressId = dto.AddressId,
                VisaStatusTypeId = dto.VisaStatusTypeId,
                TermDate = dto.TermDate,
                IsActive = dto.IsActive,
                Mi = dto.Mi,
                Notes = dto.Notes,
                Email = dto.Email,
                CcaId = dto.CcaId,
                // Defaults stamped below to satisfy non-null Id / CreatedAt;
                // operator should remove if not appropriate for this entity.
                Id = Guid.NewGuid().ToString(),
                CreatedAt = DateTime.UtcNow,
            };
            db.Set<Contractor>().Add(row);
            await db.SaveChangesAsync();
            return Results.Created($"/api/v1/contractor/{row.Id}", row);
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        // UPDATE
        g.MapPut("/{id}", async (
            string id,
            ContractorUpdateDto dto,
            IValidator<ContractorUpdateDto> validator,
            AppDbContext db) =>
        {
            var result = await validator.ValidateAsync(dto);
            if (!result.IsValid) return Results.ValidationProblem(result.ToDictionary());
            var existing = await db.Set<Contractor>().FindAsync(id);
            if (existing is null) return Results.NotFound();
            existing.AddressId = dto.AddressId;
            existing.VisaStatusTypeId = dto.VisaStatusTypeId;
            existing.TermDate = dto.TermDate;
            existing.IsActive = dto.IsActive;
            existing.Mi = dto.Mi;
            existing.Notes = dto.Notes;
            existing.Email = dto.Email;
            existing.CcaId = dto.CcaId;
            existing.UpdatedAt = DateTime.UtcNow;
            await db.SaveChangesAsync();
            return Results.Ok(existing);
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        // DELETE
        g.MapDelete("/{id}", async (string id, AppDbContext db) =>
        {
            var existing = await db.Set<Contractor>().FindAsync(id);
            if (existing is null) return Results.NotFound();
            db.Set<Contractor>().Remove(existing);
            await db.SaveChangesAsync();
            return Results.NoContent();
        }).RequireAuthorization(AuthPolicies.ContractorDelete);

        return app;
    }

    // FK-enrichment helpers (Gap-2 — emitted by CrudResourceExpander).
    // Source: Contractor.CcaId → Employee

    private static async Task<Dictionary<string, string>> LookupCcaNamesAsync(
        AppDbContext db, IReadOnlyList<Contractor> rows)
    {
        var ids = rows.Where(r => r.CcaId != null).Select(r => r.CcaId!).Distinct().ToList();
        if (ids.Count == 0) return new Dictionary<string, string>();
        var byId = await db.Set<Employee>()
            .Where(e => ids.Contains(e.Id))
            .ToDictionaryAsync(e => e.Id, e => $"{e.Lastname}, {e.Firstname}".Trim().TrimStart(',').Trim());
        return byId;
    }

    private static async Task<string?> LookupCcaNamesOneAsync(AppDbContext db, string? id)
    {
        if (string.IsNullOrEmpty(id)) return null;
        var e = await db.Set<Employee>().FindAsync(id);
        return e is null ? null : $"{e.Lastname}, {e.Firstname}".Trim().TrimStart(',').Trim();
    }
}
