FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ActiveXReplacementService/ActiveXReplacementService.csproj", "./"]
RUN dotnet restore "./ActiveXReplacementService.csproj"
COPY . .
WORKDIR "/src/ActiveXReplacementService"
RUN dotnet build "ActiveXReplacementService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ActiveXReplacementService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ActiveXReplacementService.dll"]