# Use the official .NET 8 SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the project file and restore dependencies
COPY src/CustomerAndAccountContractor.Api/*.csproj ./
RUN dotnet restore

# Copy the entire project and build the application
COPY src/CustomerAndAccountContractor.Api/. ./
RUN dotnet publish -c Release -o out

# Use the official ASP.NET Core runtime image for running the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Set the entry point for the application
ENTRYPOINT ["dotnet", "CustomerAndAccountContractor.Api.dll"]

# Expose port 8080
EXPOSE 8080