// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorSearchController.php L108-165 → searchMap
        app.MapGet("/api/v1/contractor/search", async (HttpRequest req, SqlConnection dbConnection) => {
            var s = Regex.Replace(req.Query["s"].ToString().Trim(), "\s{1,}", " ");
            var s3 = req.Query["s3"].ToString().Trim();

            if (s.Length < 3 && s3.Length < 3) {
                return Results.Ok(0);
            }

            var where1 = new List<string>();
            var where3 = new List<string>();

            var list = s.Split(' ');
            if (list.Length == 1) {
                var term = list[0];
                where1.Add($"(c.firstname LIKE @term OR c.lastname LIKE @term)");
            } else if (list.Length > 1) {
                var term1 = list[0];
                var term2 = list[1];
                where1.Add($"(c.firstname LIKE @term1 AND c.lastname LIKE @term2)");
            } else if (string.IsNullOrEmpty(s3)) {
                return Results.Ok(0);
            }

            if (!string.IsNullOrEmpty(s3)) {
                where3.Add($"cc.name LIKE @s3");
            }

            where3.Add("NOT EXISTS (SELECT 'x' FROM ts_portal_map WHERE contractor_placement_id = cp.id)");

            var query = @"SELECT DISTINCT cp.id AS placement_id, CONCAT(c.firstname, ' ', c.lastname, ' (', IF(cp.is_active = 'Y', 'Active', 'In-active'), ')') AS name,
                               c.id AS id, cc.name AS customer, cc.id AS customer_id, cp.name AS placement,
                               cp.deactivation_date AS deactivation_date, tpm.vms_foreign_str AS vms_foreign_str,
                               cp.id AS placement_id, c.is_active AS active, cp.start_date AS start_date
                          FROM contractor c, contractor_placement cp, customer cc
                          LEFT OUTER JOIN ts_portal_map tpm ON (tpm.contractor_placement_id = cp.id)
                         WHERE cp.contractor_id = c.id
                           AND cp.customer_id = cc.id
                           AND (" + string.Join(" AND ", where1) + ")
                           " + (where3.Count > 0 ? " AND " + string.Join(" AND ", where3) : "") + ";";

            var parameters = new {
                term = list.Length > 0 ? list[0] + "%" : null,
                term1 = list.Length > 0 ? list[0] + "%" : null,
                term2 = list.Length > 1 ? list[1] + "%" : null,
                s3 = s3 + "%"
            };

            var data = await dbConnection.QueryAsync(query, parameters);
            var result = data.ToList();
            return Results.Ok(result.Count);
        });

        return app;
    }


}


