# Use the official .NET SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the csproj and restore as distinct layers
COPY src/CustomerAndAccountArchcontractor.Api/*.csproj ./
RUN dotnet restore

# Copy the entire source code and build the application
COPY src/CustomerAndAccountArchcontractor.Api/. ./
RUN dotnet publish -c Release -o out

# Use the official ASP.NET Core runtime image for running the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

# Set the entry point for the application
ENTRYPOINT ["dotnet", "CustomerAndAccountArchcontractor.Api.dll"]