// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/repository/ArticleRepository.kt
//
package articlerepository

import (
	"context"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5"
)

// ArticleRepository.kt L17-25 → findBySlug
func (r *articleRepositoryImpl) FindBySlug(ctx context.Context, slug string) (*Article, error) {
    var article Article
    err := r.pool.QueryRow(ctx,
        `SELECT id, slug, title, description, body, created_at, updated_at FROM articles WHERE slug = $1`,
        slug,
    ).Scan(&article.ID, &article.Slug, &article.Title, &article.Description, &article.Body, &article.CreatedAt, &article.UpdatedAt)
    if errors.Is(err, pgx.ErrNoRows) {
        return nil, ErrNotFound
    }
    if err != nil {
        return nil, fmt.Errorf("find by slug: %w", err)
    }
    return &article, nil
}

// ArticleRepository.kt L21-25 → findByAuthorIdIn
func (r *articleRepositoryImpl) FindByAuthorIDIn(ctx context.Context, authorIds []string, limit, offset int) ([]Article, error) {
    rows, err := r.pool.Query(ctx,
        `SELECT id, title, content, author_id FROM articles WHERE author_id = ANY($1) ORDER BY created_at DESC LIMIT $2 OFFSET $3`,
        authorIds, limit, offset,
    )
    if err != nil {
        return nil, fmt.Errorf("query articles by author ids: %w", err)
    }
    defer rows.Close()
    var articles []Article
    for rows.Next() {
        var a Article
        if err := rows.Scan(&a.ID, &a.Title, &a.Content, &a.AuthorID); err != nil {
            return nil, fmt.Errorf("scan: %w", err)
        }
        articles = append(articles, a)
    }
    return articles, rows.Err()
}

// ArticleRepository.kt L27-28 → findNewestArticlesByAuthorIds
func (r *articleRepositoryImpl) FindNewestArticlesByAuthorIds(ctx context.Context, authorIds []string, offset, limit int) ([]Article, error) {
    rows, err := r.pool.Query(ctx,
        `SELECT id, title, body, author_id, created_at FROM articles WHERE author_id = ANY($1) ORDER BY created_at DESC OFFSET $2 LIMIT $3`,
        authorIds, offset, limit,
    )
    if err != nil {
        return nil, fmt.Errorf("query articles: %w", err)
    }
    defer rows.Close()
    var articles []Article
    for rows.Next() {
        var a Article
        if err := rows.Scan(&a.ID, &a.Title, &a.Body, &a.AuthorID, &a.CreatedAt); err != nil {
            return nil, fmt.Errorf("scan: %w", err)
        }
        articles = append(articles, a)
    }
    return articles, rows.Err()
}
