// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/repository/ArticleRepository.kt
//
package article

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
)

type articleRepositoryImpl struct {
    pool *pgxpool.Pool
}

func (r *articleRepositoryImpl) DeleteBySlug(ctx context.Context, slug string) error {
    _, err := r.pool.Exec(ctx, `DELETE FROM articles WHERE slug = $1`, slug)
    if err != nil {
        return fmt.Errorf("delete by slug %s: %w", slug, err)
    }
    return nil
}
