// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/ArticleFacade.kt
//
package article

import (
	"context"
	"fmt"
	"github.com/google/uuid"
)

func (s *articleFacadeImpl) CreateArticle(ctx context.Context, request CreateArticleRequest, author user.User) (ArticleView, error) {
    id := uuid.New().String()
    newArticle := request.ToArticle(id, author.ID)
    savedArticle, err := s.articleRepo.Save(ctx, newArticle)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }
    err = s.tagRepo.SaveAllTags(ctx, savedArticle.Tags)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save tags: %w", err)
    }
    authorProfileView := author.ToOwnProfileView()
    return savedArticle.ToArticleView(authorProfileView, author), nil
}

// internal/article/handler.go



func (s *articleFacadeImpl) UpdateArticle(ctx context.Context, request UpdateArticleRequest, slug string, author user.User) (ArticleView, error) {
    articleToUpdate, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    if !articleToUpdate.IsAuthor(author) {
        return ArticleView{}, fmt.Errorf("invalid request: only author can update article")
    }

    s.UpdateUser(request, articleToUpdate)

    savedArticle, err := s.articleRepo.Save(ctx, articleToUpdate)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }

    return savedArticle.ToAuthorArticleView(author), nil
}

func (s *articleFacadeImpl) DeleteArticle(ctx context.Context, slug string, user user.User) error {
    articleToDelete, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return fmt.Errorf("find article by slug: %w", err)
    }

    if !articleToDelete.IsAuthor(user) {
        return fmt.Errorf("invalid request: only author can delete own article")
    }

    err = s.articleRepo.DeleteBySlug(ctx, slug)
    if err != nil {
        return fmt.Errorf("delete article by slug: %w", err)
    }

    return nil
}

type Service interface {
    FindArticles(ctx context.Context, tag, authorName, favoritedByUser string, offset int64, limit int, currentUser *user.User) (MultipleArticlesView, error)
}

type articleFacadeImpl struct {
    articleRepo ArticleRepository
    userRepo    UserRepository
	tagRepo articleFacadeImpl_tagRepo_iface}

type articleFacadeImpl_tagRepo_iface interface {
	SaveAllTags(args ...any) error
}


func NewService(articleRepo ArticleRepository, userRepo UserRepository) Service {
    return &articleFacadeImpl{articleRepo: articleRepo, userRepo: userRepo}
}

func (s *articleFacadeImpl) FindArticles(ctx context.Context, tag, authorName, favoritedByUser string, offset int64, limit int, currentUser *user.User) (MultipleArticlesView, error) {
    var favoritedBy *user.User
    if favoritedByUser != "" {
        var err error
        favoritedBy, err = s.userRepo.FindByUsername(ctx, favoritedByUser)
        if err != nil {
            return MultipleArticlesView{}, fmt.Errorf("find favoritedBy user: %w", err)
        }
    }

    var author *user.User
    if authorName != "" {
        var err error
        author, err = s.userRepo.FindByUsername(ctx, authorName)
        if err != nil {
            return MultipleArticlesView{}, fmt.Errorf("find author user: %w", err)
        }
    }

    articles, err := s.articleRepo.FindNewestArticleFilteredBy(ctx, tag, author.ID, favoritedBy, limit, offset)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("find articles: %w", err)
    }

    articleViews := make([]ArticleView, len(articles))
    for i, article := range articles {
        articleViews[i] = mapToArticleView(article, currentUser)
    }

    return toMultipleArticlesView(articleViews), nil
}

func (s *articleFacadeImpl) Feed(ctx context.Context, offset int64, limit int, user user.User) (MultipleArticlesView, error) {
    articles, err := s.articleRepo.FindNewestArticlesByAuthorIds(ctx, user.FollowingIds, offset, limit)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("feed: %w", err)
    }

    var articleViews []ArticleView
    for _, article := range articles {
        articleView := mapToArticleView(article, user)
        articleViews = append(articleViews, articleView)
    }

    return toMultipleArticlesView(articleViews), nil
}

func (s *articleFacadeImpl) UpdateUser(ctx context.Context, request UpdateArticleRequest, articleToUpdate *Article) error {
    if request.Body != nil {
        articleToUpdate.Body = *request.Body
    }
    if request.Description != nil {
        articleToUpdate.Description = *request.Description
    }
    if request.Title != nil {
        articleToUpdate.Title = *request.Title
    }
    return s.articleRepo.Update(ctx, articleToUpdate)
}



func (s *articleFacadeImpl) FavoriteArticle(ctx context.Context, slug string, currentUser user.User) (ArticleView, error) {
    article, err := s.articleRepo.FindBySlugOrFail(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    currentUser.Favorite(article)

    if err := s.userRepo.Save(ctx, currentUser); err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }

    return mapToArticleView(article, currentUser), nil
}



func (s *articleFacadeImpl) UnfavoriteArticle(ctx context.Context, slug string, currentUser user.User) (ArticleView, error) {
    article, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }
    currentUser.Unfavorite(article)
    if err := s.userRepo.Save(ctx, currentUser); err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }
    return mapToArticleView(article, currentUser), nil
}

func (s *articleFacadeImpl) GetTags(ctx context.Context) (TagListView, error) {
    tags, err := s.articleRepo.FindAll(ctx)
    if err != nil {
        return TagListView{}, fmt.Errorf("get tags: %w", err)
    }
    return tags, nil
}

func (s *articleFacadeImpl) AddComment(ctx context.Context, slug string, content CreateCommentRequest, currentUser user.User) (CommentView, error) {
    article, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return CommentView{}, fmt.Errorf("find article by slug: %w", err)
    }

    comment := content.ToComment(uuid.New().String(), currentUser.ID)
    article.AddComment(comment)

    if err := s.articleRepo.Save(ctx, article); err != nil {
        return CommentView{}, fmt.Errorf("save article: %w", err)
    }

    return comment.ToCommentView(currentUser.ToOwnProfileView()), nil
}


type ArticleFacade interface {
    MapToCommentView(ctx context.Context, comment Comment, viewer *user.User) (CommentView, error)
}


func (a *articleFacadeImpl) MapToCommentView(ctx context.Context, comment Comment, viewer *user.User) (CommentView, error) {
    commentAuthor, err := a.userRepo.FindByID(ctx, comment.AuthorID)
    if err != nil {
        return CommentView{}, fmt.Errorf("find author: %w", err)
    }
    return comment.ToCommentView(commentAuthor, viewer), nil
}



func (a *articleFacadeImpl) GetComments(ctx context.Context, slug string, viewer *user.User) (MultipleCommentsView, error) {
    article, err := a.articleRepo.FindBySlugOrFail(ctx, slug)
    if err != nil {
        return MultipleCommentsView{}, fmt.Errorf("get comments: %w", err)
    }
    comments := make([]CommentView, 0)
    for _, comment := range article.Comments {
        comments = append(comments, mapToCommentView(comment, viewer))
    }
    return toMultipleCommentsView(comments), nil
}
