// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — fallback type aliases.
//
// These ``type X = any`` aliases let the package compile
// when the LLM-emitted code references types that aren't
// declared in this package and weren't resolved via
// cross-package imports. The wiring pass replaces these
// with the real type (struct OR cross-package import)
// — they are intentionally permissive (``any``) so the
// compiler doesn't reject valid call sites that pass
// typed values.
package src

type Articles = any
type ArticlesCount = any
type Author = any
type Bio = any
type Body = any
type Comments = any
type CreatedAt = any
type Description = any
type Email = any
type Favorited = any
type FavoritesCount = any
type Following = any
type Id = any
type Image = any
type Password = any
type Slug = any
type TagList = any
type TagName = any
type Tags = any
type Title = any
type Token = any
type UpdatedAt = any
type UserId = any
type Username = any
