// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package layer scaffold.
//
// Receiver struct for the translated `func (s *userSessionProviderImpl)`
// methods in this package, with dependency-interface-typed fields
// so the layer's outbound calls resolve. A real wiring pass swaps
// the interfaces for concrete collaborators.
package user

type userSessionProviderImpl_passwordServiceDep interface {
	EncodePassword(args ...any) (any, error)
	Matches(args ...any) bool
}

type userSessionProviderImpl_repoDep interface {
	ExistsByEmail(args ...any) (any, error)
	ExistsByUsername(args ...any) (any, error)
	FindByEmail(args ...any) (RepoFindByEmailResult, error)
	FindByID(args ...any) (any, error)
	FindByUsername(args ...any) (RepoFindByUsernameResult, error)
	Save(args ...any) (RepoSaveResult, error)
	UpdateUser(args ...any) error
}

type userSessionProviderImpl_userTokenProviderDep interface {
	GetToken(args ...any) (any, error)
}

type RepoFindByEmailResult struct {
	EncodedPassword any
}

type RepoFindByUsernameResult interface {
	ToFollowedProfileView(args ...any) any
}

type RepoSaveResult interface {
	ToUserView(args ...any) any
}

type userSessionProviderImpl struct {
	passwordService userSessionProviderImpl_passwordServiceDep
	repo userSessionProviderImpl_repoDep
	userTokenProvider userSessionProviderImpl_userTokenProviderDep
}

func (s *userSessionProviderImpl) createAuthenticationResponse(args ...any) (UserView, error) { panic("stub: sibling method") }

func (s *userSessionProviderImpl) updateEmail(args ...any) error { panic("stub: sibling method") }

func (s *userSessionProviderImpl) updateUsername(args ...any) error { panic("stub: sibling method") }
