// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placementEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placementEntityController.php L61-73 → create
        app.MapPost("/api/v1/contractor_placement", async (HttpContext ctx, [FromServices] EntityController entityController) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            if (request == null) return Results.BadRequest(new { error = "Invalid request" });

            var op = request.Op ?? "";
            switch (op)
            {
                case "":
                    return await entityController.Create(request);
                default:
                    return Results.BadRequest(new { error = "Unsupported operation" });
            }
        });

        return app;
    }

    // Contractor_placementEntityController.php L61-73 → create
    public class EntityController
    {
        public async Task<IResult> Create(Request request)
        {
            ResetMessage();
            var obj = Validate(request.Data, true);
            if (Message.Count > 0)
            {
                Op = "new";
                Model = obj;
                return Display();
            }
            else
            {
                Op = "new";
                Model = obj;
                if (!PreSave() || !Model.Save(ObjOnly))
                {
                    Message.Add("Problem saving entry (New)");
                    return Display();
                }

                var url = PostSave();

                if (request.Output == "json")
                {
                    return Display();
                }
                if (Message.Count > 0)
                {
                    return Display();
                }
                else if (!string.IsNullOrEmpty(url))
                {
                    return Results.Redirect(url);
                }
                else if (HttpContext.Session.TryGetValue("PREVREQUEST", out var prevRequest))
                {
                    return Results.Redirect(Encoding.UTF8.GetString(prevRequest));
                }
            }
            return Results.BadRequest(new { error = "Unknown error" });
        }

        private void ResetMessage() { /* Reset message logic */ }
        private object Validate(object data, bool flag) { /* Validation logic */ return new object(); }
        private bool PreSave() { /* Pre-save logic */ return true; }
        private string PostSave() { /* Post-save logic */ return ""; }
        private IResult Display() { /* Display logic */ return Results.Ok(); }

        public string Op { get; set; }
        public object Model { get; set; }
        public bool ObjOnly { get; set; }
        public List<string> Message { get; set; } = new();
    }
}

public class Request
{
    public string? Op { get; set; }
    public object Data { get; set; }
    public string? Output { get; set; }
}
