// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: chat/src/main/kotlin/com/plcoding/chirp/api/controllers/ChatController.kt
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Proj406b62972f.Endpoints;

public static class ChatEndpoints
{
    public static IEndpointRouteBuilder MapChatEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/chat").WithTags("Chat");

        // ChatController.kt L36-46 → getMessagesForChat
        func (h *Handler) GetMessagesForChat(w http.ResponseWriter, r *http.Request) {
            chatIdRaw := chi.URLParam(r, "chatId")
            chatId, err := uuid.Parse(chatIdRaw)
            if err != nil {
                httpx.WriteError(w, http.StatusBadRequest, "INVALID_CHAT_ID", "chatId must be a valid UUID")
                return
            }

            var before *time.Time
            if raw := r.URL.Query().Get("before"); raw != "" {
                parsed, err := time.Parse(time.RFC3339, raw)
                if err != nil {
                    httpx.WriteError(w, http.StatusBadRequest, "INVALID_BEFORE", "before must be a valid ISO 8601 timestamp")
                    return
                }
                before = &parsed
            }

            pageSize := DEFAULT_PAGE_SIZE
            if raw := r.URL.Query().Get("pageSize"); raw != "" {
                parsed, err := strconv.Atoi(raw)
                if err != nil || parsed <= 0 {
                    httpx.WriteError(w, http.StatusBadRequest, "INVALID_PAGE_SIZE", "pageSize must be greater than 0")
                    return
                }
                pageSize = parsed
            }

            messages, err := h.svc.GetChatMessages(r.Context(), chatId, before, pageSize)
            if err != nil {
                httpx.WriteInternal(w, r, err)
                return
            }
            httpx.WriteJSON(w, http.StatusOK, messages)
        }

        // ChatController.kt L59-63 → getChatsForUser
        func (h *Handler) GetChatsForUser(w http.ResponseWriter, r *http.Request) {
            chats, err := h.svc.GetChatsForUser(r.Context(), requestUserId)
            if err != nil {
                httpx.WriteInternal(w, r, err)
                return
            }
            httpx.WriteJSON(w, http.StatusOK, chats)
        }

        return app;
    }


}


