// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/user/PasswordService.kt
//
package user

import (
	"context"
	"fmt"
)

func (s *passwordServiceImpl) EncodePassword(ctx context.Context, rawPassword string) (string, error) {
    encoded, err := s.encoder.Encode(rawPassword)
    if err != nil {
        return "", fmt.Errorf("encode password: %w", err)
    }
    return encoded, nil
}
