// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package layer scaffold.
//
// Receiver struct for the translated `func (s *userSessionProviderImpl)`
// methods in this package, with dependency-interface-typed fields
// so the layer's outbound calls resolve. A real wiring pass swaps
// the interfaces for concrete collaborators.
package user

type userSessionProviderImpl_passwordServiceDep interface {
	EncodePassword(args ...any) (any, error)
}

type userSessionProviderImpl_repoDep interface {
	ExistsByEmail(args ...any) (any, error)
	ExistsByUsername(args ...any) (any, error)
	FindByID(args ...any) (any, error)
	FindByUsername(args ...any) (RepoFindByUsernameResult, error)
	Save(args ...any) (RepoSaveResult, error)
}

type userSessionProviderImpl_userTokenProviderDep interface {
	GetToken(args ...any) (any, error)
}

type userSessionProviderImpl struct {
	passwordService userSessionProviderImpl_passwordServiceDep
	repo userSessionProviderImpl_repoDep
	userTokenProvider userSessionProviderImpl_userTokenProviderDep
	securityContext userSessionProviderImpl_securityContext_iface}

type userSessionProviderImpl_securityContext_iface interface {
	GetContext(args ...any) (any, error)
}


func (s *userSessionProviderImpl) updateEmail(args ...any) error { panic("stub: sibling method") }

func (s *userSessionProviderImpl) updateUser(args ...any) error { panic("stub: sibling method") }

func (s *userSessionProviderImpl) updateUsername(args ...any) error { panic("stub: sibling method") }
