// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace Application.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorEntityController.php L22-26 → MapGet
        grp.MapGet("/headline", async (
            [FromQuery] string? text,
            AppDbContext db) =>
        {
            // L24 → default value logic
            var str = string.IsNullOrEmpty(text) ? "Contractor" : text;
            return Results.Ok(str);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L198-208 → links
        grp.MapGet("/links", async (AppDbContext db) =>
        {
            // L200-207 → build links response
            var list = new List<object>();
            list.Add(new {
                Label = "Search",
                Url = "{dto.Server}/search/contractor",
                Description = ""
            });
            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        return app;
    }


}


