// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package scaffold.
//
// Handler + service interface for the translated handlers in
// this package. Signatures sourced from the Kotlin .kt class
// when one matches the package; falls back to call-site arity
// when no source class is available.
package article

type articleService interface {
	AddComment(args ...any) (any, error)
	CreateArticle(args ...any) (any, error)
	DeleteArticle(args ...any) error
	DeleteComment(args ...any) error
	FavoriteArticle(args ...any) (any, error)
	Feed(args ...any) (any, error)
	FindArticles(args ...any) (any, error)
	GetArticle(args ...any) (GetArticleResult, error)
	GetComments(args ...any) (any, error)
	GetCurrentUser(args ...any) (any, error)
	GetCurrentUserOrNull(args ...any) (any, error)
	GetCurrentUserSessionOrNull(args ...any) (any, error)
	UnfavoriteArticle(args ...any) (any, error)
	UpdateArticle(args ...any) (any, error)
}

type GetArticleResult interface {
	ToArticleWrapper(args ...any) any
}

type SvcGetArticleResult interface {
	ToArticleWrapper(args ...any) any
}

type Handler struct {
	svc articleService
}

func NewHandler(svc articleService) *Handler { return &Handler{svc: svc} }
