// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorEntityController.php L38-50 → create
        app.MapPost("/api/v1/contractor", async (ContractorRequest request, HttpContext ctx, ContractorService contractorService) =>
        {
            var op = request.Op ?? "";
            switch (op)
            {
                case "":
                    var result = await contractorService.CreateAsync(request);
                    return result;
                default:
                    return Results.BadRequest(new { error = "Invalid operation" });
            }
        });

        // ContractorEntityController.php L52-54 → read
        app.MapGet("/api/v1/contractor/{id}", async (HttpContext ctx, string id) =>
        {
            var model = await InstantiateModelAsync(id);
            if (model == null || !model.IsPopulated())
            {
                var message = $"The requested model ({id}) does not exist";
                return Results.NotFound(new { message });
            }
            OnExists(model);
            return Display(model);
        });

        // ContractorEntityController.php L194-196 → del
        app.MapDelete("/sharedutilities/deliveryteamsearchcontroller", async (HttpContext context) =>
        {
            var request = context.Request;
            var id = request.Path.Value?.Split('/').LastOrDefault();
            if (string.IsNullOrEmpty(id) || !int.TryParse(id, out _))
            {
                var message = $"The requested entity({id}) does not exist";
                return Results.BadRequest(new { status = "error", message });
            }

            var model = InstantiateModel(id);
            if (!model.IsPopulated())
            {
                var message = $"The requested entity({id}) does not exist";
                return Results.BadRequest(new { status = "error", message });
            }

            if (SubmitDelRequest())
            {
                return Results.Ok(new { status = "request submitted" });
            }

            return Results.Ok(new { status = "completed" });
        });

        // ContractorEntityController.php L198-208 → links
        app.MapGet("/api/v1/contractor/links", (HttpContext ctx) =>
        {
            var list = new List<object>();
            list.Add(new object[] { "Search", $"{ctx.Request.Scheme}://{ctx.Request.Host}/search/contractor", "" });
            return Results.Json(list);
        });

        // ContractorEntityController.php L57-192 → update
        app.MapPut("/reporting/tsupdatesearchcontroller", async (HttpContext ctx, [FromBody] ContractorUpdateRequest request, ContractorRepository contractorRepo, IEmailSender emailSender) =>
        {
            var values = request.Data;
            var site = GetConfigValue("site", "App", "");
            var signature = GetConfigValue("ts portal signature", "Do not reply to this automated message.", "App");

            if (values.Op == "reset_pwd")
            {
                var id = values.Id;
                if (await contractorRepo.IsActiveAsync(id) && await contractorRepo.IsTsDirectAsync(id))
                {
                    var email = await contractorRepo.GetEmailByIdAsync(id);
                    var pwd = contractorRepo.GenerateRandomPassword();
                    await contractorRepo.UpdatePasswordAsync(id, pwd);

                    var msg = $"Hello <b>{await contractorRepo.GetNameByIdAsync(id)}</b>,<br/><br/>" +
                              "Your Password for the Pyramid Portal has been reset.<br/><br/>" +
                              $"Your username is: <b>{email}</b></br><br/>" +
                              $"Your temporary password is: <b>{pwd}</b></br>" +
                              $"To access your account using your new temporary password <a href=\"{site}/extern\">click here</a><br/><br/>" +
                              "<b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>" +
                              $"{site}/extern<br/><br/>" +
                              signature;

                    await emailSender.SendEmailAsync(email, "Password Reset", msg);
                    await contractorRepo.UpdateLastTsAsync(id, "lastpwdchange", "2000-01-01 00:00:00");
                }
                return Results.Redirect(request.PrevRequest);
            }

            if (values.Op == "welcome")
            {
                var ids = values.Id.Split(',').Select(id => id.Trim()).Distinct();
                foreach (var id in ids)
                {
                    if (await contractorRepo.IsActiveAsync(id) && await contractorRepo.IsTsDirectAsync(id) && await contractorRepo.HasApproverAsync(id))
                    {
                        var email = await contractorRepo.GetEmailByIdAsync(id);
                        var pwd = contractorRepo.GenerateRandomPassword();
                        var approverName = await contractorRepo.GetApproverNameAsync(id);
                        await contractorRepo.UpdatePasswordAsync(id, pwd);

                        var msg = $"Hello <b>{await contractorRepo.GetNameByIdAsync(id)}</b>,<br/><br/>" +
                                  "Welcome to the Pyramid Consulting Timesheet Portal!<br/><br/>" +
                                  "You will use this online tool to submit your timesheets for approval each week." +
                                  "Please remember to submit your timesheets in a timely matter to avoid any problems with your pay.<br/><br/>" +
                                  $"Your username is: <b>{email}</b></br><br/>" +
                                  $"Your temporary password is: <b>{pwd}</b></br></br>" +
                                  "Once you log in, the system will ask you to update your password.<br/><br/>" +
                                  $"<a href=\"{site}/extern\">Click Here</a> to access your account and change your password.<br/><br/>" +
                                  "<b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>" +
                                  $"{site}/extern<br/><br/>" +
                                  $"Approver Name : <b>{approverName}</b><br/><br/>" +
                                  signature;

                        await emailSender.SendEmailAsync(email, "Access Credentials for Pyramid Consulting's Timesheet Portal", msg);
                        await contractorRepo.UpdateLastTsAsync(id, "lastwelcomeemail");
                        await contractorRepo.UpdateLastTsAsync(id, "lastpwdchange", "2000-01-01 00:00:00");
                    }
                }
                return Results.Redirect(request.PrevRequest);
            }

            if (values.Op == "ts_setting")
            {
                var ids = values.Id.Split(',').Select(id => id.Trim()).Distinct();
                foreach (var id in ids)
                {
                    if (await contractorRepo.IsActiveAsync(id))
                    {
                        await contractorRepo.ToggleIsTsDirectAsync(id);
                        if (await contractorRepo.IsTsDirectAsync(id))
                        {
                            var email = await contractorRepo.GetEmailByIdAsync(id);
                            var pwd = contractorRepo.GenerateRandomPassword();
                            await contractorRepo.UpdatePasswordAsync(id, pwd);

                            var msg = $"Hello <b>{await contractorRepo.GetNameByIdAsync(id)}</b>,<br/><br/>" +
                                      "Welcome to Pyramid Consulting.<br/><br/>" +
                                      $"Your username is: <b>{email}</b></br><br/>" +
                                      $"Your temporary password is: {pwd}</br>" +
                                      $"To access your account using your new temporary password <a href=\"{site}/extern\">click here</a><br/><br/>" +
                                      "<b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>" +
                                      $"{site}/extern<br/><br/>" +
                                      signature;

                            await emailSender.SendEmailAsync(email, "Access Credentials for Pyramid Consulting's Timesheet Portal", msg);
                            await contractorRepo.UpdateLastTsAsync(id, "lastwelcomeemail");
                            await contractorRepo.UpdateLastTsAsync(id, "lastpwdchange", "2000-01-01 00:00:00");
                        }
                    }
                }
                return Results.Redirect(request.PrevRequest);
            }

            return Results.BadRequest();
        });

        return app;
    }

    // ContractorEntityController.php L38-50 → create
    public class ContractorService
    {
        private readonly IModelValidator _validator;
        private readonly IMessageService _messageService;

        public ContractorService(IModelValidator validator, IMessageService messageService)
        {
            _validator = validator;
            _messageService = messageService;
        }

        public async Task<IResult> CreateAsync(ContractorRequest request)
        {
            _messageService.ResetMessage();
            var obj = _validator.Validate(request.Data, true);
            if (_messageService.HasMessages())
            {
                return Results.Json(new { op = "new", model = obj, messages = _messageService.GetMessages() });
            }
            else
            {
                var success = await PreSaveAsync() && await SaveModelAsync(obj);
                if (!success)
                {
                    _messageService.AddMessage("Problem saving entry (New)");
                    return Results.Json(new { op = "new", model = obj, messages = _messageService.GetMessages() });
                }
                var url = PostSave();
                if (request.Output == "json")
                {
                    return Results.Json(new { op = "new", model = obj, messages = _messageService.GetMessages() });
                }
                else if (_messageService.HasMessages())
                {
                    return Results.Json(new { op = "new", model = obj, messages = _messageService.GetMessages() });
                }
                else if (!string.IsNullOrEmpty(url))
                {
                    ctx.Response.Redirect(url);
                    return Results.Ok();
                }
                else if (ctx.Session.TryGetValue("PREVREQUEST", out var prevRequest))
                {
                    ctx.Response.Redirect(prevRequest);
                    return Results.Ok();
                }
            }
            return Results.BadRequest();
        }

        private Task<bool> PreSaveAsync()
        {
            // Implement pre-save logic
            return Task.FromResult(true);
        }

        private Task<bool> SaveModelAsync(object model)
        {
            // Implement save logic
            return Task.FromResult(true);
        }

        private string PostSave()
        {
            // Implement post-save logic
            return "";
        }
    }

    public interface IModelValidator
    {
        object Validate(object data, bool isNew);
    }

    public interface IMessageService
    {
        void ResetMessage();
        bool HasMessages();
        void AddMessage(string message);
        List<string> GetMessages();
    }

    // ContractorEntityController.php L52-54 → read
    private static async Task<Model> InstantiateModelAsync(string id)
    {
        // Simulate model instantiation
        return await Task.FromResult(new Model { Id = id, Populated = true });
    }

    private static void OnExists(Model model)
    {
        // Logic for when the model exists
    }

    private static IResult Display(Model model)
    {
        // Logic to display the model
        return Results.Ok(new { model.Id });
    }

    private class Model
    {
        public string Id { get; set; }
        public bool Populated { get; set; }
        public bool IsPopulated() => Populated;
    }

    // ContractorEntityController.php L194-196 → del
    private static dynamic InstantiateModel(string id)
    {
        // Simulate model instantiation
        return new { IsPopulated = () => true }; // Replace with actual model logic
    }

    private static bool SubmitDelRequest()
    {
        // Simulate submission logic
        return true; // Replace with actual submission logic
    }

    // ContractorEntityController.php L210-281 → ValidateContractor
    private static Contractor ValidateContractor(Dictionary<string, JsonElement> values, bool isNew)
    {
        var messages = new List<string>();
        Contractor obj;

        if (isNew)
        {
            obj = new Contractor();
            obj.Id = null;
            obj.CreateTs = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
            obj.LastWelcomeEmail = "2000-01-01 00:00:00";
        }
        else
        {
            var id = int.Parse(values.GetValueOrDefault("id")?.ToString() ?? "0");
            if (id == 0)
            {
                messages.Add("ID must be set to Update Entry");
                return null;
            }
            else
            {
                obj = new Contractor(id);
                if (!obj.IsPopulated())
                {
                    messages.Add("ID provided for Update does not exist");
                    return null;
                }
            }
        }

        obj.Notes = values.GetValueOrDefault("notes")?.ToString().Trim();
        obj.Mi = values.GetValueOrDefault("mi")?.ToString().Trim();
        obj.IsActive = values.GetValueOrDefault("is_active")?.ToString() ?? "N";
        obj.AddressId = int.Parse(values.GetValueOrDefault("address_id")?.ToString() ?? "1");
        obj.VisaStatusTypeId = int.Parse(values.GetValueOrDefault("visa_status_type_id")?.ToString() ?? "1");
        if (obj.VisaStatusTypeId < 1)
        {
            messages.Add("Visa is invalid");
        }

        if (isNew)
        {
            foreach (var field in new[] { "firstname", "lastname", "email", "file_num", "comp_code" })
            {
                obj.GetType().GetProperty(field)?.SetValue(obj, values.GetValueOrDefault(field)?.ToString().Trim());
                if (string.IsNullOrWhiteSpace(values.GetValueOrDefault(field)?.ToString()))
                {
                    messages.Add($"{field.Replace("_", " ").ToUpper()} cannot be empty");
                }
            }
        }
        else
        {
            obj.Email = values.GetValueOrDefault("email")?.ToString();
            if (string.IsNullOrWhiteSpace(obj.Email))
            {
                messages.Add("Email cannot be empty");
            }
        }

        if (!string.IsNullOrWhiteSpace(obj.Email) && !Regex.IsMatch(obj.Email, @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
        {
            messages.Add("Please enter valid Email");
        }

        bool exists = isNew ? Contractor.ActiveByEmail(obj.Email) : Contractor.ExistsActive(obj.Id, obj.Email);
        if (exists)
        {
            messages.Add("This email is already taken");
        }

        if (!string.IsNullOrWhiteSpace(obj.Email))
        {
            obj.Username = obj.Email;
        }

        obj.TermDate = FromDisplayDate(values.GetValueOrDefault("term_date")?.ToString());
        if (obj.IsActive != "Y" && obj.TermDate <= DateTime.Parse("2000-01-01"))
        {
            messages.Add("Term Date is invalid");
        }

        if (messages.Count > 0)
        {
            throw new ValidationException(messages);
        }

        return obj;
    }

    // Helper method for date conversion
    private static DateTime FromDisplayDate(string date)
    {
        return DateTime.TryParse(date, out var result) ? result : DateTime.MinValue;
    }

    // Contractor class stub for demonstration
    public class Contractor
    {
        public int? Id { get; set; }
        public string CreateTs { get; set; }
        public string LastWelcomeEmail { get; set; }
        public string Notes { get; set; }
        public string Mi { get; set; }
        public string IsActive { get; set; }
        public int AddressId { get; set; }
        public int VisaStatusTypeId { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public DateTime TermDate { get; set; }

        public Contractor() {}
        public Contractor(int id) { /* Load from DB */ }
        public bool IsPopulated() => true; // Stub for demonstration

        public static bool ActiveByEmail(string email) => false; // Stub for demonstration
        public static bool ExistsActive(int? id, string email) => false; // Stub for demonstration
    }

    // Custom exception for validation errors
    public class ValidationException : Exception
    {
        public ValidationException(IEnumerable<string> messages) : base(string.Join("; ", messages)) {}
    }

    // ContractorEntityController.php L57-192 → update
    private static string GetConfigValue(string key, string section, string defaultValue)
    {
        // Simulate fetching a configuration value
        return defaultValue;
    }
}

public sealed record ContractorRequest(string? Op, object Data, string? Output);

public sealed record ContractorUpdateRequest
{
    public ContractorUpdateData Data { get; init; } = new();
    public string PrevRequest { get; init; } = string.Empty;
}

public sealed record ContractorUpdateData
{
    public string Op { get; init; } = string.Empty;
    public string Id { get; init; } = string.Empty;
}
