// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package sentinel errors.
//
// Sentinels referenced by the translated controllers' 
// ``errors.Is(err, ...)`` checks. Bodies are placeholder 
// messages; the wiring pass replaces them with the real 
// service-layer error definitions.
package user

import "errors"

var ErrInvalidCredentials = errors.New("invalid credentials")
var ErrNotFound = errors.New("not found")
