// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/api/ArticleController.kt
//
package article

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"net/http"
	"projbb8df72812/internal/platform/httpx"
	"strconv"
)

// ArticleController.kt L21-30 → getArticles
func (h *Handler) GetArticles(w http.ResponseWriter, r *http.Request) {
    offset := int64(0)
    if raw := r.URL.Query().Get("offset"); raw != "" {
        parsed, err := strconv.ParseInt(raw, 10, 64)
        if err != nil {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_OFFSET", "offset must be a valid number")
            return
        }
        offset = parsed
    }
    limit := 20
    if raw := r.URL.Query().Get("limit"); raw != "" {
        parsed, err := strconv.Atoi(raw)
        if err != nil || parsed < 1 {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_LIMIT", "limit must be greater than 0")
            return
        }
        limit = parsed
    }
    tag := r.URL.Query().Get("tag")
    favoritedByUser := r.URL.Query().Get("favorited")
    author := r.URL.Query().Get("author")
    currentUser, err := userProvider.GetCurrentUserSessionOrNull()
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    articlesView, err := h.svc.FindArticles(tag, author, favoritedByUser, offset, limit, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, articlesView)
}

// ArticleController.kt L70-73 → unfavoriteArticle
func (h *Handler) UnfavoriteArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, err := h.userProvider.GetCurrentUserOrFail(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    article, err := h.articleFacade.UnfavoriteArticle(slug, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, map[string]string{"status": "unfavorited"})
}

// ArticleController.kt L83-89 → addComment
func (h *Handler) AddComment(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var dto CommentWrapper[CreateCommentRequest]
    if err := json.NewDecoder(r.Body).Decode(&dto); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    currentUser, err := h.userProvider.GetCurrentUserOrFail(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    commentView, err := h.articleFacade.AddComment(slug, dto.Content, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, commentView)
}

// ArticleController.kt L48-54 → updateArticle
func (h *Handler) UpdateArticle(w http.ResponseWriter, r *http.Request) {
    var request ArticleWrapper[UpdateArticleRequest]
    if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    slug := chi.URLParam(r, "slug")
    currentUser, err := h.userProvider.GetCurrentUserOrFail(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    updatedArticle, err := h.articleFacade.UpdateArticle(request.Content, slug, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, updatedArticle.ToArticleWrapper())
}

// ArticleController.kt L76-79 → getComments
func (h *Handler) GetComments(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, err := h.userProvider.GetCurrentUserOrNull(r.Context())
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    comments, err := h.articleFacade.GetComments(slug, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, comments)
}

// ArticleController.kt L21-30 → getArticles
func (f *ArticleFacade) FindArticles(tag, authorName, favoritedByUser string, offset int64, limit int, currentUser *UserSession) (MultipleArticlesView, error) {
    favoritedBy := ""
    if favoritedByUser != "" {
        user, err := f.userRepository.FindByUsername(favoritedByUser)
        if err != nil {
            return MultipleArticlesView{}, err
        }
        favoritedBy = user.ID
    }
    author := ""
    if authorName != "" {
        user, err := f.userRepository.FindByUsername(authorName)
        if err != nil {
            return MultipleArticlesView{}, err
        }
        author = user.ID
    }
    articles, err := f.articleRepository.FindNewestArticleFilteredBy(tag, author, favoritedBy, limit, offset)
    if err != nil {
        return MultipleArticlesView{}, err
    }
    return articles.ToMultipleArticlesView(currentUser), nil
}

// ArticleController.kt L70-73 → unfavoriteArticle
func (f *articleFacade) UnfavoriteArticle(slug string, currentUser User) (ArticleView, error) {
    article, err := f.articleRepository.FindBySlugOrFail(slug)
    if err != nil {
        return ArticleView{}, err
    }
    currentUser.Unfavorite(article)
    if err := f.userRepository.Save(currentUser); err != nil {
        return ArticleView{}, err
    }
    return f.mapToArticleView(article, currentUser), nil
}

// ArticleController.kt L83-89 → addComment
func (a *ArticleFacade) AddComment(slug string, content CreateCommentRequest, currentUser User) (CommentView, error) {
    article, err := a.articleRepository.FindBySlugOrFail(slug)
    if err != nil {
        return CommentView{}, err
    }
    comment := content.ToComment(uuid.NewString(), currentUser.ID)
    article.AddComment(comment)
    if err := a.articleRepository.Save(article); err != nil {
        return CommentView{}, err
    }
    return comment.ToCommentView(currentUser.ToOwnProfileView()), nil
}

// ArticleController.kt L48-54 → updateArticle
func (f *ArticleFacade) UpdateArticle(request UpdateArticleRequest, slug string, author User) (ArticleView, error) {
    articleToUpdate, err := f.articleRepository.FindBySlugOrFail(slug)
    if err != nil {
        return ArticleView{}, err
    }
    if !articleToUpdate.IsAuthor(author) {
        return ArticleView{}, fmt.Errorf("only author can update article")
    }
    f.updateUser(request, articleToUpdate)
    savedArticle, err := f.articleRepository.Save(articleToUpdate)
    if err != nil {
        return ArticleView{}, err
    }
    return savedArticle.ToAuthorArticleView(author), nil
}

// ArticleController.kt L76-79 → getComments
func (u *UserProvider) GetCurrentUserOrNull(ctx context.Context) (*User, error) {
    // Logic to retrieve current user session
    // Implementation based on the provided Kotlin method
}
