// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorSearchController.php L108-165 → searchMap
        app.MapPost("/api/v1/contractor/search", async (HttpContext ctx, ContractorRepository repo) =>
        {
            var body = await ctx.Request.ReadFromJsonAsync<Dictionary<string, JsonElement>>() ?? new();

            // ContractorSearchController.php L117-118 → trim and prepare search terms
            var s = Regex.Replace(body.GetValueOrDefault("s").ToString() ?? "", "\s{1,}", " ").Trim();
            var s3 = (body.GetValueOrDefault("s3").ToString() ?? "").Trim();

            if (s.Length < 3 && s3.Length < 3)
            {
                // ContractorSearchController.php L119-124 → minimum character check
                return Results.Json(0);
            }

            // ContractorSearchController.php L126-127 → initialize where clauses
            var where1 = new List<string>();
            var where3 = new List<string>();

            // ContractorSearchController.php L129-136 → build where1 clause
            var list = s.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (list.Length == 1)
            {
                where1.Add($"(c.firstname LIKE @firstName OR c.lastname LIKE @lastName)");
            }
            else if (list.Length > 1)
            {
                where1.Add($"(c.firstname LIKE @firstName AND c.lastname LIKE @lastName)");
            }
            else if (string.IsNullOrEmpty(s3))
            {
                return Results.Json(0);
            }

            // ContractorSearchController.php L138-140 → build where3 clause
            if (!string.IsNullOrEmpty(s3))
            {
                where3.Add($"cc.name LIKE @s3");
            }

            where3.Add("NOT EXISTS (SELECT 'x' FROM ts_portal_map WHERE contractor_placement_id = cp.id)");

            // ContractorSearchController.php L144-161 → build and execute query
            var query = @"
                SELECT DISTINCT cp.id placement_id, CONCAT(c.firstname, ' ', c.lastname, ' (', IF(cp.is_active = 'Y', 'Active', 'In-active'), ')') name,
                       c.id id,
                       cc.name customer,
                       cc.id customer_id,
                       cp.name placement,
                       cp.deactivation_date deactivation_date,
                       tpm.vms_foreign_str vms_foreign_str,
                       cp.id placement_id,
                       c.is_active active,
                       cp.start_date start_date
                  FROM (contractor c, contractor_placement cp, customer cc)
                  LEFT OUTER JOIN (ts_portal_map tpm) ON (tpm.contractor_placement_id = cp.id)
                 WHERE cp.contractor_id = c.id
                   AND cp.customer_id = cc.id
                   AND (" + string.Join(" AND ", where1) + ")
                   " + (where3.Count > 0 ? " AND " + string.Join(" AND ", where3) : "") + ";";

            var parameters = new {
                firstName = list.Length > 0 ? list[0] + "%" : "",
                lastName = list.Length > 1 ? list[1] + "%" : "",
                s3 = s3 + "%"
            };

            var data = await repo.GetRowsAsync(query, parameters);
            var tabname = "contractor_" + Guid.NewGuid().ToString();

            return Results.Json(new { data, tabname, count = data.Count });
        });

        // ContractorSearchController.php L28-106 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (HttpContext ctx) =>
        {
            var dbConnection = ctx.RequestServices.GetRequiredService<IDbConnection>();
            var requestData = ctx.Request.Query.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.ToString());

            string searchType = string.Empty;
            if (boolValue(dfv("map", requestData, "0")))
            {
                searchType = "map";
                return await SearchMap();
            }

            bool isTsDirect = boolValue(dfv("is_ts_direct", requestData, "0"));
            var where = new List<string>();

            foreach (var field in new[] { "firstname", "lastname" })
            {
                var n = dfv(field, requestData, "").Trim();
                if (!string.IsNullOrEmpty(n))
                {
                    where.Add($"c.{field} LIKE '%{n}%' ");
                }
            }

            int employmentType = int.Parse(dfv("employment_type", requestData, "0"));
            if (employmentType != 0)
            {
                where.Add($"et.id = {employmentType}");
            }

            int cca = int.Parse(dfv("cca", requestData, "1"));
            if (cca != 1)
            {
                where.Add($"e.id = {cca}");
            }

            var customerName = dfv("customer_name", requestData, "").Trim();
            if (!string.IsNullOrEmpty(customerName))
            {
                where.Add($"cc.name LIKE '%{customerName}%' ");
            }

            where.Add($"('{dfv('is_ts_direct', requestData, '')}' = '' OR cp.is_ts_direct = '{dfv('is_ts_direct', requestData, 'N')}')");
            where.Add($"('{dfv('is_active', requestData, '')}' = '' OR cp.is_active = '{dfv('is_active', requestData, 'N')}')");

            var portalCustIds = Custmaster.GetPCIPortalCustomerIDs().Split(',').Where(id => int.TryParse(id, out var num) && num > 0).ToArray();

            var query = $@"
                SELECT DISTINCT cp.id placement_id, CONCAT(c.firstname, ' ', c.lastname, ' (', IF(cp.is_active = 'Y', 'Active', 'In-active'), ' / ', cp.id, ')') name,
                       et.name employment_type, c.id id, c.lastwelcomeemail welcomets, cc.name customer, cc.id customer_id,
                       cp.name placement, cp.deactivation_date deactivation_date, cp.is_active active,
                       IF(ccn.id != 1, CONCAT(ccn.firstname, ' ', ccn.lastname, ' / ', ccn.email), '(Not Set)') approver,
                       IF(e.id != 1, CONCAT(e.firstname, ' ', e.lastname, ' / ', e.email), '(Not Set)') cca,
                       IF((ccn.id != 1), 1, 0) show_checkbox, cp.is_ts_direct is_ts_direct, cp.start_date start_date
                  FROM contractor c, contractor_placement cp, profile p, employee_profile_map epm, employee e, employment_type et, customer cc, customer_contact ccn
                 WHERE cp.contractor_id = c.id
                   AND cp.customer_id = cc.id
                   AND ccn.id = cp.approver_id
                   AND p.contractor_placement_id = cp.id
                   AND p.id = recentProfile(cp.id)
                   AND p.employment_type_id != 1
                   AND cp.is_ref_only = 'N'
                   AND epm.profile_id = p.id
                   AND epm.description = 'CCA'
                   AND epm.employee_id = e.id
                   AND p.employment_type_id = et.id
                   AND c.id != 1
                   {(where.Count > 0 ? " AND (" + string.Join(" AND ", where) + ")" : "")}
                   {(portalCustIds.Length > 0 ? " AND cc.id IN(" + string.Join(",", portalCustIds) + ")" : "")}
                 GROUP BY cp.id
            ";

            var data = await dbConnection.QueryAsync<dynamic>(query);
            return Results.Json(new { status = data.Count() });
        });

        return app;
    }

    // ContractorSearchController.php L28-106 → search
    private static bool boolValue(string value)
    {
        return value == "1" || value.Equals("true", StringComparison.OrdinalIgnoreCase);
    }

    private static string dfv(string key, IDictionary<string, string> data, string defaultValue)
    {
        return data.TryGetValue(key, out var value) ? value : defaultValue;
    }

    private static Task<IResult> SearchMap()
    {
        // Placeholder for SearchMap logic
        return Task.FromResult<IResult>(Results.Ok(new { message = "SearchMap logic not implemented" }));
    }

    public static class Custmaster
    {
        public static string GetPCIPortalCustomerIDs()
        {
            // Placeholder for actual implementation
            return "1,2,3";
        }
    }
}


