// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (DbConnection dbConnection) =>
        {
            var query = @"
                SELECT cphcm.contractor_placement_id AS contractor_placement_id,
                       cphcm.onb_hr_checklist_type_id AS onb_hr_checklist_type_id,
                       cp.name AS placement,
                       ohct.name AS onb_hr_checklist_type,
                       cphcm.completion_date AS completion_date
                  FROM contractor_placement_hr_checklist_details_map cphcm
                  JOIN contractor_placement cp ON cphcm.contractor_placement_id = cp.id
                  JOIN onb_hr_checklist_type ohct ON cphcm.onb_hr_checklist_type_id = ohct.id
                 WHERE cphcm.is_active = 'Y'
                   AND cphcm.is_customer_mapped = 'Y'
              ORDER BY cphcm.contractor_placement_id DESC";

            var data = await dbConnection.QueryAsync<dynamic>(query);
            return Results.Json(new { status = data });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
        app.MapPost("/api/v1/contractor_placement_hr_checklist_details_search/run", async (HttpContext ctx, [FromServices] IHttpContextAccessor httpContextAccessor) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            var perform = false; // Default value

            // Contractor_placement_hr_checklist_detailsSearchController.php L20-22 → inherited behavior
            var includeExport = false; // Assume global variable
            var prepareExcel = boolValue(dov("prepare_excel", request.Data, false));
            if (prepareExcel) {
                // Logic for prepare_excel
            }
            if (includeExport && boolValue(dov("download_xlsx", request.Data, false))) {
                // Logic for download_xlsx
            }

            // Perform logic
            if (perform) {
                // Execute search logic
            }

            // Redirect to excel export
            if (includeExport && boolValue(dov("download_xlsx", request.Data, false))) {
                // Run download logic
            }

            // Organize and display
            return Results.Json(new { message = "Display result" });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
        app.MapGet("/api/v1/contractor_placement_hr_checklist_details/label", async (HttpContext ctx) =>
        {
            var labels = GetLabels();
            return Results.Ok(labels);
        });

        return app;
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
    // Helper functions
    private static bool boolValue(object value) => Convert.ToBoolean(value);

    private static object dov(string key, Dictionary<string, object> data, object defaultValue) => data.ContainsKey(key) ? data[key] : defaultValue;

    private record Request(Dictionary<string, object> Data);

    // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
    private static Dictionary<string, object[]> GetLabels()
    {
        return new Dictionary<string, object[]>
        {
            { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
            { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
            { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", "{server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
        };
    }
}

public sealed record Request(Dictionary<string, object> Data);
