// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/PortalContractorController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class PortalContractorEndpoints
{
    public static IEndpointRouteBuilder MapPortalContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/portalcontractor").WithTags("PortalContractor");

        // PortalContractorController.php L24-46 → populateHrTypes
        app.MapGet("/api/v1/contractor/{placement_id}/hr-types", async (int placement_id, IConfiguration configuration, IDbConnection dbConnection) =>
        {
            // PortalContractorController.php L27-28 → parse placement_id and config
            var externalHoursType = configuration.GetValue<string>("external hours type")?.Split('#') ?? new string[] { "1" };

            // PortalContractorController.php L29-32 → search objects and populate list
            var cph = new ContractorPlacementHoursTypeMap();
            var cpHrList = new List<int>();
            foreach (var hrObj in cph.SearchObjects(new { contractor_placement_id = placement_id }))
            {
                cpHrList.Add(Dov("hours_type_id", hrObj, 1));
            }

            // PortalContractorController.php L34-36 → conditional assignment
            if (cpHrList.Count > 0)
            {
                externalHoursType = cpHrList.Select(x => x.ToString()).ToArray();
            }

            // PortalContractorController.php L38-45 → construct and execute query
            var query = @"SELECT id, description AS value FROM hours_type WHERE is_active = 'Y' AND is_billable = 'Y'";
            if (externalHoursType.Length > 0)
            {
                query += " AND id IN @ExternalHoursType";
            }
            var result = await dbConnection.QueryAsync<int>(query, new { ExternalHoursType = externalHoursType });

            return Results.Json(result.ToList());
        });

        // PortalContractorController.php L47-55 → prePopulateTs
        app.MapPost("/api/v1/contractor/prepopulate/{contractor_id}", async (int contractor_id) =>
        {
            // Controller/PortalContractorController.php L49 → convert contractor_id to int
            contractor_id = Convert.ToInt32(contractor_id);

            // Controller/PortalContractorController.php L50-51 → check contractor_id
            if (new[] { 0, 1 }.Contains(contractor_id))
            {
                return Results.NoContent();
            }

            // Controller/PortalContractorController.php L53 → get placement_id
            var placement_id = await ContractorPlacement.PlacementByContractorIDAsync(contractor_id);

            // Controller/PortalContractorController.php L54 → prepopulate timesheet
            await TsWeekly.PrePopulateTsAsync(placement_id);

            return Results.Ok();
        });

        // PortalContractorController.php L56-85 → getTsList
        app.MapGet("/api/v1/contractor/{contractor_id}/tslist", async (int contractor_id, string status, ContractorPlacementService placementService, TsWeeklyService tsService) =>
        {
            // PortalContractorController.php L60-62 → validate contractor_id and status
            if (new[] {0, 1}.Contains(contractor_id) || string.IsNullOrEmpty(status))
            {
                return Results.NoContent();
            }

            // PortalContractorController.php L64 → get placement_id
            var placement_id = await placementService.PlacementByContractorIDAsync(contractor_id);

            // PortalContractorController.php L65-78 → determine method
            string method = status switch
            {
                "p" => "pendingTs",
                "r" => "rejectedTs",
                "a" => "pendingApproveTs",
                "ap" => "approvedTs",
                _ => ""
            };

            // PortalContractorController.php L79-83 → fetch list
            var list = method == "approvedTs"
                ? await tsService.ApprovedTsAsync(placement_id)
                : await tsService.GenericTsAsync(method, placement_id);

            return Results.Json(list);
        });

        // PortalContractorController.php L87-98 → getLeaveList
        app.MapGet("/api/v1/contractor/{contractor_id}/leaves", async (int contractor_id, int status_id, [FromServices] IModel model) =>
        {
            // PortalContractorController.php L91-93 → validate contractor_id
            if (contractor_id == 0 || contractor_id == 1)
            {
                return Results.BadRequest(new { error = "Invalid contractor_id" });
            }

            // PortalContractorController.php L95 → fetch leave list
            var list = await Leaves.LeaveListQueryAsync(contractor_id, status_id, "N", model);
            return Results.Json(list);
        });

        // PortalContractorController.php L100-112 → getSum
        app.MapGet("/api/v1/contractor/sum", (HttpContext ctx, [FromQuery] string pattern) =>
        {
            var array = ctx.Request.Query["array"];
            var sum = GetSum(array, pattern);
            return Results.Json(new { sum });
        });

        // PortalContractorController.php L636-695 → handleLeaveEdit
        app.MapPost("/api/v1/contractor/leave/edit", async (HttpContext ctx, ContractorRepository contractorRepo, LeaveRepository leaveRepo, CustomerRepository customerRepo) =>
        {
            var userId = ctx.User.FindFirst("id")?.Value;
            var leaveId = int.Parse(ctx.Request.Query["leave_id"]);
            var messages = new List<string>();

            if (!await contractorRepo.IsAllowedForLeaveAsync(userId))
            {
                messages.Add("No Leave specified");
                return Results.BadRequest(new { messages });
            }

            if (leaveId < 1)
            {
                messages.Add("No Leave specified");
                return Results.BadRequest(new { messages });
            }

            var contractorId = await leaveRepo.CreatedByAsync(leaveId);
            if (userId != contractorId)
            {
                messages.Add("This leave application provided does not belong to you");
                return Results.BadRequest(new { messages });
            }

            if (!await contractorRepo.IsTsDirectAsync(userId) || !await contractorRepo.HasApproverAsync(contractorId))
            {
                messages.Add("This leave application provided does not belong to you");
                return Results.BadRequest(new { messages });
            }

            var leave = await leaveRepo.GetLeaveAsync(leaveId);
            leave.IsApprover = bool.Parse(ctx.Session.GetString("is_approver") ?? "false");
            leave.ContractorName = await contractorRepo.GetNameByIdAsync(contractorId);
            var placementId = await contractorRepo.GetPlacementByContractorIdAsync(contractorId);

            var weeks = await leaveRepo.GetUniquePeriodsAsync(leave.FromDate, leave.ToDate, "week");
            bool isApproved = false;
            if (weeks.Count > 1)
            {
                foreach (var week in weeks)
                {
                    var tsWeekly = await leaveRepo.GetTsWeeklyAsync(placementId, week);
                    if (tsWeekly != null && tsWeekly.StatusId == 4)
                    {
                        isApproved = true;
                        break;
                    }
                }
            }
            else
            {
                isApproved = await leaveRepo.CheckApprovedTsAsync(leave);
            }

            leave.IsCancelAllowed = isApproved ? "N" : "Y";
            leave.CustomerName = await customerRepo.GetNameByIdAsync(await contractorRepo.GetCustomerByPlacementIdAsync(placementId));
            leave.StatusName = await leaveRepo.GetStatusNameByIdAsync(leave.StatusTypeId);
            leave.TypeName = await leaveRepo.GetTypeNameByIdAsync(leave.TypeId);
            leave.LeaveHistory = await leaveRepo.GetLeaveHistoryAsync(leaveId);

            return Results.Ok(new { leave });
        });

        // PortalContractorController.php L697-725 → handleHomePage
        app.MapGet("/api/v1/portal/homepage", async (HttpContext ctx, ContractorRepository contractorRepo) =>
        {
            var userId = ctx.User.FindFirst("id")?.Value;
            if (userId == null) return Results.Unauthorized();

            var model = new {
                AcadTrainee1099 = false,
                Pending = contractorRepo.GetTsList(userId, 'p'),
                Rejected = contractorRepo.GetTsList(userId, 'r'),
                Pendappr = contractorRepo.GetTsList(userId, 'a'),
                SubmittalHistory = contractorRepo.GetTsList(userId, 'a'),
                Labels = new[] { "Week End Date", "Customer", "Approver", "Hours" },
                IsAllowedLeave = Contractor.IsAllowedForLeave(userId) ? "Y" : "N"
            };

            var menu = contractorRepo.MenuDefinition();
            if (!Contractor.IsAllowedForLeave(userId))
            {
                menu.Remove("Leave");
            }

            contractorRepo.PrePopulateTs(userId);

            var placementId = ContractorPlacement.PlacementByContractorId(userId);
            var cpObj = new ContractorPlacement(placementId);
            if (cpObj.IsPopulated())
            {
                var customerId = ContractorPlacement.CustomerByPlacementId(placementId);
                var empType = cpObj.GetContractTypeName();
                if (customerId == 1000 && empType == "1099")
                {
                    model = model with { AcadTrainee1099 = true };
                }
            }

            return Results.Json(new { model, menu });
        });

        // PortalContractorController.php L743-770 → handleLeaveReport
        app.MapPost("/api/v1/contractor/leavereport", async (HttpContext ctx) =>
        {
            var userId = ctx.User.FindFirst("id")?.Value;
            var menu = MenuDefinition();
            if (!Contractor.IsAllowedForLeave(userId))
            {
                menu.Remove("Leave");
            }

            var model = new LeaveReportModel();
            var values = await ctx.Request.ReadFromJsonAsync<Dictionary<string, string>>() ?? new();
            var fromDate = values.GetValueOrDefault("from_date")?.Trim() ?? "";
            var toDate = values.GetValueOrDefault("to_date")?.Trim() ?? "";

            if (string.IsNullOrEmpty(fromDate))
            {
                fromDate = FinanceCalendar.ByDateMonthStart(DateAddMonths(DateTime.Now.ToString("yyyy-MM-dd"), -2));
            }
            if (string.IsNullOrEmpty(toDate))
            {
                toDate = FinanceCalendar.ByDateMonthEnd(DateAddMonths(fromDate, 2));
            }

            var statusId = int.TryParse(values.GetValueOrDefault("status_id"), out var sid) ? sid : 0;
            ctx.Session.SetString("PREVREQUEST", CreateUrl(ctx.Request.Path, values));

            model.FromDate = fromDate;
            model.ToDate = toDate;
            model.StatusId = statusId;
            model.AppldList = GetLeaveList(userId, statusId);
            model.Labels = new[] { "From Date", "To Date", "Status", "Applied Date", "Action" };
            var action = $"{BaseUrl}/leavereport";

            return RenderPage("extern_leave_report_contractor_timesheet.php", model);
        });

        // PortalContractorController.php L772-782 → handleTsLeave
        app.MapPost("/api/v1/contractor/handleTsLeave", async (HttpContext ctx, ContractorRepository contractorRepo) =>
        {
            var userId = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var menu = MenuDefinition();

            if (!await contractorRepo.IsAllowedForLeaveAsync(userId))
            {
                menu.Remove("Leave");
            }

            var model = new { }; // Equivalent to new StdClass
            var action = $"{BaseUrl}/apply";

            return RenderPage("extern_leave_contractor_timesheet.php", menu, model, action);
        });

        // PortalContractorController.php L784-834 → handle
        app.MapPost("/api/v1/portal/contractor", async (HttpContext ctx) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            var clientIP = ctx.Connection.RemoteIpAddress?.ToString();

            if (clientIP == "10.125.30.135")
            {
                SetSessionInfo(request.Data.GetValueOrDefault("fake_user_id", 1));
                var userfield = $"{PortalPoint} portal user";
                userfield = $"{PortalPoint} portal user detail";
                UserObj = ctx.Session.Get<Object>(userfield);
            }
            else if (!VerifyLogin())
            {
                return Results.Unauthorized();
            }

            LogAccess(request);

            switch (request.Module)
            {
                case "edit":
                    return await HandleTsEdit();
                case "save":
                    return await HandleTsSave();
                case "submit":
                    request.Data["submit"] = 1;
                    return await HandleTsSave();
                case "report":
                    return await HandleTsReport();
                case "leavereport":
                    return await HandleLeaveReport();
                case "apply":
                    return await HandleLeaveSave();
                case "editleave":
                    return await HandleLeaveEdit();
                case "leave":
                    return await HandleTsLeave();
                case "list":
                case "login":
                case "":
                    return await HandleHomePage();
                default:
                    return Results.NoContent();
            }
        });

        // PortalContractorController.php L727-741 → handleTsReport
        app.MapGet("/api/v1/portal-contractor/ts-report", async (HttpContext ctx, ContractorRepository contractorRepo) =>
        {
            var userId = ctx.User.FindFirst("id")?.Value;
            if (userId == null)
            {
                return Results.Unauthorized();
            }

            var menu = MenuDefinition();
            if (!await contractorRepo.IsAllowedForLeaveAsync(int.Parse(userId)))
            {
                menu.Remove("Leave");
            }

            var model = new
            {
                aprvd_list = await GetTsListAsync(int.Parse(userId), "ap"),
                is_allowed_leave = await contractorRepo.IsAllowedForLeaveAsync(int.Parse(userId)) ? "Y" : "N",
                labels = new[] { "Week End Date", "Customer", "Contractor", "Hours" }
            };

            var action = $"{BaseUrl}/report";
            return RenderPage("extern_report_contractor_timesheet.php", model, menu, action);
        });

        return app;
    }

    // PortalContractorController.php L24-46 → populateHrTypes
    // PortalContractorController.php L32 → dov function equivalent
    private static int Dov(string key, dynamic hrObj, int defaultValue)
    {
        return hrObj.ContainsKey(key) ? (int)hrObj[key] : defaultValue;
    }

    // PortalContractorController.php L29 → ContractorPlacementHoursTypeMap class stub
    public class ContractorPlacementHoursTypeMap
    {
        public IEnumerable<dynamic> SearchObjects(object criteria)
        {
            // Simulate search logic; replace with actual implementation
            return new List<dynamic>();
        }
    }

    // PortalContractorController.php L100-112 → getSum
    private static double GetSum(IQueryCollection array, string pattern)
    {
        double sum = 0;
        foreach (var key in array.Keys)
        {
            var value = array[key];
            var expKey = Regex.Split(key, pattern);
            if (expKey.Length > 1 && !string.IsNullOrEmpty(expKey[1]))
            {
                if (double.TryParse(value, out var numericValue))
                {
                    sum += numericValue;
                }
            }
        }
        return sum;
    }

    // PortalContractorController.php L743-770 → handleLeaveReport
    private static string DateAddMonths(string date, int months)
    {
        var parsedDate = DateTime.Parse(date);
        return parsedDate.AddMonths(months).ToString("yyyy-MM-dd");
    }

    private static string CreateUrl(string path, Dictionary<string, string> values)
    {
        var query = string.Join("&", values.Select(kv => $"{kv.Key}={kv.Value}"));
        return $"{path}?{query}";
    }

    private static List<object> GetLeaveList(string userId, int statusId)
    {
        // Placeholder for actual implementation
        return new List<object>();
    }

    private static Dictionary<string, object> MenuDefinition()
    {
        // Placeholder for actual implementation
        return new Dictionary<string, object>();
    }

    private static object RenderPage(string page, LeaveReportModel model)
    {
        // Placeholder for actual implementation
        return new { page, model };
    }

    // PortalContractorController.php L772-782 → handleTsLeave
    private static Dictionary<string, object> MenuDefinition()
    {
        // Implement menu definition logic here
        return new Dictionary<string, object>();
    }

    private static IResult RenderPage(string page, Dictionary<string, object> menu, object model, string action)
    {
        // Implement rendering logic here
        return Results.Ok(new { page, menu, model, action });
    }

    // PortalContractorController.php L784-834 → handle
    private static void SetSessionInfo(int userId)
    {
        // Implementation for setting session info
    }

    private static bool VerifyLogin()
    {
        // Implementation for verifying login
        return true;
    }

    private static void LogAccess(Request request)
    {
        // Implementation for logging access
    }

    private static Task<IResult> HandleTsEdit()
    {
        // Implementation for handling TS edit
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleTsSave()
    {
        // Implementation for handling TS save
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleTsReport()
    {
        // Implementation for handling TS report
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleLeaveReport()
    {
        // Implementation for handling leave report
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleLeaveSave()
    {
        // Implementation for handling leave save
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleLeaveEdit()
    {
        // Implementation for handling leave edit
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleTsLeave()
    {
        // Implementation for handling TS leave
        return Task.FromResult<IResult>(Results.Ok());
    }

    private static Task<IResult> HandleHomePage()
    {
        // Implementation for handling home page
        return Task.FromResult<IResult>(Results.Ok());
    }

    // PortalContractorController.php L727-741 → handleTsReport
    private static Dictionary<string, object> MenuDefinition()
    {
        return new Dictionary<string, object>(); // Implement menu definition logic
    }

    private static Task<List<object>> GetTsListAsync(int userId, string status)
    {
        return Task.FromResult(new List<object>()); // Implement timesheet list retrieval logic
    }

    private static IResult RenderPage(string page, object model, Dictionary<string, object> menu, string action)
    {
        // Implement page rendering logic
        return Results.Ok(new { page, model, menu, action });
    }
}

public sealed record LeaveReportModel
{
    public string FromDate { get; init; }
    public string ToDate { get; init; }
    public int StatusId { get; init; }
    public List<object> AppldList { get; init; }
    public string[] Labels { get; init; }
}

public sealed record Request
{
    public string Module { get; init; }
    public Dictionary<string, object> Data { get; init; }
}
