# Use the official .NET 8 SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY src/CustomerAndAccountContractor.Api/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY src/CustomerAndAccountContractor.Api/. ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# Set the environment variable for the port
ENV ASPNETCORE_URLS=http://+:8080

# Expose port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["dotnet", "CustomerAndAccountContractor.Api.dll"]