// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/ArticleFacade.kt
//
package article

import (
	"context"
	"fmt"
	"github.com/google/uuid"
)

// ArticleFacade.kt L25-33 → createArticle

type Service interface {
    CreateArticle(ctx context.Context, request CreateArticleRequest, author User) (ArticleView, error)
}

type articleFacadeImpl struct {
    articleRepo ArticleRepository
    tagRepo     TagRepository
	userRepo articleFacadeImpl_userRepo_iface}

type articleFacadeImpl_userRepo_iface interface {
	FindAuthorByArticle(args ...any) (any, error)
	FindByUsername(args ...any) (any, error)
	Save(args ...any) error
}


func NewService(articleRepo ArticleRepository, tagRepo TagRepository) Service {
    return &articleFacadeImpl{articleRepo: articleRepo, tagRepo: tagRepo}
}

func (s *articleFacadeImpl) CreateArticle(ctx context.Context, request CreateArticleRequest, author User) (ArticleView, error) {
    id := uuid.New().String()
    newArticle := request.ToArticle(id, author.ID)
    savedArticle, err := s.articleRepo.Save(ctx, newArticle)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }
    if err := s.tagRepo.SaveAllTags(ctx, savedArticle.Tags); err != nil {
        return ArticleView{}, fmt.Errorf("save tags: %w", err)
    }
    authorProfileView := author.ToOwnProfileView()
    return savedArticle.ToArticleView(authorProfileView, author), nil
}

// ArticleFacade.kt L34-39 → getArticle

func (s *articleFacadeImpl) GetArticle(ctx context.Context, slug string, currentUser *User) (ArticleView, error) {
	article, err := s.articleRepo.FindBySlugOrFail(ctx, slug)
	if err != nil {
		return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
	}
	author, err := s.userRepo.FindAuthorByArticle(ctx, article)
	if err != nil {
		return ArticleView{}, fmt.Errorf("find author by article: %w", err)
	}
	return article.ToArticleView(author, currentUser), nil
}

// ArticleFacade.kt L40-52 → updateArticle

// ArticleFacade.kt L53-62 → deleteArticle

// ArticleFacade.kt L63-78 → findArticles
func (s *articleFacadeImpl) FindArticles(ctx context.Context, tag, authorName, favoritedByUser string, offset int64, limit int, currentUser *User) (MultipleArticlesView, error) {
    var favoritedBy, author *User
    var err error
    if favoritedByUser != "" {
        favoritedBy, err = s.userRepo.FindByUsername(ctx, favoritedByUser)
        if err != nil {
            return MultipleArticlesView{}, fmt.Errorf("find favorited by user: %w", err)
        }
    }
    if authorName != "" {
        author, err = s.userRepo.FindByUsername(ctx, authorName)
        if err != nil {
            return MultipleArticlesView{}, fmt.Errorf("find author by name: %w", err)
        }
    }
    articles, err := s.articleRepo.FindNewestArticleFilteredBy(ctx, tag, author.ID, favoritedBy, limit, offset)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("find articles: %w", err)
    }
    var articleViews []ArticleView
    for _, article := range articles {
        view := mapToArticleView(article, currentUser)
        articleViews = append(articleViews, view)
    }
    return toMultipleArticlesView(articleViews), nil
}

// ArticleFacade.kt L79-85 → feed
func (s *articleFacadeImpl) Feed(ctx context.Context, offset int64, limit int, user User) (MultipleArticlesView, error) {
    articles, err := s.articleRepo.FindNewestArticlesByAuthorIds(ctx, user.FollowingIDs, offset, limit)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("feed: %w", err)
    }
    var articleViews []ArticleView
    for _, article := range articles {
        articleView := mapToArticleView(article, user)
        articleViews = append(articleViews, articleView)
    }
    return toMultipleArticlesView(articleViews), nil
}

// ArticleFacade.kt L97-103 → favoriteArticle

// ArticleFacade.kt L104-110 → unfavoriteArticle
func (s *articleFacadeImpl) UnfavoriteArticle(ctx context.Context, slug string, currentUser User) (ArticleView, error) {
    article, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    if _, err := currentUser.Unfavorite(article); err != nil {
        return ArticleView{}, fmt.Errorf("unfavorite article: %w", err)
    }

    if _, err := s.userRepo.Save(ctx, currentUser); err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }

    return s.mapToArticleView(article, currentUser), nil
}

// ArticleFacade.kt L111-112 → getTags

// ArticleFacade.kt L116-123 → addComment

// ArticleFacade.kt L124-133 → deleteComment

// ArticleFacade.kt L141-148 → getComments
