// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package layer scaffold.
//
// Receiver struct for the translated `func (r *articleRepositoryImpl)`
// methods in this package, with dependency-interface-typed fields
// so the layer's outbound calls resolve. A real wiring pass swaps
// the interfaces for concrete collaborators.
package article

import (
	"github.com/jackc/pgx/v5/pgxpool"
)

type articleRepositoryImpl struct {
	pool *pgxpool.Pool
}
