// SPDX-License-Identifier: Apache-2.0
// Generated by wiring-auth-go-v1.0 — Vansham V2 §3.3 fix.
//
// JWKS-backed key set. Polls a remote JWKS endpoint with HTTP caching;
// supports kid rotation by re-fetching on a cache miss. A typical
// production wiring runs against the engagement's IdP (Auth0, Cognito,
// Keycloak, etc.). For closed-network deployments swap in StaticKeySet.
package auth

import (
	"crypto/rsa"
	"encoding/json"
	"errors"
	"fmt"
	"math/big"
	"net/http"
	"sync"
	"time"

	"encoding/base64"
)

// StaticKeySet — hand-loaded {kid → *rsa.PublicKey} map. The simplest
// implementation: useful for tests and air-gapped environments where
// keys are mounted as files.
type StaticKeySet struct {
	keys map[string]*rsa.PublicKey
}

func NewStaticKeySet(keys map[string]*rsa.PublicKey) *StaticKeySet {
	return &StaticKeySet{keys: keys}
}

func (s *StaticKeySet) PublicKey(kid string) (any, error) {
	k, ok := s.keys[kid]
	if !ok {
		return nil, fmt.Errorf("unknown kid: %s", kid)
	}
	return k, nil
}

// JWKSKeySet — polls a remote JWKS URL with HTTP caching. Re-fetches
// on a cache miss (kid rotated), with a minimum refresh interval to
// stop a malicious client from flooding the IdP via probes.
type JWKSKeySet struct {
	url             string
	client          *http.Client
	mu              sync.RWMutex
	cache           map[string]*rsa.PublicKey
	lastFetch       time.Time
	minRefreshDelay time.Duration
}

func NewJWKSKeySet(url string) *JWKSKeySet {
	return &JWKSKeySet{
		url:             url,
		client:          &http.Client{Timeout: 5 * time.Second},
		cache:           map[string]*rsa.PublicKey{},
		minRefreshDelay: 30 * time.Second,
	}
}

func (j *JWKSKeySet) PublicKey(kid string) (any, error) {
	j.mu.RLock()
	if k, ok := j.cache[kid]; ok {
		j.mu.RUnlock()
		return k, nil
	}
	j.mu.RUnlock()

	if err := j.refresh(); err != nil {
		return nil, fmt.Errorf("jwks refresh: %w", err)
	}

	j.mu.RLock()
	defer j.mu.RUnlock()
	if k, ok := j.cache[kid]; ok {
		return k, nil
	}
	return nil, fmt.Errorf("unknown kid after refresh: %s", kid)
}

func (j *JWKSKeySet) refresh() error {
	j.mu.Lock()
	defer j.mu.Unlock()
	if time.Since(j.lastFetch) < j.minRefreshDelay {
		return nil // a parallel goroutine already refreshed
	}
	req, err := http.NewRequest("GET", j.url, nil)
	if err != nil {
		return err
	}
	resp, err := j.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("jwks fetch: status %d", resp.StatusCode)
	}
	var doc struct {
		Keys []struct {
			Kid string `json:"kid"`
			Kty string `json:"kty"`
			Alg string `json:"alg"`
			N   string `json:"n"`
			E   string `json:"e"`
		} `json:"keys"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&doc); err != nil {
		return err
	}
	next := map[string]*rsa.PublicKey{}
	for _, k := range doc.Keys {
		if k.Kty != "RSA" {
			continue
		}
		pub, err := jwkToRSAPublicKey(k.N, k.E)
		if err != nil {
			continue
		}
		next[k.Kid] = pub
	}
	if len(next) == 0 {
		return errors.New("jwks: no RSA keys")
	}
	j.cache = next
	j.lastFetch = time.Now()
	return nil
}

func jwkToRSAPublicKey(nB64, eB64 string) (*rsa.PublicKey, error) {
	nBytes, err := base64.RawURLEncoding.DecodeString(nB64)
	if err != nil {
		return nil, err
	}
	eBytes, err := base64.RawURLEncoding.DecodeString(eB64)
	if err != nil {
		return nil, err
	}
	n := new(big.Int).SetBytes(nBytes)
	e := 0
	for _, b := range eBytes {
		e = e<<8 | int(b)
	}
	return &rsa.PublicKey{N: n, E: e}, nil
}
