// SPDX-License-Identifier: Apache-2.0
// Generated by wiring-auth-go-v1.0 — Vansham V2 §3.5 partial fix
// (middleware steps 11+12: authn + authz).
//
// chi-compatible middleware. Mount RequireAuth at the route group that
// requires a validated principal. Mount RequireScope inside it when a
// specific scope is needed (admin endpoints, etc.).
//
// Package name is `appmw` (not `middleware`) deliberately — chi's own
// package `github.com/go-chi/chi/v5/middleware` is already named
// `middleware`. Keeping both unqualified would collide in any handler
// that imports both. Domain handlers reference us as `appmw.RequireAuth`.
package appmw

import (
	"net/http"

	"your.module/path/internal/platform/auth"
)

// RequireAuth — parses the Authorization bearer token, validates it
// against the auth.Validator, and stashes the claims on the request
// context. Failures return 401 with NO error detail (cf. ErrInvalidToken).
func RequireAuth(v *auth.Validator) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			claims, err := v.FromRequest(r)
			if err != nil {
				w.Header().Set("WWW-Authenticate", `Bearer realm="api"`)
				http.Error(w, "unauthorized", http.StatusUnauthorized)
				return
			}
			ctx := auth.WithClaims(r.Context(), claims)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

// RequireScope — wraps a handler so requests without the named scope
// in their claims get 403. Must run AFTER RequireAuth (or it always 403s).
func RequireScope(scope string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			scopes := auth.ScopesFromContext(r.Context())
			for _, s := range scopes {
				if s == scope {
					next.ServeHTTP(w, r)
					return
				}
			}
			http.Error(w, "forbidden", http.StatusForbidden)
		})
	}
}
