// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: chat/src/main/kotlin/com/plcoding/chirp/api/controllers/ChatController.kt
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Proj406b62972f.Endpoints;

public static class ChatEndpoints
{
    public static IEndpointRouteBuilder MapChatEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/chat").WithTags("Chat");

        // ChatController.kt L59-63 → getChatsForUser
        // internal/chat/handler.go
        package chat

        import (
            "net/http"
            "github.com/go-chi/chi/v5"
            "github.com/google/uuid"
            "github.com/<org>/<repo>/internal/platform/httpx"
        )

        func (h *Handler) GetChatsForUser(w http.ResponseWriter, r *http.Request) {
            userIdRaw := chi.URLParam(r, "userId")
            userId, err := uuid.Parse(userIdRaw)
            if err != nil {
                httpx.WriteError(w, http.StatusBadRequest, "INVALID_USER_ID", "userId must be a uuid")
                return
            }
            chats, err := h.svc.GetChatsForUser(r.Context(), userId)
            if err != nil {
                httpx.WriteInternal(w, r, err)
                return
            }
            httpx.WriteJSON(w, http.StatusOK, chats)
        }

        return app;
    }


}


