FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["FormTranslationService/FormTranslationService.csproj", "FormTranslationService/"]
RUN dotnet restore "FormTranslationService/FormTranslationService.csproj"
COPY . .
WORKDIR "/src/FormTranslationService"
RUN dotnet build "FormTranslationService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FormTranslationService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FormTranslationService.dll"]