// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package scaffold.
//
// Handler + service interface for the translated handlers in
// this package. Signatures sourced from the Kotlin .kt class
// when one matches the package; falls back to call-site arity
// when no source class is available.
package user

type userService interface {
	Follow(args ...any) (any, error)
	GetCurrentUserSession(args ...any) (any, error)
	GetCurrentUserSessionOrNull(args ...any) (any, error)
	GetProfile(args ...any) (any, error)
	Login(args ...any) (any, error)
	Signup(args ...any) (any, error)
	Unfollow(args ...any) (any, error)
	UpdateUser(args ...any) (any, error)
}

type Handler struct {
	svc userService
}

func NewHandler(svc userService) *Handler { return &Handler{svc: svc} }
