// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → MapGet
        grp.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (AppDbContext db) =>
        {
            var query = from cphcm in db.Set<ContractorPlacementHrChecklistDetailsMap>()
                        join cp in db.Set<ContractorPlacement>() on cphcm.ContractorPlacementId equals cp.Id
                        join ohct in db.Set<OnbHrChecklistType>() on cphcm.OnbHrChecklistTypeId equals ohct.Id
                        where cphcm.IsActive == "Y" && cphcm.IsCustomerMapped == "Y"
                        orderby cphcm.ContractorPlacementId descending
                        select new
                        {
                            contractor_placement_id = cphcm.ContractorPlacementId,
                            onb_hr_checklist_type_id = cphcm.OnbHrChecklistTypeId,
                            placement = cp.Name,
                            onb_hr_checklist_type = ohct.Name,
                            completion_date = cphcm.CompletionDate
                        };

            var data = await query.ToListAsync();
            return Results.Ok(new { status = data });
        });

        return app;
    }


}


