// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — fallback type aliases.
//
// These ``type X = any`` aliases let the package compile
// when the LLM-emitted code references types that aren't
// declared in this package and weren't resolved via
// cross-package imports. The wiring pass replaces these
// with the real type (struct OR cross-package import)
// — they are intentionally permissive (``any``) so the
// compiler doesn't reject valid call sites that pass
// typed values.
package user

type EncodedPassword = any
type InvalidRequestError = any
type PasswordService interface {
	EncodePassword(args ...any) (EncodedPassword, error)
}
type ProfileView = any
type Repository interface {
	ExistsByEmail(args ...any) (bool, error)
	ExistsByUsername(args ...any) (bool, error)
	FindByEmail(args ...any) (User, error)
	FindByUsername(args ...any) (User, error)
	Save(args ...any) (User, error)
	UpdateUser(args ...any) error
}
type Token struct {
	Token any
	UserID any
}
type UpdateUserRequest struct {
	Email any
	Password any
	Username any
	ToUser func(args ...any) User
}
type User struct {
	CreatedAt any
	Email any
	EncodedPassword any
	ID any
	Token any
	User any
	Username any
	Follow func(args ...any) (any, error)
	ToFollowedProfileView func(args ...any) ProfileView
	ToUserView func(args ...any) UserView
}
type UserSession struct {
	Token any
	User any
}
type UserView = any
