// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package sentinel errors (post-Phase-2 scan).
package user

import "errors"

var ErrNotFound = errors.New("not found")
