// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — fallback type aliases.
//
// These ``type X = any`` aliases let the package compile
// when the LLM-emitted code references types that aren't
// declared in this package and weren't resolved via
// cross-package imports. The wiring pass replaces these
// with the real type (struct OR cross-package import)
// — they are intentionally permissive (``any``) so the
// compiler doesn't reject valid call sites that pass
// typed values.
package article

type Article struct {
	AuthorID any
	Body any
	Content any
	CreatedAt any
	Description any
	ID any
	Slug any
	Tags any
	Title any
	UpdatedAt any
	id any
	IsAuthor func(args ...any) bool
	ToArticleView func(args ...any) ArticleView
	ToAuthorArticleView func(args ...any) ArticleView
}
type ArticleRepository interface {
	DeleteBySlug(args ...any) error
	FindBySlug(args ...any) (Article, error)
	FindNewestArticlesByAuthorIds(args ...any) (Article, error)
	Save(args ...any) (Article, error)
}
type ArticleView = any
type CreateArticleRequest interface {
	ToArticle(args ...any) Article
}
type MultipleArticlesView = any
type TagRepository interface {
	SaveAllTags(args ...any) error
}
type UpdateArticleRequest interface {
	ToArticle(args ...any) Article
}
type User struct {
	FollowingIDs any
	ID any
	ToOwnProfileView func(args ...any) any
	Unfavorite func(args ...any) (any, error)
}
