// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/ArticleFacade.kt
//
package article

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"net/http"
	"projbb8df72812/internal/platform/auth"
	"projbb8df72812/internal/platform/httpx"
	"strconv"
)

// ArticleFacade.kt L25-33 → createArticle
// internal/article/articleFacadeImpl.go


type Service interface {
    CreateArticle(ctx context.Context, request CreateArticleRequest, author User) (ArticleView, error)
}

type articleFacadeImpl struct {
    articleRepo ArticleRepository
    tagRepo     TagRepository
}

func NewService(articleRepo ArticleRepository, tagRepo TagRepository) Service {
    return &articleFacadeImpl{articleRepo: articleRepo, tagRepo: tagRepo}
}

func (s *articleFacadeImpl) CreateArticle(ctx context.Context, request CreateArticleRequest, author User) (ArticleView, error) {
    id := uuid.New().String()
    newArticle := request.ToArticle(id, author.ID)

    savedArticle, err := s.articleRepo.Save(ctx, newArticle)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }

    if err := s.tagRepo.SaveAllTags(ctx, savedArticle.Tags); err != nil {
        return ArticleView{}, fmt.Errorf("save tags: %w", err)
    }

    authorProfileView := author.ToOwnProfileView()
    return savedArticle.ToArticleView(authorProfileView, author), nil
}

// ArticleFacade.kt L34-39 → getArticle

// ArticleFacade.kt L40-52 → updateArticle
func (s *articleFacadeImpl) UpdateArticle(ctx context.Context, request UpdateArticleRequest, slug string, author User) (ArticleView, error) {
    articleToUpdate, err := s.repo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    if !articleToUpdate.IsAuthor(author) {
        return ArticleView{}, ErrInvalidRequest("only author can update article")
    }

    updateUser(request, articleToUpdate)

    savedArticle, err := s.repo.Save(ctx, articleToUpdate)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }

    return savedArticle.ToAuthorArticleView(author), nil
}

// ArticleFacade.kt L53-62 → deleteArticle
func (s *articleFacadeImpl) DeleteArticle(ctx context.Context, slug string, user User) error {
    article, err := s.repo.FindBySlug(ctx, slug)
    if errors.Is(err, ErrNotFound) {
        return fmt.Errorf("delete article: %w", ErrNotFound)
    }
    if err != nil {
        return fmt.Errorf("delete article: %w", err)
    }

    if !article.IsAuthor(user) {
        return fmt.Errorf("delete article: %w", ErrInvalidRequest)
    }

    if err := s.repo.DeleteBySlug(ctx, slug); err != nil {
        return fmt.Errorf("delete article: %w", err)
    }
    return nil
}

// ArticleFacade.kt L63-78 → findArticles

// ArticleFacade.kt L79-85 → feed
func (s *articleFacadeImpl) Feed(ctx context.Context, offset int64, limit int, user User) (MultipleArticlesView, error) {
    articles, err := s.repo.FindNewestArticlesByAuthorIds(ctx, user.FollowingIDs, offset, limit)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("feed: %w", err)
    }
    var articleViews []ArticleView
    for _, article := range articles {
        articleView := mapToArticleView(article, user)
        articleViews = append(articleViews, articleView)
    }
    return toMultipleArticlesView(articleViews), nil
}

// ArticleFacade.kt L97-103 → favoriteArticle

// ArticleFacade.kt L104-110 → unfavoriteArticle
func (s *articleFacadeImpl) UnfavoriteArticle(ctx context.Context, slug string, currentUser User) (ArticleView, error) {
    article, err := s.articleRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    if err := currentUser.Unfavorite(article); err != nil {
        return ArticleView{}, fmt.Errorf("unfavorite article: %w", err)
    }

    if err := s.userRepo.Save(ctx, currentUser); err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }

    return s.mapToArticleView(article, currentUser), nil
}

// ArticleFacade.kt L111-112 → getTags

// ArticleFacade.kt L116-123 → addComment

// ArticleFacade.kt L124-133 → deleteComment

// ArticleFacade.kt L141-148 → getComments
