// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
        app.MapPost("/api/v1/contractor_placement_hr_checklist_details_search/run", async (HttpContext ctx) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            var includeExport = false; // Assuming a default value, adjust if needed

            if (BoolValue(Dov("prepare_excel", request.Data, false)))
            {
                // Handles Search (Download Only)
                ctx.Items["createcsv"] = "N";
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                // Handles Page Options Download button
                ctx.Items["createcsv"] = "N";
                PreDownload(ctx);
            }

            var perform = true;
            var embed = Dfv("embed", request.Data, 0);
            var model = new Model
            {
                Param = request.Data,
                Label = new List<object>(),
                Data = new List<object>()
            };

            if (string.IsNullOrEmpty(Dfv("HTTP_X_REQUESTED_WITH", ctx.Request.Headers, "")) &&
                Dfv("response", request.Data, "") != "json" &&
                Dfv("op", request.Data, "") != "download" &&
                Dfv("op", request.Data, "") != "delete" &&
                embed == 0 &&
                !Dfv("request", request.Data, "").EndsWith(".json"))
            {
                ctx.Session.SetString("PREVREQUEST", RemoveUrlParam(CreateUrl(ctx.Request.Path, request.Data), new[] { "password" }));
            }

            var hideoptbox = IntValue(BoolValue(Dfv("hideoptbox", request.Data, Dfv("hide_option_box", request.Data, 0))));
            ResetMessage();
            PreSearch(ctx, perform);

            if (perform)
            {
                SetExecuteStart(ctx);
                model.Data = new List<object>();
                model.Label = new List<object>();

                if (Search(ctx) < 1)
                {
                    AddMessage("Nothing Found");
                }
                else
                {
                    ConvertLabelsToObjects(ctx);
                }

                SetExecuteFinish(ctx);
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                return RunDownload(ctx, request, perform);
            }

            Organize(ctx);
            return Display(ctx);
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (HttpContext ctx, [FromServices] IDbConnection dbConnection) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L28-40 → SQL query
            var query = @"
                SELECT cphcm.contractor_placement_id AS contractor_placement_id,
                       cphcm.onb_hr_checklist_type_id AS onb_hr_checklist_type_id,
                       cp.name AS placement,
                       ohct.name AS onb_hr_checklist_type,
                       cphcm.completion_date AS completion_date
                  FROM contractor_placement_hr_checklist_details_map cphcm,
                       contractor_placement cp,
                       onb_hr_checklist_type ohct
                 WHERE cphcm.contractor_placement_id = cp.id
                   AND cphcm.onb_hr_checklist_type_id = ohct.id
                   AND cphcm.is_active = 'Y'
                   AND cphcm.is_customer_mapped = 'Y'
              ORDER BY cphcm.contractor_placement_id DESC";

            var data = await dbConnection.QueryAsync(query);

            // Parent class SearchController.php L350-360 → CSV export logic
            if (data.Any() && boolValue(ctx.Request.Query["createcsv"]))
            {
                var csv = new Csv(ctx.Request.Query["resultfile"], false, "w");
                foreach (var line in data)
                {
                    csv.Write(line);
                }
            }

            return Results.Json(new { status = data.Count() });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
        app.MapGet("/api/v1/contractor_placement_hr_checklist_details/label", (ContractorPlacementHrChecklistDetailsModel model) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L49-53 → set labels
            model.Labels = new Dictionary<string, object[]>
            {
                { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
                { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
                { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", $"{model.Server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
            };

            return Results.Ok(true);
        });

        return app;
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
    // Helper methods
    static bool BoolValue(bool? value) => value ?? false;
    static T Dov<T>(string key, IDictionary<string, T> data, T defaultValue) => data.TryGetValue(key, out var value) ? value : defaultValue;
    static T Dfv<T>(string key, IDictionary<string, T> data, T defaultValue) => data.TryGetValue(key, out var value) ? value : defaultValue;
    static int IntValue(bool value) => value ? 1 : 0;

    // Placeholder for methods that need implementation
    static void PreDownload(HttpContext ctx) { /* Implement pre-download logic */ }
    static void ResetMessage() { /* Implement reset message logic */ }
    static void PreSearch(HttpContext ctx, bool perform) { /* Implement pre-search logic */ }
    static void SetExecuteStart(HttpContext ctx) { /* Implement execute start logic */ }
    static int Search(HttpContext ctx) { /* Implement search logic */ return 0; }
    static void AddMessage(string message) { /* Implement add message logic */ }
    static void ConvertLabelsToObjects(HttpContext ctx) { /* Implement convert labels logic */ }
    static void SetExecuteFinish(HttpContext ctx) { /* Implement execute finish logic */ }
    static object RunDownload(HttpContext ctx, Request request, bool perform) { /* Implement run download logic */ return new object(); }
    static void Organize(HttpContext ctx) { /* Implement organize logic */ }
    static object Display(HttpContext ctx) { /* Implement display logic */ return new object(); }
    static string RemoveUrlParam(string url, string[] paramsToRemove) { /* Implement URL param removal */ return url; }
    static string CreateUrl(string path, IDictionary<string, object> data) { /* Implement URL creation */ return path; }

    // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
    // Helper method to convert string to boolean
    private static bool boolValue(string value)
    {
        return !string.IsNullOrEmpty(value) && (value.Equals("true", StringComparison.OrdinalIgnoreCase) || value.Equals("1"));
    }

    // Csv class placeholder
    public class Csv
    {
        private string _fileName;
        private bool _append;
        private string _mode;

        public Csv(string fileName, bool append, string mode)
        {
            _fileName = fileName;
            _append = append;
            _mode = mode;
        }

        public void Write(object line)
        {
            // Implement CSV writing logic here
        }
    }
}

public sealed record Request(Dictionary<string, object> Data);

public class Model
{
    public Dictionary<string, object> Param { get; set; }
    public List<object> Label { get; set; }
    public List<object> Data { get; set; }
}
