// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package sentinel errors.
//
// Sentinels referenced by the translated controllers' 
// ``errors.Is(err, ...)`` checks. Bodies are placeholder 
// messages; the wiring pass replaces them with the real 
// service-layer error definitions.
package user

import "errors"

var ErrEmailAlreadyInUse = errors.New("email already in use")
var ErrInvalidRequest = errors.New("invalid request")
var ErrNotFound = errors.New("not found")
var ErrUsernameAlreadyInUse = errors.New("username already in use")
