// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/user/UserFacade.kt
//
package userfacade

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/go-chi/chi/v5"
	"net/http"
	"projbb8df72812/internal/platform/auth"
	"projbb8df72812/internal/platform/httpx"
)

// UserFacade.kt L15-28 → signup
func (h *Handler) Signup(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
    var req SignupRequest
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userView, err := h.svc.Signup(r.Context(), req)
    if errors.Is(err, ErrEmailAlreadyInUse) {
        httpx.WriteError(w, http.StatusConflict, "EMAIL_IN_USE", "email already in use")
        return
    }
    if errors.Is(err, ErrUsernameAlreadyInUse) {
        httpx.WriteError(w, http.StatusConflict, "USERNAME_IN_USE", "username already in use")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusCreated, userView)
}

// UserFacade.kt L29-36 → login
// internal/user/handler.go


func (h *Handler) Login(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req LoginRequest
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userView, err := h.svc.Login(r.Context(), req)
    if errors.Is(err, ErrInvalidRequest) {
        httpx.WriteError(w, http.StatusUnauthorized, "INVALID_CREDENTIALS", "invalid username or password")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userView)
}

// UserFacade.kt L37-43 → updateUser


type Service interface {
    UpdateUser(ctx context.Context, request UpdateUserRequest, userSession UserSession) (UserView, error)
}

type userFacadeImpl struct {
    repo Repository
}

func (s *userFacadeImpl) UpdateUser(ctx context.Context, request UpdateUserRequest, userSession UserSession) (UserView, error) {
    user, token := userSession.User, userSession.Token
    if err := s.repo.UpdateUser(ctx, request, user); err != nil {
        return UserView{}, fmt.Errorf("update user: %w", err)
    }
    savedUser, err := s.repo.Save(ctx, user)
    if err != nil {
        return UserView{}, fmt.Errorf("save user: %w", err)
    }
    return savedUser.ToUserView(token), nil
}

// UserFacade.kt L45-51 → updateUser
func (s *userFacadeImpl) UpdateUser(ctx context.Context, request UpdateUserRequest, user *User) error {
    if request.Bio != nil {
        user.Bio = *request.Bio
    }
    if request.Image != nil {
        user.Image = *request.Image
    }
    if request.Password != nil {
        encodedPassword, err := s.passwordService.EncodePassword(*request.Password)
        if err != nil {
            return fmt.Errorf("encode password: %w", err)
        }
        user.EncodedPassword = encodedPassword
    }
    if request.Username != nil {
        if err := s.updateUsername(ctx, user, *request.Username); err != nil {
            return fmt.Errorf("update username: %w", err)
        }
    }
    if request.Email != nil {
        if err := s.updateEmail(ctx, user, *request.Email); err != nil {
            return fmt.Errorf("update email: %w", err)
        }
    }
    return nil
}

// UserFacade.kt L57-63 → follow
func (s *userFacadeImpl) Follow(ctx context.Context, username string, futureFollower User) (ProfileView, error) {
    userToFollow, err := s.repo.FindByUsername(ctx, username)
    if err != nil {
        return ProfileView{}, fmt.Errorf("find user by username: %w", err)
    }

    futureFollower.Follow(userToFollow)

    if err := s.repo.Save(ctx, futureFollower); err != nil {
        return ProfileView{}, fmt.Errorf("save future follower: %w", err)
    }

    return userToFollow.ToFollowedProfileView(), nil
}

// UserFacade.kt L64-70 → unfollow
func (h *Handler) Unfollow(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    followerID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }

    profileView, err := h.svc.Unfollow(r.Context(), username, followerID)
    if errors.Is(err, ErrNotFound) {
        httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "user not found")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profileView)
}

// UserFacade.kt L72-80 → updateUsername
func (s *userFacadeImpl) UpdateUsername(ctx context.Context, user User, newUsername string) error {
    if user.Username == newUsername {
        return nil
    }
    exists, err := s.repo.ExistsByUsername(ctx, newUsername)
    if err != nil {
        return fmt.Errorf("check username existence: %w", err)
    }
    if exists {
        return ErrUsernameAlreadyInUse
    }
    user.Username = newUsername
    return nil
}

// UserFacade.kt L82-90 → updateEmail
func (s *userFacadeImpl) UpdateEmail(ctx context.Context, user User, newEmail string) error {
    if user.Email == newEmail {
        return nil
    }
    exists, err := s.repo.ExistsByEmail(ctx, newEmail)
    if err != nil {
        return fmt.Errorf("check email existence: %w", err)
    }
    if exists {
        return ErrEmailAlreadyInUse
    }
    user.Email = newEmail
    return nil
}

// UserFacade.kt L92-95 → createAuthenticationResponse
func (s *userFacadeImpl) CreateAuthenticationResponse(ctx context.Context, user User) (UserView, error) {
    token, err := s.userTokenProvider.GetToken(ctx, user.ID)
    if err != nil {
        return UserView{}, fmt.Errorf("get token: %w", err)
    }
    return user.ToUserView(token), nil
}
