// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — fallback type aliases.
//
// These ``type X = any`` aliases let the package compile
// when the LLM-emitted code references types that aren't
// declared in this package and weren't resolved via
// cross-package imports. The wiring pass replaces these
// with the real type (struct OR cross-package import)
// — they are intentionally permissive (``any``) so the
// compiler doesn't reject valid call sites that pass
// typed values.
package auth

type Alg = any
type IsoLevel = any
type Keys interface {
	PublicKey(args ...any) (any, error)
}
type Kid = any
type Kty = any
type Scopes = any
type Timeout = any
type UserID = any
