// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/user/UserRepository.kt
//
package user

import (
	"context"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5"
)

// UserRepository.kt L10-22 → findByEmail
func (r *userRepositoryImpl) FindByEmail(ctx context.Context, email string) (*User, error) {
    var user User
    err := r.pool.QueryRow(ctx,
        `SELECT id, username, email, created_at FROM users WHERE email = $1`,
        email,
    ).Scan(&user.ID, &user.Username, &user.Email, &user.CreatedAt)
    if errors.Is(err, pgx.ErrNoRows) {
        return nil, ErrNotFound
    }
    if err != nil {
        return nil, fmt.Errorf("find by email: %w", err)
    }
    return &user, nil
}

// UserRepository.kt L11-22 → existsByEmail
func (r *userRepositoryImpl) ExistsByEmail(ctx context.Context, email string) (bool, error) {
    var exists bool
    err := r.pool.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)`, email).Scan(&exists)
    if err != nil {
        return false, fmt.Errorf("exists by email: %w", err)
    }
    return exists, nil
}

// UserRepository.kt L13-22 → existsByUsername
func (r *userRepositoryImpl) ExistsByUsername(ctx context.Context, username string) (bool, error) {
    var exists bool
    err := r.pool.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)`, username).Scan(&exists)
    if err != nil {
        return false, fmt.Errorf("repository: exists by username %s: %w", username, err)
    }
    return exists, nil
}

// UserRepository.kt L15-22 → findByUsername
func (r *userRepositoryImpl) FindByUsername(ctx context.Context, username string) (*User, error) {
    var user User
    err := r.pool.QueryRow(ctx,
        `SELECT id, username, email, created_at FROM users WHERE username = $1`,
        username,
    ).Scan(&user.ID, &user.Username, &user.Email, &user.CreatedAt)
    if errors.Is(err, pgx.ErrNoRows) {
        return nil, ErrNotFound
    }
    if err != nil {
        return nil, fmt.Errorf("find by username: %w", err)
    }
    return &user, nil
}

// UserRepository.kt L18-22 → findByUsernameOrFail
func (r *userRepositoryImpl) FindByUsernameOrFail(ctx context.Context, username string) (User, error) {
    var user User
    err := r.pool.QueryRow(ctx, `SELECT id, username, email, created_at FROM users WHERE username = $1`, username).Scan(&user.ID, &user.Username, &user.Email, &user.CreatedAt)
    if errors.Is(err, pgx.ErrNoRows) {
        return user, fmt.Errorf("invalid request: username not found")
    }
    if err != nil {
        return user, fmt.Errorf("repository: find by username %s: %w", username, err)
    }
    return user, nil
}

// UserRepository.kt L23-27 → findByEmailOrFail
func (r *userRepositoryImpl) FindByEmailOrFail(ctx context.Context, email string) (User, error) {
    var user User
    err := r.pool.QueryRow(ctx, `SELECT id, email, username FROM users WHERE email = $1`, email).Scan(&user.ID, &user.Email, &user.Username)
    if errors.Is(err, pgx.ErrNoRows) {
        return user, fmt.Errorf("invalid request: email not found")
    }
    if err != nil {
        return user, fmt.Errorf("repository: find by email: %w", err)
    }
    return user, nil
}

// UserRepository.kt L28-29 → findAuthorByArticle
func (r *userRepositoryImpl) FindAuthorByArticle(ctx context.Context, article Article) (*User, error) {
    var user User
    err := r.pool.QueryRow(ctx,
        `SELECT id, username, email, created_at FROM users WHERE id = $1`,
        article.AuthorID,
    ).Scan(&user.ID, &user.Username, &user.Email, &user.CreatedAt)
    if errors.Is(err, pgx.ErrNoRows) {
        return nil, ErrNotFound
    }
    if err != nil {
        return nil, fmt.Errorf("find author by article: %w", err)
    }
    return &user, nil
}
