// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;
using FluentValidation;

namespace Application.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorEntityController.php L22-26 → MapGet
        grp.MapGet("/headline", async ([FromQuery] string text, AppDbContext db) =>
        {
            // L24 → determine headline based on input
            var str = string.IsNullOrEmpty(text) ? "Contractor" : text;
            return Results.Ok(str);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L198-208 → MapGet
        grp.MapGet("/links", async () =>
        {
            // L200-207 → build the links list
            var list = new List<object>();
            list.Add(new {
                Index = 0,
                Title = "Search",
                Url = "{dto.Server}/search/contractor",
                Description = ""
            });
            return Results.Ok(list);
        });

        // ContractorEntityController.php L57-192 → MapPost
        grp.MapPost("/update", async (
            UpdateContractorDto dto,
            IValidator<UpdateContractorDto> validator,
            AppDbContext db) =>
        {
            // L64-64 → handle reset password operation
            if (dto.Op == "reset_pwd")
            {
                var id = dto.Id;
                if (await Contractor.IsActive(id) && await Contractor.IsTsDirect(id))
                {
                    // reset password and send email
                    var email = await Contractor.EmailByID(id);
                    var pwd = Contractor.RandomPassword();
                    await Contractor.UpdatePassword(id, pwd);
                    var site = await GetSite();
                    var signature = await GetSignature();
                    var msg = string.Format(
                        "Hello <b>{0}</b>,<br/><br/>Your Password for the Pyramid Portal has been reset.<br/><br/>Your username is: <b>{1}</b></br><br/>Your temporary password is: <b>{2}</b></br>To access your account using your new temporary password <a href=\"{3}\">click here</a><br/><br/><b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>{4}<br/><br/>{5}",
                        await Contractor.NameByID(id),
                        email,
                        pwd,
                        site,
                        site,
                        signature
                    );
                    await MsgOutQueue(new List<string> { email }, "Password Reset", msg);
                    await Contractor.UpdateLastTs(id, "lastpwdchange", DateTime.Parse("2000-01-01 00:00:00"));
                }
                return Results.Redirect(dto.PrevRequest);
            }

            // L100-100 → handle welcome operation
            if (dto.Op == "welcome")
            {
                var ids = dto.Ids.Distinct().ToList();
                foreach (var id in ids)
                {
                    if (await Contractor.IsActive(id) && await Contractor.IsTsDirect(id) && await Contractor.HasApprover(id))
                    {
                        var email = await Contractor.EmailByID(id);
                        var pwd = Contractor.RandomPassword();
                        var approverId = await Contractor.HasApprover(id);
                        await Contractor.UpdatePassword(id, pwd);
                        var approver = new CustomerContact(approverId);
                        var site = await GetSite();
                        var signature = await GetSignature();
                        var msg = string.Format(
                            "Hello <b>{0}</b>,<br/><br/>Welcome to the Pyramid Consulting Timesheet Portal!<br/><br/>You will use this online tool to submit your timesheets for approval each week. Please remember to submit your timesheets in a timely manner to avoid any problems with your pay.<br/><br/>Your username is: <b>{1}</b></br><br/>Your temporary password is: <b>{2}</b></br></br>Once you log in, the system will ask you to update your password.<br/><br/><a href=\"{3}\">Click Here</a> to access your account and change your password.<br/><br/><b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>{4}<br/><br/>Approver Name : <b>{5}</b><br/><br/>{6}",
                            await Contractor.NameByID(id),
                            email,
                            pwd,
                            site,
                            site,
                            approver.FirstName + " " + approver.LastName,
                            signature
                        );
                        await MsgOutQueue(new List<string> { email }, "Access Credentials for Pyramid Consulting's Timesheet Portal", msg);
                        await Contractor.UpdateLastTs(id, "lastwelcomeemail");
                        await Contractor.UpdateLastTs(id, "lastpwdchange", DateTime.Parse("2000-01-01 00:00:00"));
                    }
                }
                return Results.Redirect(dto.PrevRequest);
            }

            // L148-148 → handle toggle ts_setting operation
            if (dto.Op == "ts_setting")
            {
                var ids = dto.Ids.Distinct().ToList();
                foreach (var id in ids)
                {
                    if (await Contractor.IsActive(id))
                    {
                        await Contractor.ToggleIsTsDirect(id);
                        if (await Contractor.IsTsDirect(id))
                        {
                            var email = await Contractor.EmailByID(id);
                            var pwd = Contractor.RandomPassword();
                            await Contractor.UpdatePassword(id, pwd);
                            var site = await GetSite();
                            var signature = await GetSignature();
                            var msg = string.Format(
                                "Hello <b>{0}</b>,<br/><br/>Welcome to Pyramid Consulting.<br/><br/>Your username is: <b>{1}</b></br><br/>Your temporary password is: {2}</br>To access your account using your new temporary password <a href=\"{3}\">click here</a><br/><br/><b><i>Copy-paste the URL below into your web browser if the link does not work.</i></b><br/><br/>{4}<br/><br/>", 
                                await Contractor.NameByID(id),
                                email,
                                pwd,
                                site,
                                site
                            );
                            await MsgOutQueue(new List<string> { email }, "Access Credentials for Pyramid Consulting's Timesheet Portal", msg);
                            await Contractor.UpdateLastTs(id, "lastwelcomeemail");
                            await Contractor.UpdateLastTs(id, "lastpwdchange", DateTime.Parse("2000-01-01 00:00:00"));
                        }
                    }
                }
                return Results.Redirect(dto.PrevRequest);
            }

            return Results.BadRequest("Invalid operation.");
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        return app;
    }

    // ContractorEntityController.php L57-192 → update
    private async Task<string> GetSite() {
        // Logic to retrieve site
    }

    private async Task<string> GetSignature() {
        // Logic to retrieve signature
    }

    private async Task MsgOutQueue(List<string> to, string subject, string message) {
        // Logic to send email
    }
}

public sealed record UpdateContractorDto(
    string Op,
    int Id,
    List<int> Ids,
    string PrevRequest);
