// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
        app.MapPost("/api/v1/contractor_placement_hr_checklist_details_search/run", async (HttpContext ctx) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            var includeExport = false; // Assuming global variable

            if (BoolValue(Dov("prepare_excel", request.Data, false))) {
                ctx.Items["createcsv"] = "N";
            }
            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false))) {
                ctx.Items["createcsv"] = "N";
                PreDownload(ctx);
            }

            var perform = true;
            var embed = Dfv("embed", request.Data, 0);
            var model = new Model {
                Param = request.Data,
                Label = new List<object>(),
                Data = new List<object>()
            };

            if (string.IsNullOrEmpty(Dfv("HTTP_X_REQUESTED_WITH", ctx.Request.Headers, "")) &&
                Dfv("response", request.Data, "") != "json" &&
                Dfv("op", request.Data, "") != "download" &&
                Dfv("op", request.Data, "") != "delete" &&
                !Dfv("embed", request.Data, 0) &&
                !Dfv("request", request.Data, "").EndsWith(".json"))
            {
                ctx.Session.SetString("PREVREQUEST", RemoveUrlParam(
                    CreateUrl(ctx.Request.Path, request.Data),
                    new[] { "password" }
                ));
            }

            var hideoptbox = Int32.Parse(BoolValue(Dfv("hideoptbox", request.Data, Dfv("hide_option_box", request.Data, 0))).ToString());
            ResetMessage();

            PreSearch(perform);

            if (perform) {
                SetExecuteStart();
                model.Data = new List<object>();
                var label = new List<object>();
                if (Search() < 1) {
                    AddMessage("Nothing Found");
                } else {
                    ConvertLabelsToObjects();
                }
                SetExecuteFinish();
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false))) {
                return RunDownload(request, perform);
            }

            Organize();

            return Display();
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (HttpContext ctx, DbConnection dbConnection) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L28-40 → query
            var query = @"
                SELECT cphcm.contractor_placement_id contractor_placement_id,
                       cphcm.onb_hr_checklist_type_id onb_hr_checklist_type_id,
                       cp.name placement,
                       ohct.name onb_hr_checklist_type,
                       cphcm.completion_date completion_date
                  FROM contractor_placement_hr_checklist_details_map cphcm,
                       contractor_placement cp,
                       onb_hr_checklist_type ohct
                 WHERE cphcm.contractor_placement_id = cp.id
                   AND cphcm.onb_hr_checklist_type_id = ohct.id
                   AND cphcm.is_active = 'Y'
                   AND cphcm.is_customer_mapped = 'Y'
                 ORDER BY cphcm.contractor_placement_id DESC";

            var data = await dbConnection.QueryAsync(query);
            var dataList = data.ToList();

            // SearchController.php L350-360 → CSV export logic
            if (dataList.Any() && boolValue(ctx.Request.Query["createcsv"]))
            {
                var csv = new Csv(ctx.Request.Query["resultfile"], false, "w");
                csv.Write(dataList.First());
                foreach (var line in dataList.Skip(1))
                {
                    csv.Write(line);
                }
            }

            return Results.Json(new { status = dataList.Count });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
        app.MapGet("/api/v1/contractor_placement_hr_checklist_details/label", (ContractorPlacementHrChecklistDetailsModel model) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L49-53 → set labels
            model.Label = new Dictionary<string, object[]>
            {
                { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
                { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
                { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", $"{model.Server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
            };
            return Results.Ok(true);
        });

        return app;
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
    // Helper methods translated from PHP

    private static bool BoolValue(object value) {
        return Convert.ToBoolean(value);
    }

    private static object Dov(string key, Dictionary<string, object> data, object defaultValue) {
        return data.ContainsKey(key) ? data[key] : defaultValue;
    }

    private static object Dfv(string key, Dictionary<string, object> data, object defaultValue) {
        return data.ContainsKey(key) ? data[key] : defaultValue;
    }

    private static string RemoveUrlParam(string url, string[] paramsToRemove) {
        // Implement URL parameter removal logic
        return url;
    }

    private static string CreateUrl(string path, Dictionary<string, object> data) {
        // Implement URL creation logic
        return path;
    }

    private static void ResetMessage() {
        // Implement message reset logic
    }

    private static void PreSearch(bool perform) {
        // Implement pre-search logic
    }

    private static void SetExecuteStart() {
        // Implement execute start logic
    }

    private static int Search() {
        // Implement search logic
        return 0;
    }

    private static void AddMessage(string message) {
        // Implement add message logic
    }

    private static void ConvertLabelsToObjects() {
        // Implement label conversion logic
    }

    private static void SetExecuteFinish() {
        // Implement execute finish logic
    }

    private static void Organize() {
        // Implement organize logic
    }

    private static object Display() {
        // Implement display logic
        return new { };
    }

    private static void PreDownload(HttpContext ctx) {
        // Implement pre-download logic
    }

    private static object RunDownload(Request request, bool perform) {
        // Implement run download logic
        return new { };
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
    // Helper method to convert a string to a boolean
    private static bool boolValue(string value)
    {
        return !string.IsNullOrEmpty(value) && (value.Equals("true", StringComparison.OrdinalIgnoreCase) || value.Equals("1"));
    }

    // Csv class placeholder
    public class Csv
    {
        private string _filePath;
        private bool _someFlag;
        private string _mode;

        public Csv(string filePath, bool someFlag, string mode)
        {
            _filePath = filePath;
            _someFlag = someFlag;
            _mode = mode;
        }

        public void Write(object line)
        {
            // Implement CSV writing logic here
        }
    }
}

public class Request {
    public Dictionary<string, object> Data { get; set; }
}

public class Model {
    public Dictionary<string, object> Param { get; set; }
    public List<object> Label { get; set; }
    public List<object> Data { get; set; }
}
