// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Model/Contractor_placement.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placement.php L195-207 → customerByPlacementID
        app.MapGet("/api/v1/contractor_placement/{contractor_placement_id}/customer", async (int contractor_placement_id, DbConnection dbConnection) =>
        {
            // Model/Contractor_placement.php L199 → convert to int
            contractor_placement_id = Convert.ToInt32(contractor_placement_id);

            // Model/Contractor_placement.php L201-204 → query
            var query = @"SELECT customer_id value FROM contractor_placement WHERE id = @Id";

            // Model/Contractor_placement.php L206 → execute and return
            var command = new SqlCommand(query, (SqlConnection)dbConnection);
            command.Parameters.AddWithValue("@Id", contractor_placement_id);
            var result = await command.ExecuteScalarAsync();
            return Results.Json(Convert.ToInt32(result));
        });

        // Contractor_placement.php L209-221 → endclientByPlacementID
        grp.MapGet("/endclient/{contractorPlacementId}", async (int contractorPlacementId, DbConnection dbConnection) =>
        {
            // Model/Contractor_placement.php L213 → ensure integer
            contractorPlacementId = Convert.ToInt32(contractorPlacementId);

            // Model/Contractor_placement.php L215-219 → query execution
            var query = @"SELECT endclient_id value FROM contractor_placement WHERE id = @Id";
            var command = new SqlCommand(query, (SqlConnection)dbConnection);
            command.Parameters.AddWithValue("@Id", contractorPlacementId);

            var result = await command.ExecuteScalarAsync();
            var endclientId = result != null ? Convert.ToInt32(result) : 0;

            return Results.Json(endclientId);
        });

        // Contractor_placement.php L223-235 → countryByPlacementID
        app.MapGet("/api/v1/contractor-placement/{contractor_placement_id}/country", async (int contractor_placement_id, DbConnection dbConnection) =>
        {
            // Model/Contractor_placement.php L227 → ensure integer
            contractor_placement_id = Convert.ToInt32(contractor_placement_id);

            // Model/Contractor_placement.php L229-234 → query execution
            var query = "SELECT country_id value FROM contractor_placement WHERE id = @contractor_placement_id";
            using var command = dbConnection.CreateCommand();
            command.CommandText = query;
            command.Parameters.AddWithValue("@contractor_placement_id", contractor_placement_id);
            var result = await command.ExecuteScalarAsync();

            return Results.Json(new { value = Convert.ToInt32(result) });
        });

        // Contractor_placement.php L758-773 → updateWorkAddress
        app.MapPut("/api/v1/contractor_placement/{placement_id}/work_address/{worksite_addr_id}", async (int placement_id, int worksite_addr_id, DbConnection dbConnection) =>
        {
            // Model/Contractor_placement.php L762-763 → ensure integers
            placement_id += 0;
            worksite_addr_id += 0;

            // Model/Contractor_placement.php L765-772 → update if worksite_addr_id > 0
            if (worksite_addr_id > 0)
            {
                var query = "UPDATE profile SET worksite_addr_id = @worksite_addr_id WHERE contractor_placement_id = @placement_id";
                using var command = dbConnection.CreateCommand();
                command.CommandText = query;
                command.Parameters.Add(new SqlParameter("@worksite_addr_id", worksite_addr_id));
                command.Parameters.Add(new SqlParameter("@placement_id", placement_id));
                await command.ExecuteNonQueryAsync();
            }

            return Results.NoContent();
        });

        // Contractor_placement.php L337-389 → adjustPlacementStartDate
        app.MapPost("/api/v1/contractor/placement/adjust-start-date", async (int placement_id, string start_date, ContractorPlacementRepository repo) =>
        {
            // Model/Contractor_placement.php L340-341 → validate inputs
            if (placement_id == 0 || start_date == "2001-01-01")
                return Results.BadRequest();

            // Model/Contractor_placement.php L344 → load placement
            var plcObj = await repo.GetPlacementAsync(placement_id);
            if (plcObj == null || !plcObj.IsPopulated())
                return Results.NotFound();

            // Model/Contractor_placement.php L347-349 → update start date
            plcObj.StartDate = start_date;
            if (plcObj.HasChanged())
            {
                await repo.SaveAsync(plcObj);

                // Model/Contractor_placement.php L351 → delete invalid entries
                await ContractorPlacementOverdueStatusMap.DeleteInvalidEntriesAsync(plcObj.Id);

                // Model/Contractor_placement.php L352-369 → update profiles
                foreach (var profile in plcObj.AllProfiles())
                {
                    if (profile.ValidFrom <= profile.ValidTo)
                    {
                        plcObj.StartDate = DateSanitize(plcObj.StartDate);
                        if (plcObj.StartDate < profile.ValidFrom)
                        {
                            profile.ValidFrom = plcObj.StartDate;
                            await profile.SaveAsync();
                            await Profile.VoidAfterProfileAsync(plcObj.Id, profile.ValidFrom);
                            break;
                        }
                        if (plcObj.StartDate >= profile.ValidFrom && plcObj.StartDate <= profile.ValidTo)
                        {
                            profile.ValidFrom = plcObj.StartDate;
                            await profile.SaveAsync();
                            await Profile.VoidAfterProfileAsync(plcObj.Id, profile.ValidFrom);
                            break;
                        }
                        await profile.AdjustBurdenNewAsync(plcObj.IsPassthru);
                        await profile.SaveAsync();
                    }
                }

                // Model/Contractor_placement.php L373-385 → H1B Employees Credit Exception
                var visaTypes = GetVisaTypes();
                var demographicId = await ContractorPlacement.CheckDemographicReverseMapAsync(placement_id);
                var demographicObj = new OnbDemographic(demographicId);
                var visaType = demographicObj.GetVisaType();
                var cutoffDate = GetCutoffDate();

                if (visaTypes.Contains(visaType))
                {
                    foreach (var profile in plcObj.AllProfiles())
                    {
                        if (profile.ValidFrom >= cutoffDate)
                        {
                            await Profile.UpdateH1bEmployeesApplyPctAsync(profile.Id);
                        }
                    }
                }
            }

            return Results.Ok();
        });

        // Contractor_placement.php L431-502 → matchCandidateToPlacement
        app.MapGet("/api/v1/placement/match/{contractorPlacementId}/{jobreqId?}", async (int contractorPlacementId, int? jobreqId, AppDbContext db) =>
        {
            // Model/Contractor_placement.php L435-440 → get placement
            var cp = await db.ContractorPlacements.FindAsync(contractorPlacementId);
            if (cp == null || !cp.IsPopulated())
            {
                Console.WriteLine("  Placement not populated");
                return Results.NotFound();
            }

            // Model/Contractor_placement.php L442-447 → get contractor
            var contractor = await db.Contractors.FindAsync(cp.ContractorId);
            if (contractor == null || !contractor.IsPopulated() || contractor.Id < 2)
            {
                Console.WriteLine("  Contractor not populated");
                return Results.NotFound();
            }

            // Model/Contractor_placement.php L450-459 → get job
            jobreqId ??= cp.JobreqId;
            if (jobreqId < 2)
            {
                Console.WriteLine("  Job not populated");
                return Results.NotFound();
            }

            // Model/Contractor_placement.php L462-479 → get candidates and match email
            var candidates = await db.CandidateActivities
                .Where(ca => ca.JobreqId == jobreqId)
                .Select(ca => ca.CandidateId)
                .Distinct()
                .ToListAsync();

            foreach (var cid in candidates)
            {
                var candidate = await db.Candidates.FindAsync(cid);
                if (candidate != null && candidate.Email == contractor.Email)
                {
                    return Results.Json(candidate);
                }
            }

            // Model/Contractor_placement.php L483-495 → match name
            Console.WriteLine($"  {contractor.Firstname} {contractor.Lastname}");
            foreach (var cid in candidates)
            {
                var candidate = await db.Candidates.FindAsync(cid);
                if (candidate != null)
                {
                    Console.WriteLine($"  * {candidate.Firstname} {candidate.Lastname}");
                    if (contractor.Firstname == candidate.Firstname && contractor.Lastname == candidate.Lastname)
                    {
                        return Results.Json(candidate);
                    }
                }
            }

            return Results.NotFound();
        });

        // Contractor_placement.php L504-575 → bestMatch
        app.MapGet("/api/v1/contractor/bestmatch", async (string custids, string contractorname, string tsweek, [FromServices] IDbConnection dbConnection) =>
        {
            var list = new List<Dictionary<string, object>>();
            var custIdsList = QuoteAndTransform(custids);
            var contractorsList = QuoteAndTransform(ContractorBestMatch(contractorname, dbConnection));

            if (custIdsList.Count < 1 || contractorsList.Count < 1)
                return Results.Json(list);

            var query = $"SELECT cp.id, cp.start_date, cp.deactivation_date, cp.is_active, c.id AS contractor_id, c.firstname, c.mi, c.lastname, c.is_active AS is_active_contractor FROM contractor_placement cp, contractor c WHERE cp.contractor_id = c.id AND cp.customer_id IN ({string.Join(",", custIdsList)}) AND c.id IN ({string.Join(",", contractorsList)})";
            list = await DbGetRows(query, dbConnection);

            if (list.Count < 1)
            {
                query = $"SELECT cp.id, cp.start_date, cp.deactivation_date, cp.is_active, c.id AS contractor_id, c.firstname, c.mi, c.lastname, c.is_active AS is_active_contractor FROM contractor_placement cp, contractor c WHERE cp.contractor_id = c.id AND c.id IN ({string.Join(",", contractorsList)})";
                list = await DbGetRows(query, dbConnection);
            }

            if (list.Count > 1)
            {
                list = list.Aggregate(new List<Dictionary<string, object>>(), (carry, entry) =>
                {
                    var tssecs = DateTimeOffset.Parse(tsweek).ToUnixTimeSeconds();
                    var maxdeviation = 7 * 86400;
                    if (!IsPerm(entry["id"]))
                    {
                        if (tssecs - DateTimeOffset.Parse(entry["start_date"].ToString()).ToUnixTimeSeconds() >= -1 * maxdeviation &&
                            (entry["deactivation_date"].ToString() == "2000-01-01 00:00:00" || tssecs - DateTimeOffset.Parse(entry["deactivation_date"].ToString()).ToUnixTimeSeconds() <= maxdeviation))
                        {
                            carry.Add(entry);
                        }
                    }
                    return carry;
                });
            }

            return Results.Json(list);
        });

        return app;
    }

    // Contractor_placement.php L337-389 → adjustPlacementStartDate
    // Helper methods and configurations
    private static List<string> GetVisaTypes() =>
        GetConfig("100 percentage credit work authorization list", "H1B,CPT,OPT EAD,TN", "App").Split(',').Select(v => v.Trim()).ToList();

    private static DateTime GetCutoffDate() =>
        DateTime.Parse(GetConfig("100 percentage credit cutoff date", "2023-10-06", "App"));

    private static string DateSanitize(string date) =>
        DateTime.Parse(date).ToString("yyyy-MM-dd");

    // Contractor_placement.php L504-575 → bestMatch
    private static List<string> QuoteAndTransform(string input)
    {
        // Transform input into a list of quoted strings
        return input.Split(',').Select(s => $"'{s.Trim()}'").ToList();
    }

    private static List<string> ContractorBestMatch(string contractorname, IDbConnection dbConnection)
    {
        // Simulate the Contractor::bestMatch logic
        var list = new List<string>();
        // Add logic to interact with the database and fetch contractor IDs
        return list;
    }

    private static async Task<List<Dictionary<string, object>>> DbGetRows(string query, IDbConnection dbConnection)
    {
        // Execute the query and return the result as a list of dictionaries
        return new List<Dictionary<string, object>>();
    }

    private static bool IsPerm(object id)
    {
        // Simulate the Contractor_placement::isPerm logic
        return false;
    }
}


