// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorSearchController.php L23-26 → run
        app.MapPost("/api/v1/contractor/search", async (HttpContext ctx, [FromServices] ISearchService searchService) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<SearchRequest>();
            if (request == null) return Results.BadRequest(new { error = "Invalid request" });

            var result = await searchService.RunAsync(request, true);
            return Results.Json(result);
        });

        return app;
    }

    // ContractorSearchController.php L23-26 → run
    public interface ISearchService
    {
        Task<object> RunAsync(SearchRequest request, bool perform);
    }

    public class SearchService : ISearchService
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISession _session;
        private readonly ILogger<SearchService> _logger;

        public SearchService(IHttpContextAccessor httpContextAccessor, ILogger<SearchService> logger)
        {
            _httpContextAccessor = httpContextAccessor;
            _logger = logger;
            _session = _httpContextAccessor.HttpContext.Session;
        }

        public async Task<object> RunAsync(SearchRequest request, bool perform)
        {
            bool includeExport = false; // Assume this is set elsewhere

            if (BoolValue(Dov("prepare_excel", request.Data, false)))
            {
                // Handle prepare_excel logic
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                // Handle download_xlsx logic
                PreDownload();
            }

            // Perform search logic
            if (perform)
            {
                SetExecuteStart();
                var data = new List<object>();
                var labels = new List<object>();

                if (Search() < 1)
                {
                    AddMessage("Nothing Found");
                }
                else
                {
                    ConvertLabelsToObjects();
                }

                SetExecuteFinish();
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                return RunDownload(request, perform);
            }

            Organize();

            return Display();
        }

        private bool BoolValue(object value) => Convert.ToBoolean(value);
        private object Dov(string key, IDictionary<string, object> data, object defaultValue) => data.ContainsKey(key) ? data[key] : defaultValue;
        private void PreDownload() { /* Implement logic */ }
        private void SetExecuteStart() { /* Implement logic */ }
        private int Search() { return 0; /* Implement logic */ }
        private void AddMessage(string message) { /* Implement logic */ }
        private void ConvertLabelsToObjects() { /* Implement logic */ }
        private void SetExecuteFinish() { /* Implement logic */ }
        private object RunDownload(SearchRequest request, bool perform) { return new object(); /* Implement logic */ }
        private void Organize() { /* Implement logic */ }
        private object Display() { return new object(); /* Implement logic */ }
    }
}

public sealed record SearchRequest(Dictionary<string, object> Data);
