// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Model/Contractor_placement.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placement.php L84-98 → isPerm
        // Model/Contractor_placement.php L84-98 → MapGet
        app.MapGet("/api/v1/contractor-placement/{id}/is-perm", async (int id, AppDbContext db) =>
        {
            var count = await db.Set<Profile>()
                .Where(p => p.ContractorPlacementId == id && p.EmploymentTypeId == 1)
                .CountAsync();
            return Results.Ok(new { isPerm = count > 0 });
        });

        // Contractor_placement.php L99-113 → isTsDirect
        // Model/Contractor_placement.php L99-113 → MapGet
        app.MapGet("/api/v1/contractorplacement/{contractor_placement_id}/isTsDirect", async (int contractor_placement_id, AppDbContext db) =>
        {
            // L103 → ensure contractor_placement_id is an integer
            contractor_placement_id = Convert.ToInt32(contractor_placement_id);

            // L105-110 → parameterized query
            var query = @"SELECT COUNT(*) FROM contractor_placement WHERE id = @Id AND is_ts_direct = 'Y'";
            var count = await db.Database.ExecuteSqlRawAsync(query, new SqlParameter("@Id", contractor_placement_id));

            // L112 → return boolean based on count
            return Results.Ok(count > 0);
        });

        // Contractor_placement.php L115-131 → inFurlough
        // Model/Contractor_placement.php L115-131 → MapGet
        grp.MapGet("/infurlough/{contractor_placement_id}/{date}", async (int contractor_placement_id, string date, AppDbContext db) =>
        {
            var query = @"SELECT COUNT(*) FROM contractor_placement_furlough 
                          WHERE contractor_placement_id = @ContractorPlacementId 
                          AND is_deleted = 'N' 
                          AND @Date BETWEEN effective_from AND effective_to";

            var count = await db.Database.ExecuteSqlRawAsync(query, 
                new SqlParameter("@ContractorPlacementId", contractor_placement_id),
                new SqlParameter("@Date", date));

            return Results.Ok(new { inFurlough = count > 0 });
        });

        // Contractor_placement.php L133-145 → contractorByPlacementID
        // Model/Contractor_placement.php L133-145 → MapGet
        app.MapGet("/api/v1/contractor/placement/{contractor_placement_id}", async (int contractorPlacementId, AppDbContext db) =>
        {
            // L137 → convert to int
            contractorPlacementId = Convert.ToInt32(contractorPlacementId);

            // L139-144 → query contractor_id
            var query = "SELECT contractor_id FROM contractor_placement WHERE id = @Id";
            var contractorId = await db.Database.GetDbConnection().QueryFirstOrDefaultAsync<int?>(query, new { Id = contractorPlacementId });

            // Return as integer
            return Results.Ok(contractorId ?? 0);
        });

        // Contractor_placement.php L147-166 → placementByCenteneContractorEmail
        // Model/Contractor_placement.php L147-166 → MapGet
        grp.MapGet("/placementByCenteneContractorEmail", async (string email, AppDbContext db) =>
        {
            // L150 → trim and validate email
            email = email.Trim();
            if (string.IsNullOrEmpty(email))
            {
                return Results.BadRequest(new { error = "Email is required." });
            }

            // L155-163 → query for placement
            var query = @"
                SELECT cp.id
                FROM contractor_placement cp
                JOIN contractor c ON cp.contractor_id = c.id
                WHERE cp.contractor_id != 1
                AND c.email = @Email
                AND cp.customer_id = 1033
                ORDER BY cp.id DESC
                LIMIT 1";

            var placementId = await db.Database.ExecuteSqlInterpolatedAsync($"{query}", new SqlParameter("@Email", email));
            if (placementId == null)
            {
                return Results.NotFound();
            }

            return Results.Ok(new { value = placementId });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L168-193 → placementByContractorID
        // Model/Contractor_placement.php L168-193 → MapGet
        grp.MapGet("/placement/{contractor_id}", async (int contractor_id, [FromQuery] bool applyExclude, [FromQuery] string? is_active, AppDbContext db) =>
        {
            var pyramidCustomers = new List<int> { 591 };
            var excludeOmsCustomers = new List<int>(); // Assume this is populated from a config or service
            var excludeOmsCustomersFiltered = excludeOmsCustomers.Except(pyramidCustomers);

            var query = db.Set<ContractorPlacement>().Where(cp => cp.ContractorId == contractor_id && cp.ContractorId != 1);

            if (!string.IsNullOrEmpty(is_active))
            {
                query = query.Where(cp => cp.IsActive == is_active);
            }

            if (applyExclude)
            {
                query = query.Where(cp => !excludeOmsCustomersFiltered.Contains(cp.CustomerId));
            }

            query = query.Where(cp => !EF.Functions.Like(cp.Name, "PERM %"))
                         .OrderByDescending(cp => cp.Id)
                         .Take(1);

            var result = await query.Select(cp => cp.Id).FirstOrDefaultAsync();
            return Results.Ok(result);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L195-207 → customerByPlacementID
        // Model/Contractor_placement.php L195-207 → MapGet
        app.MapGet("/api/v1/contractor-placement/{contractor_placement_id}/customer", async (int contractor_placement_id, AppDbContext db) =>
        {
            var query = "SELECT customer_id FROM contractor_placement WHERE id = @Id";
            var customerId = await db.Database.GetDbConnection().ExecuteScalarAsync<int?>(query, new { Id = contractor_placement_id });
            if (customerId == null)
            {
                return Results.NotFound();
            }
            return Results.Ok(new { value = customerId });
        });

        // Contractor_placement.php L209-221 → endclientByPlacementID
        // Model/Contractor_placement.php L209-221 → MapGet
        grp.MapGet("/endclient/{contractor_placement_id}", async (int contractorPlacementId, AppDbContext db) =>
        {
            var query = @"SELECT endclient_id FROM contractor_placement WHERE id = @Id";
            var endclientId = await db.Database.ExecuteSqlRawAsync(query, new SqlParameter("@Id", contractorPlacementId));
            return Results.Ok(new { value = endclientId });
        });

        // Contractor_placement.php L223-235 → countryByPlacementID
        // Model/Contractor_placement.php L223-235 → MapGet
        grp.MapGet("/placement/{contractor_placement_id}/country", async (int contractor_placement_id, AppDbContext db) =>
        {
            var query = "SELECT country_id FROM contractor_placement WHERE id = @Id";
            var countryId = await db.Database.ExecuteSqlRawAsync(query, new SqlParameter("@Id", contractor_placement_id));
            return Results.Ok(countryId);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L337-389 → adjustPlacementStartDate
        // Model/Contractor_placement.php L337-389 → MapPut
        grp.MapPut("/adjustPlacementStartDate/{placement_id:int}", async (
            int placement_id,
            [FromQuery] string start_date,
            AppDbContext db) =>
        {
            // L340-342 → validate input
            if (placement_id == 0 || start_date == "2001-01-01")
            {
                return Results.BadRequest("Invalid placement_id or start_date");
            }

            // L344 → load placement object
            var plcObj = await db.ContractorPlacements.FindAsync(placement_id);
            if (plcObj == null)
            {
                return Results.NotFound();
            }

            // L346 → check if populated
            if (plcObj.IsPopulated())
            {
                plcObj.StartDate = DateTime.Parse(start_date);

                // L348 → check if changed
                if (plcObj.HasChanged())
                {
                    // L349 → save changes
                    db.ContractorPlacements.Update(plcObj);
                    await db.SaveChangesAsync();

                    // L351 → delete invalid entries
                    ContractorPlacementOverdueStatusMap.DeleteInvalidEntries(plcObj.Id);

                    // L352-369 → adjust profiles
                    foreach (var profile in plcObj.AllProfiles())
                    {
                        if (profile.ValidFrom <= profile.ValidTo)
                        {
                            plcObj.StartDate = DateSanitize(plcObj.StartDate);
                            if (plcObj.StartDate < profile.ValidFrom)
                            {
                                profile.ValidFrom = plcObj.StartDate;
                                db.Profiles.Update(profile);
                                await db.SaveChangesAsync();
                                Profile.VoidAfterProfile(plcObj.Id, profile.ValidFrom);
                                break;
                            }
                            if (plcObj.StartDate >= profile.ValidFrom && plcObj.StartDate <= profile.ValidTo)
                            {
                                profile.ValidFrom = plcObj.StartDate;
                                db.Profiles.Update(profile);
                                await db.SaveChangesAsync();
                                Profile.VoidAfterProfile(plcObj.Id, profile.ValidFrom);
                                break;
                            }
                            profile.AdjustBurdenNew(plcObj.IsPassthru);
                            db.Profiles.Update(profile);
                            await db.SaveChangesAsync();
                        }
                    }

                    // L373-385 → handle visa types
                    var visaTypes = GetConfig("100 percentage credit work authorization list", "H1B,CPT,OPT EAD,TN").Split(',');
                    var demographicId = ContractorPlacement.CheckDemographicReverseMap(placement_id);
                    var demographicObj = new OnbDemographic(demographicId);
                    var visaType = demographicObj.GetVisaType();
                    var cutoffDate = DateToDate(GetConfig("100 percentage credit cutoff date", "2023-10-06"));

                    if (visaTypes.Contains(visaType))
                    {
                        foreach (var profile in plcObj.AllProfiles())
                        {
                            if (profile.ValidFrom >= cutoffDate)
                            {
                                Profile.UpdateH1bEmployeesApplyPct(profile.Id);
                            }
                        }
                    }
                }
            }
            return Results.Ok();
        });

        // Contractor_placement.php L392-429 → uniquePlacementsByCandidateIDs
        // Model/Contractor_placement.php L392-429 → MapGet
        grp.MapGet("/unique-placements", async ([FromQuery] string candidateIds, SqlConnection dbConnection) =>
        {
            // L396 → trim and split candidate IDs
            var candidateIdList = candidateIds.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(id => id.Trim()).ToList();
            if (candidateIdList.Count < 1)
            {
                return Results.Ok(new List<object>());
            }

            // L401-427 → SQL query with parameterization
            var query = @"
                SELECT DISTINCT can.id, can.contractor_placement_id AS value FROM
                (
                    SELECT DISTINCT co.candidate_id AS id,
                                   cp.id AS contractor_placement_id
                      FROM contractor_placement cp
                      JOIN contractor_placement_oms_map cpom ON cpom.contractor_placement_id = cp.id
                      JOIN adhoc_oms_workorder aow ON aow.WorkOrderID = cpom.oms_id
                      JOIN candidate_onboarding co ON aow.ConsultantDemographicID = co.ConsultantDemographicID
                     WHERE cp.start_date <= cp.end_date
                       AND co.candidate_id IN @CandidateIds
                     UNION
                    SELECT DISTINCT od.candidate_id AS id,
                                   cpdm.contractor_placement_id AS contractor_placement_id
                      FROM contractor_placement_demographic_map cpdm
                      JOIN onb_demographic od ON od.id = cpdm.demographic_id
                      JOIN contractor_placement cp ON cpdm.contractor_placement_id = cp.id
                     WHERE cp.start_date <= cp.end_date
                       AND od.candidate_id IN @CandidateIds
                     UNION
                    SELECT DISTINCT ccm.candidate_id AS id,
                                   cp.id AS contractor_placement_id
                      FROM candidate_contractor_map ccm
                      JOIN contractor_placement cp ON ccm.contractor_id = cp.contractor_id
                     WHERE ccm.candidate_id IN @CandidateIds
                ) can
            ";

            var results = await dbConnection.QueryAsync(query, new { CandidateIds = candidateIdList });
            return Results.Ok(results);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L504-575 → bestMatch
        // Model/Contractor_placement.php L504-575 → MapGet
        app.MapGet("/api/v1/contractor-placement/best-match", async (
            [FromQuery] string custids,
            [FromQuery] string contractorname,
            [FromQuery] string tsweek,
            AppDbContext db) =>
        {
            var list = new List<dynamic>();
            var custIdsArray = QuoteAndTransform(custids);
            var contractorsArray = QuoteAndTransform(await Contractor.BestMatchAsync(contractorname, db));

            if (custIdsArray.Count < 1 || contractorsArray.Count < 1)
            {
                return Results.Ok(list);
            }

            var query = @"SELECT cp.id, cp.start_date, cp.deactivation_date, cp.is_active, c.id as contractor_id, 
                          c.firstname, c.mi, c.lastname, c.is_active as is_active_contractor
                          FROM contractor_placement cp
                          JOIN contractor c ON cp.contractor_id = c.id
                          WHERE cp.customer_id IN @CustIds AND c.id IN @Contractors";

            list = (await db.Database.GetDbConnection().QueryAsync(query, new { CustIds = custIdsArray, Contractors = contractorsArray })).ToList();

            if (list.Count < 1)
            {
                query = @"SELECT cp.id, cp.start_date, cp.deactivation_date, cp.is_active, c.id as contractor_id, 
                          c.firstname, c.mi, c.lastname, c.is_active as is_active_contractor
                          FROM contractor_placement cp
                          JOIN contractor c ON cp.contractor_id = c.id
                          WHERE c.id IN @Contractors";

                list = (await db.Database.GetDbConnection().QueryAsync(query, new { Contractors = contractorsArray })).ToList();
            }

            if (list.Count > 1)
            {
                var tssecs = DateTimeOffset.Parse(tsweek).ToUnixTimeSeconds();
                var maxdeviation = 7 * 86400;
                list = list.Where(entry =>
                {
                    var startDate = DateTimeOffset.Parse(entry.start_date).ToUnixTimeSeconds();
                    var deactivationDate = entry.deactivation_date != "2000-01-01 00:00:00" ? DateTimeOffset.Parse(entry.deactivation_date).ToUnixTimeSeconds() : (long?)null;

                    if (ContractorPlacement.IsPerm(entry.id))
                    {
                        return false;
                    }
                    else if (tssecs - startDate < -1 * maxdeviation)
                    {
                        return false;
                    }
                    else if (deactivationDate.HasValue && tssecs - deactivationDate.Value > maxdeviation)
                    {
                        return false;
                    }
                    return true;
                }).ToList();
            }

            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L577-588 → getPlacementIDsByCustomer
        // Model/Contractor_placement.php L577-588 → MapGet
        app.MapGet("/api/v1/contractor_placement/{customer_id}/ids", async (string customer_id, AppDbContext db) =>
        {
            var ids = await db.Set<ContractorPlacement>()
                .Where(cp => cp.CustomerId == customer_id && cp.IsPending == "N")
                .Select(cp => cp.Id)
                .ToListAsync();

            return Results.Ok(new { ids });
        });

        // Contractor_placement.php L590-602 → getJobClassificationName
        // Model/Contractor_placement.php L590-602 → MapGet
        app.MapGet("/api/v1/contractor-placement/{id}/job-classification", async (string id, SqlConnection dbConnection) =>
        {
            const string query = @"
                SELECT jct.name
                FROM contractor_placement cp
                JOIN jobreq j ON cp.jobreq_id = j.id
                JOIN jobreq_classification_type jct ON j.jobreq_classification_type_id = jct.id
                WHERE cp.id = @ContractorPlacementId";

            using var command = new SqlCommand(query, dbConnection);
            command.Parameters.AddWithValue("@ContractorPlacementId", id);

            var result = await command.ExecuteScalarAsync();
            return result != null ? Results.Ok(new { value = result }) : Results.NotFound();
        });

        // Contractor_placement.php L604-617 → getJobPriorityType
        // Model/Contractor_placement.php L604-617 → MapGet
        app.MapGet("/api/v1/contractor_placement/{contractor_placement_id}/job_priority_type", async (string contractor_placement_id, SqlConnection dbConnection) =>
        {
            var query = @"
                SELECT jpt.name AS value
                FROM contractor_placement cp
                JOIN jobreq j ON cp.jobreq_id = j.id
                JOIN jobpriority jp ON jp.jobreq_id = j.id
                JOIN jobpriority_type jpt ON jp.override_priority_id = jpt.id
                WHERE cp.id = @ContractorPlacementId
            ";

            using var command = new SqlCommand(query, dbConnection);
            command.Parameters.AddWithValue("@ContractorPlacementId", contractor_placement_id);

            var result = await command.ExecuteScalarAsync<string>();
            return result != null ? Results.Ok(new { value = result }) : Results.NotFound();
        });

        // Contractor_placement.php L619-631 → getJobPositionType
        // Model/Contractor_placement.php L619-631 → MapGet
        app.MapGet("/api/v1/contractor-placement/{contractor_placement_id}/job-position-type", async (int contractor_placement_id, AppDbContext db) =>
        {
            var query = @"
                SELECT pt.name
                FROM contractor_placement cp
                JOIN jobreq j ON cp.jobreq_id = j.id
                JOIN position_type pt ON pt.id = j.position_type_id
                WHERE cp.id = @ContractorPlacementId
            ";

            var value = await db.Database.ExecuteSqlRawAsync(query, new SqlParameter("@ContractorPlacementId", contractor_placement_id));

            if (value == null)
            {
                return Results.NotFound();
            }

            return Results.Ok(new { value });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L688-695 → jobreqID
        // Model/Contractor_placement.php L688-695 → MapGet
        grp.MapGet("/jobreq/{placement_id}", async (int placement_id, AppDbContext db) =>
        {
            var query = "SELECT jobreq_id FROM contractor_placement WHERE id = @PlacementId";
            var jobreqId = await db.Database.ExecuteSqlRawAsync(query, new SqlParameter("@PlacementId", placement_id));
            return jobreqId != null ? Results.Ok(new { value = jobreqId }) : Results.NotFound();
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement.php L717-731 → getDemographicsID
        // Model/Contractor_placement.php L717-731 → MapGet
        app.MapGet("/api/v1/contractor_placement/{placement_id}/demographics", async (int placement_id, SqlConnection dbConnection) =>
        {
            // L721 → sanitize input
            var sanitizedPlacementId = placement_id;

            // L723-728 → SQL query with parameterization
            var query = @"
                SELECT aow.ConsultantDemographicID AS value
                FROM contractor_placement_oms_map cpom
                JOIN adhoc_oms_workorder aow ON aow.WorkOrderID = cpom.oms_id
                WHERE cpom.contractor_placement_id = @PlacementId
            ";

            // Execute query
            using var command = new SqlCommand(query, dbConnection);
            command.Parameters.AddWithValue("@PlacementId", sanitizedPlacementId);
            var result = await command.ExecuteScalarAsync();

            // Return result
            if (result != null)
            {
                return Results.Ok(new { value = result });
            }
            return Results.NotFound();
        });

        // Contractor_placement.php L733-744 → percentageLookupList
        // Model/Contractor_placement.php L733-744 → MapGet
        grp.MapGet("/percentage-lookup", (double increment, double min, double max) =>
        {
            var list = PercentageLookupList(increment, min, max);
            return Results.Json(list);
        });

        // Contractor_placement.php L746-756 → updateInsertWorksiteAddress
        // Model/Contractor_placement.php L746-756 → MapPost
        grp.MapPost("/worksite-address", async (
            WorksiteAddressRequest req,
            AppDbContext db) =>
        {
            var stateName = States.Translate(req.StateName.Trim());
            if (string.IsNullOrEmpty(stateName))
            {
                stateName = req.StateName.Trim();
            }

            var workaddr = await Address.DoExists(
                req.StreetAddress.Trim(),
                "",
                req.City.Trim(),
                stateName,
                req.Zip.Trim(),
                req.Country.Trim(),
                req.CustomerId,
                "W",
                db);

            return Results.Ok(workaddr);
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        // Contractor_placement.php L758-773 → updateWorkAddress
        // Model/Contractor_placement.php L758-773 → MapPut
        grp.MapPut("/work-address/{placement_id}", async (int placement_id, int worksite_addr_id, AppDbContext db) =>
        {
            // L762-763 → Coerce to int
            placement_id += 0;
            worksite_addr_id += 0;

            // L765 → Check if worksite_addr_id is greater than 0
            if (worksite_addr_id > 0)
            {
                // L767-769 → Update query
                var query = "UPDATE profile SET worksite_addr_id = @worksite_addr_id WHERE contractor_placement_id = @placement_id";
                var parameters = new { worksite_addr_id, placement_id };
                await db.Database.ExecuteSqlRawAsync(query, parameters);
            }
            return Results.NoContent();
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        // Contractor_placement.php L431-502 → matchCandidateToPlacement
        // Model/Contractor_placement.php L431-502 → MapGet
        grp.MapGet("/matchCandidateToPlacement/{contractorPlacementId}/{jobreqId?}", async (
            int contractorPlacementId,
            int? jobreqId,
            AppDbContext db) =>
        {
            // L436-440: Get placement
            var cp = await db.ContractorPlacements.FindAsync(contractorPlacementId);
            if (cp == null)
            {
                return Results.NotFound("Placement not populated");
            }

            // L443-447: Get contractor
            var contractor = await db.Contractors.FindAsync(cp.ContractorId);
            if (contractor == null || contractor.Id < 2)
            {
                return Results.NotFound("Contractor not populated");
            }

            // L450-459: Get job
            var jobId = jobreqId ?? cp.JobreqId;
            if (jobId < 2)
            {
                return Results.NotFound("Job not populated");
            }

            // L462-479: Match email
            var candidateIds = await db.CandidateActivities
                .Where(ca => ca.JobreqId == jobId)
                .Select(ca => ca.CandidateId)
                .Distinct()
                .ToListAsync();

            foreach (var cid in candidateIds)
            {
                var candidate = await db.Candidates.FindAsync(cid);
                if (candidate != null && candidate.Email == contractor.Email)
                {
                    return Results.Ok(candidate);
                }
            }

            // L484-495: Match name
            foreach (var cid in candidateIds)
            {
                var candidate = await db.Candidates.FindAsync(cid);
                if (candidate != null && candidate.Firstname == contractor.Firstname && candidate.Lastname == contractor.Lastname)
                {
                    return Results.Ok(candidate);
                }
            }

            return Results.NotFound();
        });

        // Contractor_placement.php L697-715 → changeJobId
        // Model/Contractor_placement.php L697-715 → MapPut
        grp.MapPut("/change-job-id", async (
            [FromQuery] int old_id,
            [FromQuery] int new_id,
            AppDbContext db) =>
        {
            if (old_id == 0 || new_id == 0)
            {
                return Results.BadRequest("Old ID and New ID must be provided.");
            }

            var updated = 0;
            var placements = await db.ContractorPlacements
                .Where(p => p.JobreqId == old_id && p.IsActive == "Y")
                .ToListAsync();

            foreach (var plc in placements)
            {
                plc.JobreqId = new_id;
                updated++;
            }

            await db.SaveChangesAsync();
            return Results.Ok(new { updated });
        });

        return app;
    }

    // Contractor_placement.php L337-389 → adjustPlacementStartDate
    public static DateTime DateSanitize(DateTime date) {
        // Implement date sanitization logic
        return date;
    }

    public static DateTime DateToDate(string dateString) {
        return DateTime.Parse(dateString);
    }

    public static string[] GetConfig(string key, string defaultValue) {
        // Implement configuration retrieval logic
        return defaultValue.Split(',');
    }

    public class ContractorPlacementOverdueStatusMap {
        public static void DeleteInvalidEntries(int placementId) {
            // Implement deletion logic
        }
    }

    public class Profile {
        public static void VoidAfterProfile(int placementId, DateTime validFrom) {
            // Implement void logic
        }

        public static void UpdateH1bEmployeesApplyPct(int profileId) {
            // Implement update logic
        }
    }

    // Contractor_placement.php L504-575 → bestMatch
    public static List<string> QuoteAndTransform(string input)
    {
        return input.Split(',').Select(x => $"'{x.Trim()}'").ToList();
    }

    public static async Task<List<string>> BestMatchAsync(string contractorname, AppDbContext db)
    {
        // Simulate the Contractor::bestMatch PHP method
        // This should be replaced with actual logic or a database call
        return await Task.FromResult(new List<string> { contractorname });
    }

    public static bool IsPerm(string id)
    {
        // Simulate the Contractor_placement::isPerm PHP method
        // This should be replaced with actual logic
        return false;
    }

    // Contractor_placement.php L733-744 → percentageLookupList
    public static Dictionary<string, object> PercentageLookupList(double increment = 0.25, double min = 0.0, double max = 100.0)
    {
        var list = new Dictionary<string, object>();
        var begin = Math.Max(min, 0.0);
        var end = Math.Min(max, 100.0);
        var add = Math.Max(Math.Min(increment, 100.0), 0.01);
        while (begin <= end)
        {
            list[string.Format("{0:F2}", begin)] = new { value = string.Format("{0:F2} %", begin) };
            begin += add;
        }
        return list;
    }

    // Contractor_placement.php L746-756 → updateInsertWorksiteAddress
    public static class Address
    {
        public static async Task<bool> DoExists(
            string streetAddress,
            string additional,
            string city,
            string stateName,
            string zip,
            string country,
            string customerId,
            string type,
            AppDbContext db)
        {
            // Implement the logic to check if the address exists in the database
            // This is a placeholder for the actual implementation
            return await Task.FromResult(true);
        }
    }

    public static class States
    {
        public static string Translate(string stateName)
        {
            // Implement the logic to translate the state name
            // This is a placeholder for the actual implementation
            return stateName;
        }
    }
}

public sealed record WorksiteAddressRequest(
    string StateName,
    string StreetAddress,
    string City,
    string Zip,
    string Country,
    string CustomerId);
