// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → MapGet
        grp.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (AppDbContext db) =>
        {
            var query = @"
                SELECT cphcm.contractor_placement_id AS ContractorPlacementId,
                       cphcm.onb_hr_checklist_type_id AS OnbHrChecklistTypeId,
                       cp.name AS Placement,
                       ohct.name AS OnbHrChecklistType,
                       cphcm.completion_date AS CompletionDate
                  FROM contractor_placement_hr_checklist_details_map cphcm
                  JOIN contractor_placement cp ON cphcm.contractor_placement_id = cp.id
                  JOIN onb_hr_checklist_type ohct ON cphcm.onb_hr_checklist_type_id = ohct.id
                 WHERE cphcm.is_active = 'Y'
                   AND cphcm.is_customer_mapped = 'Y'
                 ORDER BY cphcm.contractor_placement_id DESC
            ";

            var data = await db.Database.GetDbConnection().QueryAsync(query);
            return Results.Ok(new { status = data });
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → MapPost
        app.MapPost("/api/v1/contractor_placement_hr_checklist_details/search", async (
            HttpRequest request,
            AppDbContext db) =>
        {
            var includeExport = false; // Assume some global or configuration setting
            var requestData = await request.ReadFromJsonAsync<Dictionary<string, object>>();
            var perform = true;
            var createcsv = "Y";

            if (bool.TryParse(requestData?["prepare_excel"]?.ToString(), out var prepareExcel) && prepareExcel)
            {
                createcsv = "N";
            }

            if (includeExport && bool.TryParse(requestData?["download_xlsx"]?.ToString(), out var downloadXlsx) && downloadXlsx)
            {
                createcsv = "N";
                // Call pre_download equivalent if needed
            }

            // Perform search logic
            var model = new
            {
                Param = requestData,
                Label = new List<object>(),
                Data = new List<object>()
            };

            if (perform)
            {
                // Simulate search execution
                var data = new List<object>(); // Replace with actual search logic
                if (data.Count < 1)
                {
                    return Results.Ok(new { message = "Nothing Found" });
                }
                else
                {
                    // Convert labels to objects if needed
                }
            }

            // Organize and display results
            return Results.Ok(model);
        });

        return app;
    }


}


