// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/PortalContractorController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class PortalContractorEndpoints
{
    public static IEndpointRouteBuilder MapPortalContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/portalcontractor").WithTags("PortalContractor");

        // PortalContractorController.php L24-46 → MapGet
        grp.MapGet("/populateHrTypes/{placement_id}", async (int placement_id, AppDbContext db, IConfiguration config) =>
        {
            // L27 → Convert placement_id to int
            var externalHoursType = config.GetValue<string>("external hours type")?.Split('#') ?? Array.Empty<string>();
            var cpHrList = new List<string>();

            // L31 → Search contractor placement hours type map
            var cphList = await db.Set<ContractorPlacementHoursTypeMap>()
                .Where(c => c.ContractorPlacementId == placement_id)
                .ToListAsync();

            foreach (var hrObj in cphList)
            {
                cpHrList.Add(hrObj.HoursTypeId);
            }

            if (cpHrList.Count > 0)
            {
                externalHoursType = cpHrList.ToArray();
            }

            // L38-43 → Query hours_type table
            var query = db.Set<HoursType>()
                .Where(ht => ht.IsActive == "Y" && ht.IsBillable == "Y");

            if (externalHoursType.Length > 0)
            {
                query = query.Where(ht => externalHoursType.Contains(ht.Id));
            }

            var result = await query.Select(ht => new { ht.Id, Value = ht.Description }).ToListAsync();
            return Results.Ok(result);
        });

        // PortalContractorController.php L47-55 → MapPost
        grp.MapPost("/prepopulate-ts/{contractor_id}", async (int contractor_id) =>
        {
            // L49 → convert contractor_id to int
            contractor_id = Convert.ToInt32(contractor_id);

            // L50-51 → check if contractor_id is 0 or 1
            if (contractor_id == 0 || contractor_id == 1)
            {
                return Results.NoContent();
            }

            // L53 → call placementByContractorID
            var placement_id = ContractorPlacement.PlacementByContractorID(contractor_id);

            // L54 → call prePopulateTs
            TsWeekly.PrePopulateTs(placement_id);

            return Results.Ok();
        });

        // PortalContractorController.php L56-85 → MapGet
        grp.MapGet("/tslist/{contractor_id:int}/{status}", async (int contractor_id, string status, AppDbContext db) =>
        {
            // L60-62 → input validation
            if (contractor_id == 0 || contractor_id == 1 || string.IsNullOrEmpty(status))
            {
                return Results.BadRequest();
            }

            // L64 → get placement_id
            var placementId = await db.ContractorPlacements
                .Where(cp => cp.ContractorId == contractor_id)
                .Select(cp => cp.Id)
                .FirstOrDefaultAsync();

            if (placementId == 0)
            {
                return Results.NotFound();
            }

            // L65-78 → determine method
            string method = status switch
            {
                "p" => "pendingTs",
                "r" => "rejectedTs",
                "a" => "pendingApproveTs",
                "ap" => "approvedTs",
                _ => string.Empty
            };

            if (string.IsNullOrEmpty(method))
            {
                return Results.BadRequest();
            }

            // L79-83 → fetch list
            var list = method == "approvedTs"
                ? await TsWeekly.GetApprovedTsAsync(placementId, db)
                : await TsWeekly.GetTsAsync(method, placementId, db);

            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // PortalContractorController.php L87-98 → MapGet
        grp.MapGet("/leave-list/{contractor_id:int}/{status_id:int}", async (int contractor_id, int status_id, AppDbContext db) =>
        {
            // L91 → validate contractor_id
            if (contractor_id == 0 || contractor_id == 1)
            {
                return Results.BadRequest("Invalid contractor_id");
            }

            // L95 → fetch leave list
            var list = await Leaves.LeaveListQueryAsync(contractor_id, status_id, "N", db);

            // L97 → return list
            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // PortalContractorController.php L727-741 → MapGet
        grp.MapGet("/report", async (HttpContext ctx, AppDbContext db) =>
        {
            var userId = ctx.User.FindFirst("id")?.Value;
            if (userId == null)
            {
                return Results.Unauthorized();
            }

            var menu = MenuDefinition();
            if (!Contractor.IsAllowedForLeave(userId))
            {
                menu.Remove("Leave");
            }

            var model = new
            {
                aprvd_list = GetTsList(userId, "ap"),
                is_allowed_leave = Contractor.IsAllowedForLeave(userId) ? "Y" : "N",
                labels = new[] { "Week End Date", "Customer", "Contractor", "Hours" }
            };

            var action = $"{BaseUrl}/report";
            return RenderPage("extern_report_contractor_timesheet.php", model, menu, action);
        }).RequireAuthorization();

        // PortalContractorController.php L743-770 → MapGet
        grp.MapGet("/leavereport", async (HttpContext ctx, AppDbContext db) =>
        {
            var userId = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var menu = await MenuDefinitionAsync();
            if (!await Contractor.IsAllowedForLeaveAsync(userId, db))
            {
                menu.Remove("Leave");
            }

            var values = ctx.Request.Query;
            var fromDate = values.TryGetValue("from_date", out var fd) ? fd.ToString().Trim() : "";
            var toDate = values.TryGetValue("to_date", out var td) ? td.ToString().Trim() : "";
            if (string.IsNullOrEmpty(fromDate))
            {
                fromDate = FinanceCalendar.ByDateMonthStart(DateTime.UtcNow.AddMonths(-2));
            }
            if (string.IsNullOrEmpty(toDate))
            {
                toDate = FinanceCalendar.ByDateMonthEnd(DateTime.Parse(fromDate).AddMonths(2));
            }
            var statusId = values.TryGetValue("status_id", out var sid) ? int.Parse(sid.ToString()) : 0;
            ctx.Session.SetString("PREVREQUEST", CreateUrl(ctx.Request.Path, values));

            var model = new LeaveReportModel
            {
                FromDate = fromDate,
                ToDate = toDate,
                StatusId = statusId,
                AppldList = await GetLeaveListAsync(userId, statusId, db),
                Labels = new[] { "From Date", "To Date", "Status", "Applied Date", "Action" }
            };

            var action = $"{ctx.Request.Scheme}://{ctx.Request.Host}/leavereport";
            return Results.Ok(new { model, action });
        }).RequireAuthorization();

        // PortalContractorController.php L554-634 → MapGet
        grp.MapGet("/timesheet/edit/{id}", async (
            [FromRoute] int id,
            [FromQuery] int download,
            [FromServices] AppDbContext db,
            [FromServices] IHttpContextAccessor httpContextAccessor) =>
        {
            var userId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var menu = MenuDefinition();
            if (!Contractor.IsAllowedForLeave(userId))
            {
                menu.Remove("Leave");
            }
            if (id < 1)
            {
                return Results.BadRequest(new { message = "No Timesheet specified" });
            }
            var contractorId = ContractorPlacement.ContractorByPlacementID(TsWeekly.GetPlacementID(id));
            if (userId != contractorId.ToString())
            {
                return Results.BadRequest(new { message = "Timesheet provided does not belong to you" });
            }
            if (!Contractor.IsTsDirect(contractorId) || !Contractor.HasApprover(contractorId))
            {
                return Results.BadRequest(new { message = "Timesheet provided does not belong to you" });
            }
            if (download == 1)
            {
                var fileObj = TsWeeklyAttachment.GetAttachments(id);
                var fileUrl = fileObj.AttachmentUrl;
                return Results.File(fileUrl);
            }
            var model = new TsWeekly(id)
            {
                Id = id,
                IsApprover = bool.Parse(httpContextAccessor.HttpContext.User.FindFirstValue("is_approver") ?? "false"),
                TsWeeklyId = id,
                IsAllowedLeave = Contractor.IsAllowedForLeave(contractorId) ? "Y" : "N"
            };
            var hourTypes = PopulateHrTypes(model.ContractorPlacementId);
            model.Hours = model.IsAllowedLeave == "Y"
                ? TsDailyFts.FromTsDailyFtsToArray(model.WeekStart, id, out var tsDaily, hourTypes)
                : TsDaily.FromTsDailyToArray(model.WeekStart, id, out tsDaily, hourTypes);
            model.TsDaily = tsDaily;
            model.ContractorName = Contractor.NameByID(contractorId);
            model.CustomerName = Customer.NameByID(ContractorPlacement.CustomerByPlacementID(model.ContractorPlacementId));
            model.CustomerId = ContractorPlacement.CustomerByPlacementID(model.ContractorPlacementId);
            model.CountryId = ContractorPlacement.CountryByPlacementID(model.ContractorPlacementId);
            model.StatusName = model.IsVerified == "Y"
                ? TsWeeklyStatus.ByID(model.TsWeeklyStatusId) + " / Verified"
                : TsWeeklyStatus.ByID(model.TsWeeklyStatusId);
            model.ApproverNote = TsWeeklyNotes.GetApproverNote(id);
            model.ContractorNote = TsWeeklyNotes.GetContractorNote(id);
            model.Attachments = TsWeeklyAttachment.GetAttachments(id);
            var cpObj = new ContractorPlacement(model.ContractorPlacementId);
            var profile = cpObj.ProfileByTimestamp(FinanceCalendar.ByDateWeekEnd(model.WeekStart));
            model.EmploymentType = cpObj.GetContractTypeName();
            var recProfObj = cpObj.RecentProfile();
            if (Billprofile.IsOTBillable(recProfObj.Id) || profile.IsNonexempt == "Y")
            {
                hourTypes[2] = HoursType.ByID(2);
            }
            if (model.IsAllowedLeave == "Y")
            {
                hourTypes.Remove(2);
            }
            if (model.EmploymentType != "1099" && model.CustomerId != 1000)
            {
                hourTypes[7] = "Time Off";
            }
            model.HourTypes = hourTypes;
            model.PtoHrTypes = PtoHoursType;
            model.FromDate = model.WeekStart;
            model.ToDate = FinanceCalendar.ByDateWeekEnd(model.WeekStart);
            model.StatusId = new[] { 2, 5 };
            var leaves = GetLeaveList(contractorId, model.StatusId);
            model.Leaves = Leaves.FormatLeaveList(leaves);
            return Results.Ok(model);
        }).RequireAuthorization();

        // PortalContractorController.php L636-695 → MapPost
        grp.MapPost("/leave/edit", async (
            [FromServices] AppDbContext db,
            [FromServices] IHttpContextAccessor httpContextAccessor) =>
        {
            var userId = int.Parse(httpContextAccessor.HttpContext.User.FindFirst("id").Value);
            var menu = MenuDefinition();

            if (!await Contractor.IsAllowedForLeaveAsync(db, userId))
            {
                menu.Remove("Leave");
            }

            var leaveId = int.Parse(httpContextAccessor.HttpContext.Request.Path.Value.Split('/').LastOrDefault() ?? "0");
            if (leaveId < 1)
            {
                AddMessage("No Leave specified");
                return await HandleHomePage();
            }

            var contractorId = await Leaves.CreatedByAsync(db, leaveId);
            if (userId != contractorId)
            {
                AddMessage("This leave application provided does not belong to you");
                return await HandleHomePage();
            }

            if (!await Contractor.IsTsDirectAsync(db, userId) || !await Contractor.HasApproverAsync(db, contractorId))
            {
                AddMessage("This leave application provided does not belong to you");
                return await HandleHomePage();
            }

            var model = await Leaves.LoadAsync(db, leaveId);
            model.IsApprover = bool.Parse(httpContextAccessor.HttpContext.Session.GetString("is_approver") ?? "false");
            model.ContractorName = await Contractor.NameByIdAsync(db, contractorId);
            var placementId = await ContractorPlacement.PlacementByContractorIdAsync(db, contractorId);

            var weeks = DateUniquePeriods(model.FromDate, model.ToDate, "week").Keys;
            bool isApproved;
            string isCancelAllowed;

            if (weeks.Count() > 1)
            {
                var apprStatusList = new List<int>();
                foreach (var week in weeks)
                {
                    var tswkId = await TsWeekly.GetWeeklyIdAsync(db, placementId, week);
                    var tsw = await TsWeekly.LoadAsync(db, tswkId);
                    if (tsw.IsPopulated() && tsw.TsWeeklyStatusId == 4)
                    {
                        apprStatusList.Add(tsw.TsWeeklyStatusId);
                    }
                }
                isApproved = apprStatusList.Contains(4);
            }
            else
            {
                isApproved = await Leaves.CheckApprovedTsAsync(db, model);
            }
            isCancelAllowed = isApproved ? "N" : "Y";

            model.CustomerName = await Customer.NameByIdAsync(db, await ContractorPlacement.CustomerByPlacementIdAsync(db, placementId));
            model.StatusName = await LeaveStatusType.ByIdAsync(db, model.LeaveStatusTypeId);
            model.TypeName = await LeaveType.ByIdAsync(db, model.LeaveTypeId);
            model.LeaveHistory = await LeaveStatusHistory.GetHistoryAsync(db, leaveId);
            model.IsCancelAllowed = isCancelAllowed;

            SaveUrl = $"{BaseUrl}/apply";
            return await RenderPage("extern_edit_leave.php");
        });

        // PortalContractorController.php L697-725 → MapGet
        grp.MapGet("/home", async (
            HttpContext ctx,
            AppDbContext db,
            IConfiguration config) =>
        {
            var userId = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Results.Unauthorized();

            var model = new
            {
                AcadTrainee1099 = false,
                Pending = await GetTsList(db, userId, 'p'),
                Rejected = await GetTsList(db, userId, 'r'),
                Pendappr = await GetTsList(db, userId, 'a'),
                SubmittalHistory = await GetTsList(db, userId, 'a'),
                Labels = new[] { "Week End Date", "Customer", "Approver", "Hours" },
                IsAllowedLeave = await ContractorIsAllowedForLeave(db, config, userId) ? "Y" : "N"
            };

            var menu = await GetMenuDefinition(db, userId);
            if (!await ContractorIsAllowedForLeave(db, config, userId))
            {
                menu.Remove("Leave");
            }

            var placementId = await ContractorPlacementByContractorID(db, userId);
            var cpObj = await GetContractorPlacement(db, placementId);
            if (cpObj != null)
            {
                var customerId = await CustomerByPlacementID(db, placementId);
                var empType = cpObj.ContractTypeName;
                if (customerId == 1000 && empType == "1099")
                {
                    model = model with { AcadTrainee1099 = true };
                }
            }

            return Results.Ok(model);
        }).RequireAuthorization();

        return app;
    }

    // PortalContractorController.php L56-85 → getTsList
    public static class TsWeekly
    {
        public static async Task<IEnumerable<object>> GetApprovedTsAsync(int placementId, AppDbContext db)
        {
            // Implement the logic to fetch approved timesheets
            // Example placeholder logic:
            return await db.TsWeeklies
                .Where(ts => ts.PlacementId == placementId && ts.Status == "approved")
                .ToListAsync();
        }

        public static async Task<IEnumerable<object>> GetTsAsync(string method, int placementId, AppDbContext db)
        {
            // Implement the logic to fetch timesheets based on method
            // Example placeholder logic:
            return await db.TsWeeklies
                .Where(ts => ts.PlacementId == placementId && ts.Status == method)
                .ToListAsync();
        }
    }

    // PortalContractorController.php L87-98 → getLeaveList
    public static class Leaves
    {
        public static async Task<List<LeaveDto>> LeaveListQueryAsync(int contractorId, int statusId, string flag, AppDbContext db)
        {
            // Implement the query logic here, using EF Core or Dapper
            // Example placeholder:
            return await db.Leaves
                .Where(l => l.ContractorId == contractorId && l.StatusId == statusId && l.Flag == flag)
                .ToListAsync();
        }
    }

    public class LeaveDto
    {
        public int Id { get; set; }
        public int ContractorId { get; set; }
        public int StatusId { get; set; }
        public string Flag { get; set; }
        // Add other necessary properties
    }

    // PortalContractorController.php L727-741 → handleTsReport
    private static Dictionary<string, object> MenuDefinition()
    {
        // Implement menu definition logic here
        return new Dictionary<string, object>();
    }

    private static List<object> GetTsList(string userId, string status)
    {
        // Implement timesheet list retrieval logic here
        return new List<object>();
    }

    private static IResult RenderPage(string page, object model, Dictionary<string, object> menu, string action)
    {
        // Implement rendering logic here
        return Results.Ok(); // Placeholder for actual rendering
    }

    public static class Contractor
    {
        public static bool IsAllowedForLeave(string userId)
        {
            // Implement leave permission logic here
            return true; // Placeholder logic
        }
    }

    // PortalContractorController.php L743-770 → handleLeaveReport
    public static async Task<bool> IsAllowedForLeaveAsync(string userId, AppDbContext db)
    {
        // Implement the logic to check if the user is allowed for leave
        return await Task.FromResult(true); // Placeholder
    }

    public static async Task<List<object>> GetLeaveListAsync(string userId, int statusId, AppDbContext db)
    {
        // Implement the logic to get the leave list
        return await Task.FromResult(new List<object>()); // Placeholder
    }

    public static async Task<Dictionary<string, string>> MenuDefinitionAsync()
    {
        // Implement the logic to get the menu definition
        return await Task.FromResult(new Dictionary<string, string>());
    }

    public static string CreateUrl(string path, IQueryCollection values)
    {
        // Implement the logic to create URL
        return path + "?" + string.Join("&", values.Select(kvp => kvp.Key + "=" + kvp.Value));
    }

    public static class FinanceCalendar
    {
        public static string ByDateMonthStart(DateTime date)
        {
            // Implement the logic to get the start of the month
            return date.ToString("yyyy-MM-01");
        }

        public static string ByDateMonthEnd(DateTime date)
        {
            // Implement the logic to get the end of the month
            return date.AddMonths(1).AddDays(-1).ToString("yyyy-MM-dd");
        }
    }

    // PortalContractorController.php L554-634 → handleTsEdit
    public static Dictionary<string, string> MenuDefinition() => new Dictionary<string, string> { { "Leave", "Leave" } };

    // PortalContractorController.php L636-695 → handleLeaveEdit
    private static Dictionary<string, object> MenuDefinition() { /* Implement menu definition logic */ }
    private static void AddMessage(string message) { /* Implement message addition logic */ }
    private static Task<IActionResult> HandleHomePage() { /* Implement home page handling logic */ }
    private static async Task<Dictionary<DateTime, string>> DateUniquePeriods(DateTime fromDate, DateTime toDate, string periodType) { /* Implement date unique periods logic */ }
    private static Task<IActionResult> RenderPage(string page) { /* Implement page rendering logic */ }

    // PortalContractorController.php L697-725 → handleHomePage
    private static async Task<bool> ContractorIsAllowedForLeave(AppDbContext db, IConfiguration config, string userId)
    {
        var ptoCustIds = config.GetValue<string>("pto customers")?.Split(',').Select(id => int.TryParse(id, out var num) ? num : (int?)null).Where(id => id.HasValue).Select(id => id.Value).ToList();
        if (ptoCustIds == null || !ptoCustIds.Any()) return false;

        var query = from cp in db.ContractorPlacements
                    join p in db.Profiles on cp.Id equals p.ContractorPlacementId
                    where p.Id == await RecentProfile(db, cp.Id) &&
                          p.EmploymentTypeId == 4 &&
                          cp.ContractorId == int.Parse(userId) &&
                          ptoCustIds.Contains(cp.CustomerId)
                    select cp.Id;

        return await query.AnyAsync();
    }

    private static async Task<int?> ContractorPlacementByContractorID(AppDbContext db, string userId)
    {
        return await db.ContractorPlacements.Where(cp => cp.ContractorId == int.Parse(userId)).Select(cp => cp.Id).FirstOrDefaultAsync();
    }

    private static async Task<ContractorPlacement?> GetContractorPlacement(AppDbContext db, int? placementId)
    {
        return placementId.HasValue ? await db.ContractorPlacements.FindAsync(placementId.Value) : null;
    }

    private static async Task<int?> CustomerByPlacementID(AppDbContext db, int? placementId)
    {
        return placementId.HasValue ? await db.ContractorPlacements.Where(cp => cp.Id == placementId.Value).Select(cp => cp.CustomerId).FirstOrDefaultAsync() : null;
    }

    private static async Task<List<string>> GetTsList(AppDbContext db, string userId, char status)
    {
        // Placeholder for actual implementation
        return new List<string>();
    }

    private static async Task<Dictionary<string, object>> GetMenuDefinition(AppDbContext db, string userId)
    {
        // Placeholder for actual implementation
        return new Dictionary<string, object>();
    }
}

public sealed record LeaveReportModel
{
    public string FromDate { get; init; }
    public string ToDate { get; init; }
    public int StatusId { get; init; }
    public List<object> AppldList { get; init; }
    public string[] Labels { get; init; }
}
