// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsEntityController.php L48-60 → MapPost
        grp.MapPost("/", async (
            HttpRequest request,
            AppDbContext db) =>
        {
            // L50 → set request
            var op = request.Form.TryGetValue("op", out var opValue) ? opValue.ToString() : "";

            switch (op)
            {
                case "":
                    // L54 → call parent create logic
                    return await ParentCreate(request, db);

                default:
                    break;
            }
            return Results.BadRequest(); // Handle unexpected operation
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        return app;
    }

    // Contractor_placement_hr_checklist_detailsEntityController.php L48-60 → create
    private static async Task<IResult> ParentCreate(HttpRequest request, AppDbContext db)
    {
        // L258-294 → inline parent create logic
        var obj = await Validate(request.Form, true);
        if (obj == null) return Results.ValidationProblem(new Dictionary<string, string> { { "error", "Validation failed" } });

        // Save logic
        if (!await PreSave() || !await SaveModel(obj))
        {
            return Results.BadRequest(new { message = "Problem saving entry (New)" });
        }

        // Redirect logic
        var url = PostSave();
        if (request.Form.TryGetValue("output", out var output) && output.ToString() == "json")
        {
            return Results.Ok(obj);
        }
        else if (url is string)
        {
            return Results.Redirect(url);
        }
        return Results.NoContent();
    }
}


