// SPDX-License-Identifier: Apache-2.0
// Generated by CrudResourceExpander (deterministic — no LLM call)
//
// Resource:        /api/v1/contractor-placement
// Entity:          Magicbox.Api.Domain.ContractorPlacement
// Source PHP:      Controller/Contractor_placementEntityController.php
// Translated slots already in ContractorPlacementEndpoints.cs (suppressed here): []
// Scaffold types:  CreateDto=True, UpdateDto=True, ResponseDto=True, AuthPolicies.ContractorPlacement{Read,Write,Delete}=False,False,False

// HITL: prune slots, refine body projection, wire validators.
//
using FluentValidation;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Magicbox.Api.Auth;
using Magicbox.Api.Data;
using Magicbox.Api.Domain;
using Magicbox.Api.Dtos;

namespace Application.Endpoints;

public static class ContractorPlacementCrudEndpoints
{
    public static IEndpointRouteBuilder MapContractorPlacementCrudEndpoints(this IEndpointRouteBuilder app)
    {
        var g = app.MapGroup("/api/v1/contractor-placement").WithTags("ContractorPlacement");

        // TODO HITL: AuthPolicies.ContractorPlacementRead is not in the scaffold — wire a policy in Program.cs and add the constant
        // LIST — paginated; replace .Take(500) with caller-driven page size
        g.MapGet("/", async (AppDbContext db) =>
        {
            var rows = await db.Set<ContractorPlacement>()
                .OrderByDescending(x => x.CreatedAt)
                .Take(500)
                .ToListAsync();
            return Results.Ok(new { records = rows, count = rows.Count });
        });

        // TODO HITL: AuthPolicies.ContractorPlacementRead is not in the scaffold — wire a policy in Program.cs and add the constant
        // SEARCH — filters derived from scaffold (JWM step not available for this controller)
        g.MapGet("/search", async (HttpRequest req, AppDbContext db) =>
        {
            var query = db.Set<ContractorPlacement>().AsQueryable();
            var rows = await query.OrderByDescending(x => x.CreatedAt).Take(500).ToListAsync();
            return Results.Ok(new { records = rows, count = rows.Count });
        });

        // TODO HITL: AuthPolicies.ContractorPlacementRead is not in the scaffold — wire a policy in Program.cs and add the constant
        // DETAIL
        g.MapGet("/{id}", async (string id, AppDbContext db) =>
        {
            var row = await db.Set<ContractorPlacement>().FindAsync(id);
            return row is null ? Results.NotFound() : Results.Ok(row);
        });

        // TODO HITL: AuthPolicies.ContractorPlacementWrite is not in the scaffold — wire a policy in Program.cs and add the constant
        // CREATE
        g.MapPost("/", async (
            ContractorPlacementCreateDto dto,
            IValidator<ContractorPlacementCreateDto> validator,
            AppDbContext db) =>
        {
            var result = await validator.ValidateAsync(dto);
            if (!result.IsValid) return Results.ValidationProblem(result.ToDictionary());
            var row = new ContractorPlacement
            {
                // HITL: assign Domain fields from dto.<Field>.
                // Defaults stamped below to satisfy non-null Id / CreatedAt;
                // operator should remove if not appropriate for this entity.
                Id = Guid.NewGuid().ToString(),
                CreatedAt = DateTime.UtcNow,
            };
            db.Set<ContractorPlacement>().Add(row);
            await db.SaveChangesAsync();
            return Results.Created($"/api/v1/contractor-placement/{row.Id}", row);
        });

        // TODO HITL: AuthPolicies.ContractorPlacementWrite is not in the scaffold — wire a policy in Program.cs and add the constant
        // UPDATE
        g.MapPut("/{id}", async (
            string id,
            ContractorPlacementUpdateDto dto,
            IValidator<ContractorPlacementUpdateDto> validator,
            AppDbContext db) =>
        {
            var result = await validator.ValidateAsync(dto);
            if (!result.IsValid) return Results.ValidationProblem(result.ToDictionary());
            var existing = await db.Set<ContractorPlacement>().FindAsync(id);
            if (existing is null) return Results.NotFound();
            // HITL: project dto.<Field> onto existing.<Field>.
            existing.UpdatedAt = DateTime.UtcNow;
            await db.SaveChangesAsync();
            return Results.Ok(existing);
        });

        // TODO HITL: AuthPolicies.ContractorPlacementDelete is not in the scaffold — wire a policy in Program.cs and add the constant
        // DELETE
        g.MapDelete("/{id}", async (string id, AppDbContext db) =>
        {
            var existing = await db.Set<ContractorPlacement>().FindAsync(id);
            if (existing is null) return Results.NotFound();
            db.Set<ContractorPlacement>().Remove(existing);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });

        return app;
    }
}
