// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
        app.MapPost("/api/v1/contractor_placement_hr_checklist_details/search", async (HttpContext ctx) =>
        {
            var request = await ctx.Request.ReadFromJsonAsync<Request>();
            var includeExport = false; // Assume a default or inject as needed

            if (request == null)
                return Results.BadRequest(new { error = "Invalid request" });

            if (BoolValue(Dov("prepare_excel", request.Data, false)))
            {
                // Handle Search (Download Only)
                // createcsv = 'N';
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                // Handle Page Options Download button
                // createcsv = 'N';
                PreDownload();
            }

            var perform = true;
            var embed = Dfv("embed", request.Data, 0);
            var model = new Model
            {
                Param = request.Data,
                Label = new List<object>(),
                Data = new List<object>()
            };

            if (string.IsNullOrEmpty(Dfv("HTTP_X_REQUESTED_WITH", ctx.Request.Headers, ""))
                && Dfv("response", request.Data, "") != "json"
                && Dfv("op", request.Data, "") != "download"
                && Dfv("op", request.Data, "") != "delete"
                && !Dfv("embed", request.Data, 0)
                && !Dfv("request", request.Data, "").EndsWith(".json"))
            {
                // Session logic
                // _session["PREVREQUEST"] = ...
            }

            var hideoptbox = Int32.Parse(BoolValue(Dfv("hideoptbox", request.Data, Dfv("hide_option_box", request.Data, 0))).ToString());
            ResetMessage();

            PreSearch(perform);

            if (perform)
            {
                SetExecuteStart();
                model.Data = new List<object>();
                var label = new List<object>();

                if (Search() < 1)
                {
                    AddMessage("Nothing Found");
                }
                else
                {
                    ConvertLabelsToObjects();
                }

                SetExecuteFinish();
            }

            if (includeExport && BoolValue(Dov("download_xlsx", request.Data, false)))
            {
                return RunDownload(request, perform);
            }

            Organize();

            return Display();
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
        app.MapGet("/contractorplacement/contractorplacementsearchcontroller", async (AppDbContext db) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L28-40 → SQL query
            var query = from cphcm in db.ContractorPlacementHrChecklistDetailsMap
                        join cp in db.ContractorPlacement on cphcm.ContractorPlacementId equals cp.Id
                        join ohct in db.OnbHrChecklistType on cphcm.OnbHrChecklistTypeId equals ohct.Id
                        where cphcm.IsActive == "Y" && cphcm.IsCustomerMapped == "Y"
                        orderby cphcm.ContractorPlacementId descending
                        select new
                        {
                            contractor_placement_id = cphcm.ContractorPlacementId,
                            onb_hr_checklist_type_id = cphcm.OnbHrChecklistTypeId,
                            placement = cp.Name,
                            onb_hr_checklist_type = ohct.Name,
                            completion_date = cphcm.CompletionDate
                        };

            var data = await query.ToListAsync();

            // Parent class logic for CSV export
            if (data.Any() && boolValue(createCsv))
            {
                using var csv = new Csv(resultFile, false, "w");
                csv.Write(data.First());
                foreach (var line in data.Skip(1))
                {
                    csv.Write(line);
                }
            }

            return Results.Json(new { status = data.Count });
        });

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → label
        app.MapGet("/api/v1/contractor_placement_hr_checklist_details/label", (ContractorPlacementHrChecklistDetailsModel model) =>
        {
            // Contractor_placement_hr_checklist_detailsSearchController.php L49-52 → set labels
            model.Label = new Dictionary<string, object[]>
            {
                { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
                { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
                { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", $"{model.Server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
            };
            return Results.Ok(true);
        });

        return app;
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L19-22 → run
    // Helper methods translated from PHP

    private static bool BoolValue(object value)
    {
        return Convert.ToBoolean(value);
    }

    private static object Dov(string key, Dictionary<string, object> data, object defaultValue)
    {
        return data.ContainsKey(key) ? data[key] : defaultValue;
    }

    private static object Dfv(string key, Dictionary<string, object> data, object defaultValue)
    {
        return data.ContainsKey(key) ? data[key] : defaultValue;
    }

    private static void ResetMessage()
    {
        // Reset message logic
    }

    private static void PreSearch(bool perform)
    {
        // Pre-search logic
    }

    private static void SetExecuteStart()
    {
        // Set execute start logic
    }
    }

    private static int Search()
    {
        // Search logic
        return 0;
    }

    private static void AddMessage(string message)
    {
        // Add message logic
    }

    private static void ConvertLabelsToObjects()
    {
        // Convert labels to objects logic
    }

    private static void SetExecuteFinish()
    {
        // Set execute finish logic
    }

    private static void Organize()
    {
        // Organize logic
    }

    private static object Display()
    {
        // Display logic
        return new { }; // Placeholder
    }

    private static object RunDownload(object request, bool perform)
    {
        // Run download logic
        return new { }; // Placeholder
    }

    private static void PreDownload()
    {
        // Pre-download logic
    }

    // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → search
    // Helper function to convert string to boolean
    private static bool boolValue(string value)
    {
        return !string.IsNullOrEmpty(value) && (value.ToLower() == "true" || value == "1");
    }

    // Csv helper class
    public class Csv : IDisposable
    {
        private StreamWriter _writer;

        public Csv(string path, bool append, string mode)
        {
            _writer = new StreamWriter(path, append);
        }

        public void Write(object line)
        {
            // Implement CSV writing logic here
        }

        public void Dispose()
        {
            _writer?.Dispose();
        }
    }
}

public class Request
{
    public Dictionary<string, object> Data { get; set; }
}

public class Model
{
    public Dictionary<string, object> Param { get; set; }
    public List<object> Label { get; set; }
    public List<object> Data { get; set; }
}
