// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placementSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placementSearchController.php L118-138 → downloadFile
        grp.MapGet("/downloadFile", async (HttpContext ctx, [FromQuery] string file, [FromQuery] string altname, [FromServices] IFileService fileService) =>
        {
            // Contractor_placementSearchController.php L120 → global docpath
            var docpath = ctx.RequestServices.GetRequiredService<IConfiguration>().GetValue<string>("DocPath");

            // Contractor_placementSearchController.php L122-123 → extract id and seqno
            var id = int.TryParse(ctx.Request.Query["id"], out var idValue) ? idValue : 0;
            var seqno = int.TryParse(ctx.Request.Query["seqno"], out var seqnoValue) ? seqnoValue : 0;

            if (id > 0 && seqno > 0)
            {
                // Contractor_placementSearchController.php L126-130 → glob pattern
                var filepat = Path.Combine(docpath, "Contract/Client_Approval_Documents", $"{id}_{seqno}.*");
                var files = Directory.GetFiles(Path.GetDirectoryName(filepat), Path.GetFileName(filepat));
                if (files.Any())
                {
                    await fileService.DownloadFileAsync(ctx, files.First());
                    return;
                }
            }
            else if (id > 0)
            {
                // Contractor_placementSearchController.php L132-134 → getAttachments
                var attachment = ContractorPlacementAttachment.GetAttachments(id).FirstOrDefault();
                if (attachment != null)
                {
                    await fileService.DownloadFileAsync(ctx, attachment.AttachmentUrl);
                    return;
                }
            }

            // Contractor_placementSearchController.php L136-137 → fallback
            await fileService.DownloadFileAsync(ctx, file);
        });

        return app;
    }


}


