// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/article/ArticleFacade.kt
//
package article

import (
	"context"
	"fmt"
	"github.com/google/uuid"
	"time"
)

func (s *articleFacadeImpl) CreateArticle(ctx context.Context, request CreateArticleRequest, author user.User) (ArticleView, error) {
    id := uuid.New().String()
    newArticle := request.ToArticle(id, author.ID)

    ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
    defer cancel()

    savedArticle, err := s.userRepo.Save(ctx, newArticle)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }

    err = s.tagRepo.SaveAllTags(ctx, savedArticle.Tags)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save tags: %w", err)
    }

    authorProfileView := author.ToOwnProfileView()
    return savedArticle.ToArticleView(authorProfileView, author), nil
}

func (s *articleFacadeImpl) GetArticle(ctx context.Context, slug string, currentUser *user.User) (*ArticleView, error) {
    article, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return nil, fmt.Errorf("find article by slug: %w", err)
    }
    author, err := s.userRepo.FindAuthorByArticle(ctx, article)
    if err != nil {
        return nil, fmt.Errorf("find author by article: %w", err)
    }
    return article.ToArticleView(author, currentUser), nil
}

func (s *articleFacadeImpl) UpdateArticle(ctx context.Context, request UpdateArticleRequest, slug string, author user.User) (ArticleView, error) {
    articleToUpdate, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    if !articleToUpdate.IsAuthor(author) {
        return ArticleView{}, fmt.Errorf("only author can update article: %w", ErrInvalidRequest)
    }

    updateUser(request, articleToUpdate)

    savedArticle, err := s.userRepo.Save(ctx, articleToUpdate)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save article: %w", err)
    }

    return savedArticle.ToAuthorArticleView(author), nil
}

func (s *articleFacadeImpl) DeleteArticle(ctx context.Context, slug string, user user.User) error {
    articleToDelete, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return fmt.Errorf("find article: %w", err)
    }

    if !articleToDelete.IsAuthor(user) {
        return fmt.Errorf("only author can delete own article")
    }

    if err := s.userRepo.DeleteBySlug(ctx, slug); err != nil {
        return fmt.Errorf("delete article: %w", err)
    }

    return nil
}

// internal/article/handler.go



func (s *articleFacadeImpl) Feed(ctx context.Context, offset int64, limit int, user user.User) (MultipleArticlesView, error) {
    articles, err := s.userRepo.FindNewestArticlesByAuthorIds(ctx, user.FollowingIDs, offset, limit)
    if err != nil {
        return MultipleArticlesView{}, fmt.Errorf("find newest articles: %w", err)
    }

    var articleViews []ArticleView
    for _, article := range articles {
        articleView := mapToArticleView(article, user)
        articleViews = append(articleViews, articleView)
    }

    return toMultipleArticlesView(articleViews), nil
}

func (s *articleFacadeImpl) UpdateUser(ctx context.Context, request UpdateArticleRequest, articleToUpdate *Article) error {
    if request.Body != nil {
        articleToUpdate.Body = *request.Body
    }
    if request.Description != nil {
        articleToUpdate.Description = *request.Description
    }
    if request.Title != nil {
        articleToUpdate.Title = *request.Title
    }
    return nil
}

func (s *articleFacadeImpl) FavoriteArticle(ctx context.Context, slug string, currentUser user.User) (ArticleView, error) {
    article, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }

    err = currentUser.Favorite(article)
    if err != nil {
        return ArticleView{}, fmt.Errorf("favorite article: %w", err)
    }

    err = s.userRepo.Save(ctx, currentUser)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }

    return s.mapToArticleView(article, currentUser), nil
}

func (s *articleFacadeImpl) UnfavoriteArticle(ctx context.Context, slug string, currentUser user.User) (ArticleView, error) {
    article, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return ArticleView{}, fmt.Errorf("find article by slug: %w", err)
    }
    err = currentUser.Unfavorite(article)
    if err != nil {
        return ArticleView{}, fmt.Errorf("unfavorite article: %w", err)
    }
    err = s.userRepo.Save(ctx, currentUser)
    if err != nil {
        return ArticleView{}, fmt.Errorf("save user: %w", err)
    }
    return s.mapToArticleView(article, currentUser), nil
}

// internal/article/handler.go



// internal/article/handler.go



// internal/article/handler.go



type Service interface {
    MapToCommentView(ctx context.Context, comment Comment, viewer *user.User) (CommentView, error)
}

type articleFacadeImpl struct {
    userRepo user.Repository
	tagRepo articleFacadeImpl_tagRepo_iface}

type articleFacadeImpl_tagRepo_iface interface {
	SaveAllTags(args ...any) error
}


func (s *articleFacadeImpl) MapToCommentView(ctx context.Context, comment Comment, viewer *user.User) (CommentView, error) {
    commentAuthor, err := s.userRepo.FindByID(ctx, comment.AuthorID)
    if err != nil {
        return CommentView{}, fmt.Errorf("find author: %w", err)
    }
    return comment.ToCommentView(commentAuthor, viewer), nil
}

func (s *articleFacadeImpl) GetComments(ctx context.Context, slug string, viewer *user.User) (MultipleCommentsView, error) {
    article, err := s.userRepo.FindBySlug(ctx, slug)
    if err != nil {
        return MultipleCommentsView{}, fmt.Errorf("find article by slug: %w", err)
    }
    comments := make([]CommentView, 0)
    for _, comment := range article.Comments {
        commentView := mapToCommentView(comment, viewer)
        comments = append(comments, commentView)
    }
    return toMultipleCommentsView(comments), nil
}
