# Use the official .NET 8 SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY src/CustomerAndAccountArchcontractor.Api/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY src/CustomerAndAccountArchcontractor.Api/. ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

# Set the environment variable for the port
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "CustomerAndAccountArchcontractor.Api.dll"]