# Start with the official Golang image
FROM golang:1.18-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod .

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o userservice

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./userservice"]
