// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placementEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placementEntityController.php L2916-2935 → getCcpRateColums
        app.MapGet("/api/v1/contractor-placement/rate-columns", async (ContractorPlacementModel model) =>
        {
            // Contractor_placementEntityController.php L2917-2933 → get rate columns
            var typeArr = model.RateColVaries;
            var rateCols = new Dictionary<string, Dictionary<string, string>>();
            var excludeCols = new HashSet<string> { "pct_discount", "pct_vms_fee", "pct_discount_inv", "pct_discount_vol", "burden_sick", "burden_sick_zip", "burden_sick_state", "hr_facility_fee", "hr_fringe_benefit" };

            foreach (var entry in typeArr)
            {
                var fieldName = entry.Key;
                var row = entry.Value;

                if (excludeCols.Contains(fieldName))
                    continue;

                var fieldLabel = Dfv(0, row, "");
                var fieldFactor = Dfv(1, row, "");
                var fieldEntity = Dfv(2, row, "");
                var fieldFreq = Dfv(3, row, 0) == 1 ? "Y" : "N";

                rateCols[fieldName] = new Dictionary<string, string>
                {
                    { "label", fieldLabel },
                    { "factor", fieldFactor },
                    { "entity", fieldEntity },
                    { "has_freq", fieldFreq }
                };
            }

            return Results.Json(rateCols);
        });

        return app;
    }

    // Contractor_placementEntityController.php L2916-2935 → getCcpRateColums
    private static string Dfv(int index, List<object> row, string defaultValue)
    {
        return row.Count > index ? row[index]?.ToString() ?? defaultValue : defaultValue;
    }

    private static int Dfv(int index, List<object> row, int defaultValue)
    {
        return row.Count > index && int.TryParse(row[index]?.ToString(), out var result) ? result : defaultValue;
    }
}


