// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L24-44 → MapGet
        grp.MapGet("/", async (AppDbContext db) =>
        {
            // L28-39 → build the query using LINQ
            var query = from cphcm in db.Set<ContractorPlacementHrChecklistDetailMap>()
                        join cp in db.Set<ContractorPlacement>() on cphcm.ContractorPlacementId equals cp.Id
                        join ohct in db.Set<OnboardingHrChecklistType>() on cphcm.OnbHrChecklistTypeId equals ohct.Id
                        where cphcm.IsActive == "Y" && cphcm.IsCustomerMapped == "Y"
                        orderby cphcm.ContractorPlacementId descending
                        select new
                        {
                            ContractorPlacementId = cphcm.ContractorPlacementId,
                            OnbHrChecklistTypeId = cphcm.OnbHrChecklistTypeId,
                            Placement = cp.Name,
                            OnbHrChecklistType = ohct.Name,
                            CompletionDate = cphcm.CompletionDate
                        };

            var results = await query.ToListAsync();
            return Results.Ok(new { count = results.Count });
        }).RequireAuthorization(AuthPolicies.SomePolicy);

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → MapGet
        grp.MapGet("/label", async (AppDbContext db) =>
        {
            // L368-370 → parent label method
            var labels = new Dictionary<string, object>();

            // L49-52 → build the label structure
            labels["placement"] = new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" };
            labels["onb_hr_checklist_type"] = new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" };
            labels["completion_date"] = new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", "{this.server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" };

            return Results.Ok(labels);
        }).RequireAuthorization(AuthPolicies.ContractorPlacementRead);

        return app;
    }


}


