// SPDX-License-Identifier: Apache-2.0
// Generated by wiring-auth-go-v1.0 — Vansham V2 §3.3 fix.
//
// JWT validation with RS256 + kid header lookup against a published
// JWKS endpoint. Replaces the Phase 1 auth context-key helper.
package auth

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

// ErrInvalidToken is returned when a token is malformed, expired,
// signed by the wrong algorithm, or its kid is unknown. Callers must
// not surface the underlying error message to clients — it can leak
// kid lookup state.
var ErrInvalidToken = errors.New("invalid token")

// Claims is the engagement-shaped JWT payload. The Issuer / Audience
// fields are validated against config values in NewValidator.
type Claims struct {
	jwt.RegisteredClaims
	UserID uuid.UUID `json:"user_id"`
	Scopes []string  `json:"scopes,omitempty"`
}

// KeySet is the JWKS / public-key registry the validator consults on
// each ``Parse``. Implementations rotate keys behind the lock — the
// validator never caches a *rsa.PublicKey reference outside this lookup.
type KeySet interface {
	PublicKey(kid string) (any, error)
}

// Validator parses + verifies a JWT. Construct one per process (cheap)
// and share it across handlers via a middleware.
type Validator struct {
	keys     KeySet
	issuer   string
	audience string
	clock    func() time.Time
	mu       sync.RWMutex
}

// NewValidator wires the keyset + the expected issuer / audience. Both
// are required — empty issuer = misconfigured config, refuse to start.
func NewValidator(keys KeySet, issuer, audience string) (*Validator, error) {
	if keys == nil {
		return nil, errors.New("auth.NewValidator: keys is nil")
	}
	if strings.TrimSpace(issuer) == "" {
		return nil, errors.New("auth.NewValidator: issuer is empty")
	}
	if strings.TrimSpace(audience) == "" {
		return nil, errors.New("auth.NewValidator: audience is empty")
	}
	return &Validator{
		keys:     keys,
		issuer:   issuer,
		audience: audience,
		clock:    time.Now,
	}, nil
}

// Parse validates the token. Returns ErrInvalidToken on any failure —
// callers MUST NOT distinguish the underlying cause to the client.
func (v *Validator) Parse(raw string) (*Claims, error) {
	if raw == "" {
		return nil, ErrInvalidToken
	}
	parser := jwt.NewParser(
		jwt.WithValidMethods([]string{jwt.SigningMethodRS256.Alg(), jwt.SigningMethodES256.Alg()}),
		jwt.WithIssuer(v.issuer),
		jwt.WithAudience(v.audience),
		jwt.WithExpirationRequired(),
	)
	claims := &Claims{}
	tok, err := parser.ParseWithClaims(raw, claims, func(token *jwt.Token) (any, error) {
		kid, _ := token.Header["kid"].(string)
		if kid == "" {
			return nil, fmt.Errorf("missing kid header")
		}
		v.mu.RLock()
		defer v.mu.RUnlock()
		return v.keys.PublicKey(kid)
	})
	if err != nil || !tok.Valid {
		return nil, ErrInvalidToken
	}
	if claims.UserID == uuid.Nil {
		return nil, ErrInvalidToken
	}
	return claims, nil
}

// FromRequest pulls the bearer token out of an Authorization header,
// validates it, and returns the claims. Convenience for middleware.
func (v *Validator) FromRequest(r *http.Request) (*Claims, error) {
	hdr := r.Header.Get("Authorization")
	if hdr == "" {
		return nil, ErrInvalidToken
	}
	const prefix = "Bearer "
	if !strings.HasPrefix(hdr, prefix) {
		return nil, ErrInvalidToken
	}
	return v.Parse(strings.TrimSpace(hdr[len(prefix):]))
}

// ── Context propagation ──────────────────────────────────────────────

type ctxKey struct{ name string }

var (
	userIDCtxKey = &ctxKey{"user_id"}
	scopesCtxKey = &ctxKey{"scopes"}
)

// WithClaims puts the validated claims into the request context. The
// require_auth middleware calls this after a successful Parse.
func WithClaims(ctx context.Context, c *Claims) context.Context {
	ctx = context.WithValue(ctx, userIDCtxKey, c.UserID)
	ctx = context.WithValue(ctx, scopesCtxKey, c.Scopes)
	return ctx
}

// UserIDFromContext returns (uuid.Nil, false) when no validated user is
// in scope — caller treats as 401.
func UserIDFromContext(ctx context.Context) (uuid.UUID, bool) {
	v, ok := ctx.Value(userIDCtxKey).(uuid.UUID)
	return v, ok
}

// ScopesFromContext returns the authenticated principal's scopes (or nil).
func ScopesFromContext(ctx context.Context) []string {
	v, _ := ctx.Value(scopesCtxKey).([]string)
	return v
}
