// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsSearchController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsSearchController.php L46-55 → MapGet
        grp.MapGet("/label", async (AppDbContext db) =>
        {
            // L48-50 → set up model labels
            var labels = new Dictionary<string, object[]>
            {
                { "placement", new object[] { "Contractor Placement", "width:100px;", "text-align:left;", 0, false, false, "" } },
                { "onb_hr_checklist_type", new object[] { "Health Screening", "width:150px;", "text-align:left;", 0, false, false, "" } },
                { "completion_date", new object[] { "Completion Date ", "width:150px;", "text-align:left;", 0, "toDisplayDate", "{this.server}/entity/contractor_placement_hr_checklist_details/", "contractor_placement_id", "onb_hr_checklist_type_id" } }
            };
            return Results.Ok(labels);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        return app;
    }


}


