// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/user/UserFacade.kt
//
package user

import (
	"context"
	"errors"
	"fmt"
	"github.com/google/uuid"
)

// UserFacade.kt L15-28 → signup
type userFacadeImpl struct {
	repo Repository
	passwordService PasswordService
	userTokenProvider userFacadeImpl_userTokenProvider_iface}

type userFacadeImpl_userTokenProvider_iface interface {
	GetToken(args ...any) (any, error)
}


func (s *userFacadeImpl) Signup(ctx context.Context, request UserRegistrationRequest) (UserView, error) {
	exists, err := s.repo.ExistsByEmail(ctx, request.Email)
	if err != nil {
		return UserView{}, fmt.Errorf("check email existence: %w", err)
	}
	if exists {
		return UserView{}, ErrEmailAlreadyInUse
	}

	exists, err = s.repo.ExistsByUsername(ctx, request.Username)
	if err != nil {
		return UserView{}, fmt.Errorf("check username existence: %w", err)
	}
	if exists {
		return UserView{}, ErrUsernameAlreadyInUse
	}

	encodedPassword, err := s.passwordService.EncodePassword(request.Password)
	if err != nil {
		return UserView{}, fmt.Errorf("encode password: %w", err)
	}

	id := uuid.New().String()
	user := request.ToUser(encodedPassword, id)

	savedUser, err := s.repo.Save(ctx, user)
	if err != nil {
		return UserView{}, fmt.Errorf("save user: %w", err)
	}

	return s.CreateAuthenticationResponse(savedUser), nil
}

// UserFacade.kt L29-36 → login
func (s *userFacadeImpl) Login(ctx context.Context, request UserAuthenticationRequest) (UserView, error) {
    user, err := s.repo.FindByEmail(ctx, request.Email)
    if errors.Is(err, ErrNotFound) {
        return UserView{}, fmt.Errorf("login: user not found")
    }
    if err != nil {
        return UserView{}, fmt.Errorf("login: %w", err)
    }
    if !s.passwordService.Matches(request.Password, user.EncodedPassword) {
        return UserView{}, InvalidRequestError{"Password", "invalid"}
    }
    return s.CreateAuthenticationResponse(user)
}

// UserFacade.kt L37-43 → updateUser


type Service interface {
    UpdateUser(ctx context.Context, request UpdateUserRequest, userSession UserSession) (UserView, error)
}


func (s *userFacadeImpl) UpdateUser(ctx context.Context, request UpdateUserRequest, userSession UserSession) (UserView, error) {
    user, token := userSession.User, userSession.Token
    if err := s.repo.UpdateUser(ctx, request, user); err != nil {
        return UserView{}, fmt.Errorf("update user: %w", err)
    }
    savedUser, err := s.repo.Save(ctx, user)
    if err != nil {
        return UserView{}, fmt.Errorf("save user: %w", err)
    }
    return savedUser.ToUserView(token), nil
}

// UserFacade.kt L45-51 → updateUser

// UserFacade.kt L57-63 → follow
func (s *userFacadeImpl) Follow(ctx context.Context, username string, futureFollower User) (ProfileView, error) {
    userToFollow, err := s.repo.FindByUsername(ctx, username)
    if err != nil {
        return ProfileView{}, fmt.Errorf("find user by username: %w", err)
    }

    futureFollower.Follow(userToFollow)

    if _, err := s.repo.Save(ctx, futureFollower); err != nil {
        return ProfileView{}, fmt.Errorf("save future follower: %w", err)
    }

    return userToFollow.ToFollowedProfileView(), nil
}

// UserFacade.kt L64-70 → unfollow

// UserFacade.kt L72-80 → updateUsername
func (s *userFacadeImpl) updateUsername(ctx context.Context, user *User, newUsername string) error {
    if user.Username == newUsername {
        return nil
    }
    exists, err := s.repo.ExistsByUsername(ctx, newUsername)
    if err != nil {
        return fmt.Errorf("check username existence: %w", err)
    }
    if exists {
        return ErrUsernameAlreadyInUse
    }
    user.Username = newUsername
    return nil
}

// UserFacade.kt L82-90 → updateEmail
func (s *userFacadeImpl) UpdateEmail(ctx context.Context, user User, newEmail string) error {
    if user.Email == newEmail {
        return nil
    }
    exists, err := s.repo.ExistsByEmail(ctx, newEmail)
    if err != nil {
        return fmt.Errorf("check email existence: %w", err)
    }
    if exists {
        return ErrEmailAlreadyInUse
    }
    user.Email = newEmail
    return nil
}

// UserFacade.kt L92-95 → createAuthenticationResponse
func (s *userFacadeImpl) CreateAuthenticationResponse(ctx context.Context, user User) (UserView, error) {
    token, err := s.userTokenProvider.GetToken(user.ID)
    if err != nil {
        return UserView{}, fmt.Errorf("get token: %w", err)
    }
    return user.ToUserView(token), nil
}
