// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/ContractorEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace Application.Endpoints;

public static class ContractorEndpoints
{
    public static IEndpointRouteBuilder MapContractorEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractor").WithTags("Contractor");

        // ContractorEntityController.php L22-26 → MapGet
        grp.MapGet("/headline", async (string text, AppDbContext db) =>
        {
            // L24 → default to 'Contractor' if text is empty
            var str = string.IsNullOrEmpty(text) ? "Contractor" : text;
            return Results.Ok(str);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L198-208 → MapGet
        grp.MapGet("/links", async () =>
        {
            // L200-207 → build links list
            var list = new List<Dictionary<string, string>>();
            list.Add(new Dictionary<string, string>
            {
                { "0", "Search" },
                { "1", "{server}/search/contractor" },
                { "2", "" }
            });
            return Results.Ok(list);
        }).RequireAuthorization(AuthPolicies.ContractorRead);

        // ContractorEntityController.php L210-281 → validate
        public static async Task<Contractor> ValidateContractorAsync(ContractorCreateDto dto, bool isNew, AppDbContext db)
        {
            var messages = new List<string>();
            Contractor obj;

            if (isNew)
            {
                obj = new Contractor
                {
                    Id = null,
                    CreateTs = DateTime.UtcNow,
                    LastWelcomeEmail = new DateTime(2000, 1, 1)
                };
            }
            else
            {
                var id = int.TryParse(dto.Id, out var parsedId) ? parsedId : 0;
                if (id == 0)
                {
                    messages.Add("ID must be set to Update Entry");
                    throw new ValidationException(messages);
                }
                obj = await db.Set<Contractor>().FindAsync(id);
                if (obj == null)
                {
                    messages.Add("ID provided for Update does not exist");
                    throw new ValidationException(messages);
                }
            }

            obj.Notes = dto.Notes?.Trim();
            obj.Mi = dto.Mi?.Trim();
            obj.IsActive = dto.IsActive ?? 'N';
            obj.AddressId = dto.AddressId ?? 1;
            obj.VisaStatusTypeId = dto.VisaStatusTypeId ?? 1;

            if (obj.VisaStatusTypeId < 1)
            {
                messages.Add("Visa is invalid");
            }

            if (isNew)
            {
                foreach (var field in new[] { "Firstname", "Lastname", "Email", "FileNum", "CompCode" })
                {
                    var value = dto.GetType().GetProperty(field)?.GetValue(dto)?.ToString();
                    if (string.IsNullOrWhiteSpace(value))
                    {
                        messages.Add($"{field} cannot be empty");
                    }
                    obj.GetType().GetProperty(field)?.SetValue(obj, value);
                }
            }
            else
            {
                obj.Email = dto.Email?.Trim();
                if (string.IsNullOrWhiteSpace(obj.Email))
                {
                    messages.Add("Email cannot be empty");
                }
            }

            if (!string.IsNullOrWhiteSpace(obj.Email) && !new EmailAddressAttribute().IsValid(obj.Email))
            {
                messages.Add("Please enter valid Email");
            }

            var exists = isNew ? await db.Set<Contractor>().AnyAsync(c => c.Email == obj.Email && c.IsActive) : await db.Set<Contractor>().AnyAsync(c => c.Id != obj.Id && c.Email == obj.Email && c.IsActive);
            if (exists)
            {
                messages.Add("This email is already taken");
            }

            if (!string.IsNullOrWhiteSpace(obj.Email))
            {
                obj.Username = obj.Email;
            }

            obj.TermDate = DateTime.TryParse(dto.TermDate, out var termDate) ? termDate : DateTime.MinValue;
            if (obj.IsActive != 'Y' && obj.TermDate <= new DateTime(2000, 1, 1))
            {
                messages.Add("Term Date is invalid");
            }

            if (messages.Any())
            {
                throw new ValidationException(messages);
            }

            return obj;
        }

        return app;
    }


}

public sealed record ContractorCreateDto(
    string Id,
    string? Notes,
    string? Mi,
    string? IsActive,
    int? AddressId,
    int? VisaStatusTypeId,
    string? Firstname,
    string? Lastname,
    string? Email,
    string? FileNum,
    string? CompCode,
    string? TermDate);
