// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/api/UserController.kt
//
package user

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"net/http"
	"projbb8df72812/internal/platform/auth"
	"projbb8df72812/internal/platform/httpx"
	"projbb8df72812/internal/springmongo"
)

// UserController.kt L16-18 → signup
func (h *Handler) Signup(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req UserWrapper[UserRegistrationRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        var maxErr *http.MaxBytesError
        if errors.As(err, &maxErr) {
            httpx.WriteError(w, http.StatusRequestEntityTooLarge, "PAYLOAD_TOO_LARGE", "request body exceeds 1 MiB")
            return
        }
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userWrapper, err := h.svc.Signup(r.Context(), req.Content)
    if err != nil {
        if errors.Is(err, ErrEmailAlreadyInUse) {
            httpx.WriteError(w, http.StatusConflict, "EMAIL_ALREADY_IN_USE", "email is already in use")
            return
        }
        if errors.Is(err, ErrUsernameAlreadyInUse) {
            httpx.WriteError(w, http.StatusConflict, "USERNAME_ALREADY_IN_USE", "username is already in use")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusCreated, userWrapper)
}

// UserController.kt L22-24 → login
func (h *Handler) Login(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req UserWrapper[LoginRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userView, err := h.svc.Login(r.Context(), req.Content)
    if err != nil {
        if errors.Is(err, ErrInvalidCredentials) {
            httpx.WriteError(w, http.StatusUnauthorized, "INVALID_CREDENTIALS", "invalid username or password")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userView)
}

// UserController.kt L27-30 → getCurrentUser
func (h *Handler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
    userID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    userSession, err := h.svc.GetCurrentUserSession(r.Context(), userID)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userSession)
}

// UserController.kt L33-36 → updateUser
func (h *Handler) UpdateUser(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req UserWrapper[UpdateUserRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    userWrapper, err := h.svc.UpdateUser(r.Context(), req.Content, userID)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userWrapper)
}

// UserController.kt L39-42 → getProfile
func (h *Handler) GetProfile(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    currentUser, err := h.svc.GetCurrentUserSessionOrNull(r.Context())
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    profile, err := h.svc.GetProfile(r.Context(), username, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profile)
}

// UserController.kt L45-48 → follow
func (h *Handler) Follow(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    userID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    profile, err := h.svc.Follow(r.Context(), username, userID)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profile)
}

// UserController.kt L51-54 → unfollow
func (h *Handler) Unfollow(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    currentUser, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    err = h.svc.Unfollow(r.Context(), username, currentUser)
    if err != nil {
        if errors.Is(err, user.ErrNotFound) {
            httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "user not found")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, map[string]string{"status": "success"})
}

// UserController.kt L27-30 → getCurrentUser
func (usp *UserSessionProvider) GetCurrentUserSessionOrFail(ctx context.Context, userID uuid.UUID) (*User, string, error) {
    context, err := ReactiveSecurityContextHolder.GetContext(ctx)
    if err != nil {
        return nil, "", fmt.Errorf("get security context: %w", err)
    }
    tokenPrincipal, ok := context.Authentication.Principal.(springmongo.TokenPrincipal)
    if !ok {
        return nil, "", errors.New("invalid principal type")
    }
    user, err := usp.userRepository.FindByID(ctx, tokenPrincipal.UserID)
    if err != nil {
        return nil, "", fmt.Errorf("find user by id: %w", err)
    }
    return user, tokenPrincipal.Token, nil
}
