// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/api/ArticleController.kt
//
package article

import (
	"encoding/json"
	"errors"
	"github.com/go-chi/chi/v5"
	"net/http"
	"projbb8df72812/internal/platform/auth"
	"projbb8df72812/internal/platform/httpx"
	"strconv"
)

// ArticleController.kt L15-18 → createArticle
func (h *Handler) CreateArticle(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var dto ArticleWrapper[CreateArticleRequest]
    if err := json.NewDecoder(r.Body).Decode(&dto); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := dto.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    currentUser, err := h.svc.GetCurrentUserOrFail(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    article, err := h.svc.CreateArticle(r.Context(), dto.Content, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusCreated, article)
}

// ArticleController.kt L21-30 → getArticles
func (h *Handler) GetArticles(w http.ResponseWriter, r *http.Request) {
    offset := int64(0)
    if raw := r.URL.Query().Get("offset"); raw != "" {
        parsed, err := strconv.ParseInt(raw, 10, 64)
        if err != nil || parsed < 0 {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_OFFSET", "offset must be a non-negative integer")
            return
        }
        offset = parsed
    }

    limit := 20
    if raw := r.URL.Query().Get("limit"); raw != "" {
        parsed, err := strconv.Atoi(raw)
        if err != nil || parsed < 1 || parsed > 100 {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_LIMIT", "limit must be 1..100")
            return
        }
        limit = parsed
    }

    tag := r.URL.Query().Get("tag")
    favoritedByUser := r.URL.Query().Get("favorited")
    author := r.URL.Query().Get("author")

    currentUser, _ := auth.UserIDFromContext(r.Context())

    articles, err := h.svc.FindArticles(r.Context(), tag, author, favoritedByUser, offset, limit, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }

    httpx.WriteJSON(w, http.StatusOK, articles)
}

// ArticleController.kt L33-39 → feed
func (h *Handler) Feed(w http.ResponseWriter, r *http.Request) {
    offset := int64(0)
    if raw := r.URL.Query().Get("offset"); raw != "" {
        parsed, err := strconv.ParseInt(raw, 10, 64)
        if err != nil || parsed < 0 {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_OFFSET", "offset must be a non-negative integer")
            return
        }
        offset = parsed
    }

    limit := 20
    if raw := r.URL.Query().Get("limit"); raw != "" {
        parsed, err := strconv.Atoi(raw)
        if err != nil || parsed < 1 || parsed > 100 {
            httpx.WriteError(w, http.StatusBadRequest, "INVALID_LIMIT", "limit must be 1..100")
            return
        }
        limit = parsed
    }

    currentUser, err := h.svc.GetCurrentUser(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }

    articles, err := h.svc.Feed(r.Context(), offset, limit, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }

    httpx.WriteJSON(w, http.StatusOK, articles)
}

// ArticleController.kt L42-45 → getArticle
func (h *Handler) GetArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, err := h.svc.GetCurrentUserSessionOrNull(r.Context())
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    article, err := h.svc.GetArticle(r.Context(), slug, currentUser)
    if err != nil {
        if errors.Is(err, ErrNotFound) {
            httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "article not found")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, article)
}

// ArticleController.kt L48-54 → updateArticle
func (h *Handler) UpdateArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    var req ArticleWrapper[UpdateArticleRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    currentUser, ok := auth.UserIDFromContext(r.Context())
    if !ok {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    article, err := h.svc.UpdateArticle(r.Context(), req.Content, slug, currentUser)
    if errors.Is(err, ErrInvalidRequest) {
        httpx.WriteError(w, http.StatusForbidden, "FORBIDDEN", "only author can update article")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, article)
}

// ArticleController.kt L57-60 → deleteArticle
func (h *Handler) DeleteArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    err = h.svc.DeleteArticle(r.Context(), slug, currentUser)
    if errors.Is(err, ErrInvalidRequest) {
        httpx.WriteError(w, http.StatusForbidden, "FORBIDDEN", "only author can delete own article")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, map[string]bool{"deleted": true})
}

// ArticleController.kt L64-67 → favoriteArticle
func (h *Handler) FavoriteArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, err := h.svc.GetCurrentUserOrFail(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    article, err := h.svc.FavoriteArticle(r.Context(), slug, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, article)
}

// ArticleController.kt L70-73 → unfavoriteArticle
func (h *Handler) UnfavoriteArticle(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    userID, ok := auth.UserIDFromContext(r.Context())
    if !ok {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    article, err := h.svc.UnfavoriteArticle(r.Context(), slug, userID)
    if errors.Is(err, ErrNotFound) {
        httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "article not found")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, map[string]string{"status": "success"})
}

// ArticleController.kt L76-79 → getComments
func (h *Handler) GetComments(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    currentUser, _ := h.svc.GetCurrentUserOrNull(r.Context())
    comments, err := h.svc.GetComments(r.Context(), slug, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, comments)
}

// ArticleController.kt L83-89 → addComment
func (h *Handler) AddComment(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    var req CommentWrapper[CreateCommentRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    user, ok := auth.UserIDFromContext(r.Context())
    if !ok {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    comment, err := h.svc.AddComment(r.Context(), slug, req.Content, user)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, comment)
}

// ArticleController.kt L92-95 → deleteComment
func (h *Handler) DeleteComment(w http.ResponseWriter, r *http.Request) {
    slug := chi.URLParam(r, "slug")
    commentId := chi.URLParam(r, "commentId")

    currentUser, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }

    err = h.svc.DeleteComment(r.Context(), slug, commentId, currentUser)
    if errors.Is(err, ErrInvalidRequest) {
        httpx.WriteError(w, http.StatusForbidden, "FORBIDDEN", "only author can delete comment")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }

    httpx.WriteJSON(w, http.StatusOK, map[string]string{"status": "success"})
}
