// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — fallback type aliases.
//
// These ``type X = any`` aliases let the package compile
// when the LLM-emitted code references types that aren't
// declared in this package and weren't resolved via
// cross-package imports. The wiring pass replaces these
// with the real type (struct OR cross-package import)
// — they are intentionally permissive (``any``) so the
// compiler doesn't reject valid call sites that pass
// typed values.
package article

type Articles = []Article
type ArticlesCount = any
type Author struct {
	ID any
	ToOwnProfileView func(args ...any) ProfileView
}
type AuthorArticleView = any
type Body = any
type Comments = any
type CreatedAt = any
type Description = any
type Favorited struct {
	ID any
}
type FavoritesCount = any
type Id = any
type Slug = any
type TagList = any
type TagName = any
type Tags = any
type Title = any
type UnfavoredArticleView = any
type UpdatedAt = any
type User struct {
	FollowingIDs any
	ID any
	ToOwnProfileView func(args ...any) ProfileView
	Unfavorite func(args ...any) (any, error)
}
