// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/security/JwtSigner.kt
//
package jwt

import (
	"time"
)

func (s *jwtSignerImpl) expirationDate() time.Time {
    expirationTime := time.Now().Add(s.sessionTime())
    return expirationTime
}
