// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsEntityController.php L19-46 → MapGet
        grp.MapGet("/{contractor_placement_id}/{onb_hr_checklist_type_id}", async (
            string contractor_placement_id,
            string onb_hr_checklist_type_id,
            AppDbContext db,
            IHttpContextAccessor httpContextAccessor) =>
        {
            // L22-23 → extract path parameters (already bound by route)
            // L24 → activeHRChecklistEntry lookup
            var cp_hr_checklist_details = await db.Set<ContractorPlacementHrChecklistDetailsMap>()
                .Where(x => x.ContractorPlacementId == contractor_placement_id
                         && x.OnbHrChecklistTypeId == onb_hr_checklist_type_id
                         && x.IsActive)
                .FirstOrDefaultAsync();

            // L25 → extract completion_date with sentinel default
            var completion_date = (cp_hr_checklist_details?.CompletionDate ?? "2000-01-01").Trim();

            // L26 → validate both IDs are present and well-formed
            if (!string.IsNullOrEmpty(contractor_placement_id)
                && !string.IsNullOrEmpty(onb_hr_checklist_type_id)
                && IsValidId(contractor_placement_id)
                && IsValidId(onb_hr_checklist_type_id))
            {
                // L27-39 → 'edit' operation: load or instantiate model with fetched data
                var model = new ContractorPlacementHrChecklistDetailsMapDto
                {
                    ContractorPlacementId = contractor_placement_id,
                    OnbHrChecklistTypeId = onb_hr_checklist_type_id,
                    CompletionDate = completion_date,
                };

                // L40 → onExists() hook (legacy lifecycle; in C# we just proceed to display)
                return Results.Ok(new
                {
                    op = "edit",
                    model = model,
                    message = new List<string>(),
                });
            }
            else if ((contractor_placement_id == "new" || contractor_placement_id == "")
                     && string.IsNullOrEmpty(onb_hr_checklist_type_id))
            {
                // L41-43 → 'new' operation not allowed; exit with error
                return Results.BadRequest(new
                {
                    error = "add not allowed",
                    op = "new",
                });
            }

            // L45 → fallback: return empty/not-found state
            return Results.NotFound(new
            {
                error = "Invalid contractor_placement_id or onb_hr_checklist_type_id",
            });
        }).RequireAuthorization(AuthPolicies.ContractorPlacementRead);

        // Contractor_placement_hr_checklist_detailsEntityController.php L48-60 → MapPost
        grp.MapPost("/", async (
            [FromBody] ContractorPlacementHrChecklistDetailsCreateRequest request,
            IValidator<ContractorPlacementHrChecklistDetailsCreateRequest> validator,
            AppDbContext db) =>
        {
            // L51 → extract operation mode from request
            var op = request.Op ?? "";

            // L52-59 → switch on operation
            switch (op)
            {
                case "":
                    // L54 → parent::create($this->request) — inline parent logic
                    // Parent EntityController::create (L254-294):
                    // 1. Validate request data (L259)
                    var validationResult = await validator.ValidateAsync(request);
                    if (!validationResult.IsValid)
                    {
                        // L260-263 → validation failed; return display with errors
                        return Results.BadRequest(new
                        {
                            ok = false,
                            errors = validationResult.ToDictionary(),
                            op = "new",
                            model = request,
                        });
                    }

                    // 2. Validation passed; proceed to save (L266-271)
                    var entity = new ContractorPlacementHrChecklistDetails
                    {
                        Id = $"CPHR-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
                        ContractorPlacementId = request.ContractorPlacementId,
                        HrChecklistItemId = request.HrChecklistItemId,
                        Status = request.Status ?? "pending",
                        Notes = request.Notes,
                        CreatedAt = DateTime.UtcNow,
                    };

                    // preSave hook (parent L268) — no-op in base; child may override
                    // For now, assume success and proceed to save.
                    db.Set<ContractorPlacementHrChecklistDetails>().Add(entity);
                    try
                    {
                        await db.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                        // L269 → save failed
                        return Results.BadRequest(new
                        {
                            ok = false,
                            error = "Problem saving entry (New)",
                            detail = ex.Message,
                        });
                    }

                    // 3. postSave hook (parent L274) — no-op in base; child may override
                    // For now, assume success and return the created entity.
                    // L276-290 → check output format and redirect/return
                    // Since we're a REST API, always return JSON (not HTML redirect).
                    return Results.Created(
                        $"/api/v1/contractor-placement-hr-checklist-details/{entity.Id}",
                        new
                        {
                            ok = true,
                            record = new
                            {
                                id = entity.Id,
                                contractor_placement_id = entity.ContractorPlacementId,
                                hr_checklist_item_id = entity.HrChecklistItemId,
                                status = entity.Status,
                                notes = entity.Notes,
                                created_at = entity.CreatedAt,
                            },
                        });

                default:
                    // L57-58 → unknown operation; no-op (fall through)
                    return Results.BadRequest(new
                    {
                        ok = false,
                        error = $"Unknown operation: {op}",
                    });
            }
        }).RequireAuthorization(AuthPolicies.ContractorPlacementWrite);

        // Contractor_placement_hr_checklist_detailsEntityController.php L62-93 → MapPut
        grp.MapPut("/{id}", async (
            string id,
            ContractorPlacementHrChecklistDetailsUpdateDto dto,
            IValidator<ContractorPlacementHrChecklistDetailsUpdateDto> validator,
            AppDbContext db) =>
        {
            // L65 → extract request body fields
            var contractorPlacementId = dto.ContractorPlacementId ?? 1;
            var onbHrChecklistTypeId = dto.OnbHrChecklistTypeId ?? 1;
            var completionDate = dto.CompletionDate;

            // L70-72 → validation: both IDs cannot be 0 (defaults are 1, so this is a guard)
            if (contractorPlacementId == 0 && onbHrChecklistTypeId == 0)
            {
                return Results.BadRequest(new
                {
                    errors = new[] { "Contractor Placement ID and Hr Checklist Type ID must be set to Update Entry" }
                });
            }

            // L74-75 → check if record already exists (is_populated)
            var existing = await db.Set<ContractorPlacementHrChecklistDetailsMap>()
                .FirstOrDefaultAsync(x =>
                    x.ContractorPlacementId == contractorPlacementId &&
                    x.OnbHrChecklistTypeId == onbHrChecklistTypeId);

            if (existing == null)
            {
                // L76 → inactivate previous checklist entries for this placement + type combo
                var previousEntries = await db.Set<ContractorPlacementHrChecklistDetailsMap>()
                    .Where(x =>
                        x.ContractorPlacementId == contractorPlacementId &&
                        x.OnbHrChecklistTypeId == onbHrChecklistTypeId)
                    .ToListAsync();
                foreach (var prev in previousEntries)
                {
                    prev.IsActive = false;
                }

                // L77-83 → create new entry
                var newEntry = new ContractorPlacementHrChecklistDetailsMap
                {
                    ContractorPlacementId = contractorPlacementId,
                    OnbHrChecklistTypeId = onbHrChecklistTypeId,
                    CompletionDate = completionDate,
                    IsCustomerMapped = "Y",
                    CreateTs = DateTime.UtcNow,
                };
                db.Set<ContractorPlacementHrChecklistDetailsMap>().Add(newEntry);
                await db.SaveChangesAsync();

                // L86 → redirect to previous request (legacy session-based navigation)
                // In .NET, we return a redirect response or a location header.
                // Since the legacy code exits after redirect, we return NoContent
                // with a Location header pointing to the referrer or a stored session value.
                return Results.NoContent();
            }
            else
            {
                // L88-90 → record already exists, just redirect back
                // (no update needed; the legacy code treats this as a no-op)
                return Results.NoContent();
            }
        }).RequireAuthorization(AuthPolicies.ContractorPlacementWrite);

        return app;
    }

    // Contractor_placement_hr_checklist_detailsEntityController.php L19-46 → read
    // Helper: validate ID format (legacy isID check)
    private static bool IsValidId(string id)
    {
        // Legacy isID() typically checks for non-empty alphanumeric/UUID format.
        // Adjust regex per your actual ID scheme (UUID, numeric, etc.).
        if (string.IsNullOrWhiteSpace(id)) return false;
        // Permissive: allow alphanumeric, hyphens, underscores (covers UUIDs, slugs, etc.)
        return System.Text.RegularExpressions.Regex.IsMatch(id, @"^[a-zA-Z0-9_-]+$");
    }
}

public sealed record ContractorPlacementHrChecklistDetailsMapDto(
    string ContractorPlacementId,
    string OnbHrChecklistTypeId,
    string CompletionDate);

public sealed record ContractorPlacementHrChecklistDetailsCreateRequest(
    string? Op,
    string ContractorPlacementId,
    string HrChecklistItemId,
    string? Status,
    string? Notes);

public sealed record ContractorPlacementHrChecklistDetailsUpdateDto(
    int? ContractorPlacementId,
    int? OnbHrChecklistTypeId,
    DateTime? CompletionDate);
