// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placementEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacement").WithTags("Contractorplacement");

        // Contractor_placementEntityController.php L61-73 → MapPost
        grp.MapPost("/", async (
            ContractorPlacementCreateDto dto,
            IValidator<ContractorPlacementCreateDto> validator,
            AppDbContext db,
            ILogger<ContractorPlacementEndpoints> logger) =>
        {
            // L64 → extract operation mode from request
            var op = dto.Op ?? "";

            // L65-72 → switch on operation
            switch (op)
            {
                case "":
                    // L67 → delegate to parent::create logic
                    // Parent EntityController::create (L254-294):
                    // 1. Validate request data (L259)
                    var validationResult = await validator.ValidateAsync(dto);
                    if (!validationResult.IsValid)
                    {
                        // L260-263 → validation failed; return display with errors
                        return Results.BadRequest(new
                        {
                            ok = false,
                            errors = validationResult.ToDictionary(),
                            op = "new",
                            model = dto,
                        });
                    }

                    // 2. Pre-save hook (L268)
                    // NOTE: preSave() is a virtual method on the parent; if the child
                    // overrides it, that override runs. For now, assume no-op (returns true).
                    // If preSave has side effects, they must be injected or called here.

                    // 3. Create and persist the entity (L268)
                    var row = new ContractorPlacement
                    {
                        Id = $"CPLA-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}",
                        EmployeeId = dto.EmployeeId,
                        CustomerId = dto.CustomerId,
                        EndclientId = dto.EndclientId,
                        PrimaryOfficeId = dto.PrimaryOfficeId,
                        EmploymentTypeId = dto.EmploymentTypeId,
                        Status = dto.Status ?? "draft",
                        WorkflowStage = "new",
                        CreatedAt = DateTime.UtcNow,
                    };
                    db.Set<ContractorPlacement>().Add(row);
                    try
                    {
                        await db.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                        // L269 → save failed
                        logger.LogError(ex, "Problem saving ContractorPlacement entry (New)");
                        return Results.BadRequest(new
                        {
                            ok = false,
                            errors = new[] { "Problem saving entry (New)" },
                            op = "new",
                            model = dto,
                        });
                    }

                    // 4. Post-save hook (L274)
                    // NOTE: postSave() is a virtual method; if the child overrides it,
                    // that runs. For now, assume it returns null (no redirect).

                    // 5. Return response (L276-290)
                    // L276 → if output == 'json', return display (which is the response DTO)
                    // For a REST API, we always return JSON.
                    return Results.Created(
                        $"/api/v1/contractor-placement/{row.Id}",
                        new
                        {
                            ok = true,
                            record = new
                            {
                                id = row.Id,
                                employee_id = row.EmployeeId,
                                customer_id = row.CustomerId,
                                endclient_id = row.EndclientId,
                                primary_office_id = row.PrimaryOfficeId,
                                employment_type_id = row.EmploymentTypeId,
                                status = row.Status,
                                workflow_stage = row.WorkflowStage,
                                created_at = row.CreatedAt,
                            },
                        });

                default:
                    // L70-71 → unknown operation; no-op (fall through)
                    return Results.BadRequest(new
                    {
                        ok = false,
                        error = $"Unknown operation: {op}",
                    });
            }
        }).RequireAuthorization(AuthPolicies.ContractorPlacementWrite);

        // Contractor_placementEntityController.php L75-206 → MapPost
        grp.MapPost("/read", async (
            [FromBody] ContractorPlacementReadRequest req,
            AppDbContext db,
            ILogger<ContractorPlacementEndpoints> logger) =>
        {
            // L80-81 → extract searchtype and id from request
            var searchtype = req.SearchType ?? "";
            var id = req.Id > 0 ? req.Id : 0;

            if (id > 0)
            {
                // L83-85 → load placement and its recent profile
                var placement = await db.Set<ContractorPlacement>().FindAsync(id);
                if (placement == null)
                {
                    return Results.BadRequest(new { ok = false, errors = new[] { "Placement not found" } });
                }

                var profile = await db.Set<ContractorPlacementProfile>()
                    .Where(p => p.ContractorPlacementId == id)
                    .OrderByDescending(p => p.CreatedAt)
                    .FirstOrDefaultAsync();

                // L86-182 → switch on searchtype
                switch (searchtype)
                {
                    case "reason":
                        // L88-97 → EOP reason lookup by employment type and agreement type
                        var reqType = req.ReqType ?? "eop";
                        List<object> eopReasons = new();

                        if (reqType == "eop")
                        {
                            var agreementTypeId = (placement.IsAcademy ?? "N") == "N" ? 0 : 2;
                            if (profile != null)
                            {
                                eopReasons = await GetEopReasonByEmploymentTypeId(
                                    db, profile.EmploymentTypeId, agreementTypeId);
                            }
                        }
                        else if (reqType == "ext")
                        {
                            eopReasons = await GetEopReasonForExtension(db);
                        }
                        else if (reqType == "bench")
                        {
                            eopReasons = await GetEopReasonForBenchPlacements(db);
                        }

                        return Results.Ok(new { ok = true, data = eopReasons });

                    case "state":
                        // L100-118 → state list by country (CAD or USA)
                        var country = req.Country ?? "USA";
                        var stateData = new List<object>();

                        if (country == "CAD")
                        {
                            var stateList = await GetStatesList(db, false, false, true);
                            foreach (var state in stateList)
                            {
                                var stateCode = state.Value ?? "";
                                var translated = TranslateStateCode(stateCode);
                                if (new[] { "ON", "NS" }.Contains(translated))
                                {
                                    stateData.Add(new { id = translated, name = stateCode });
                                }
                            }
                        }
                        else if (country == "USA")
                        {
                            var except = new[] { "Yearly", "AMERICAN SAMOA", "FEDERATED STATES OF MICRONESIA",
                                "GUAM", "MARSHALL ISLANDS", "NORTHERN MARIANA ISLANDS", "NORTHWEST TERRITORIES",
                                "NUNAVUT", "PALAU", "YUKON", "WASHINGTON D.C.", "WASHINGTON D.C", "WASHINGTON DC",
                                "VIRGIN ISLANDS" };
                            var stateList = await GetStatesList(db, false, false, true, except);
                            foreach (var state in stateList)
                            {
                                var stateCode = state.Value ?? "";
                                var translated = TranslateStateCode(stateCode);
                                stateData.Add(new { id = translated, name = stateCode });
                            }
                        }

                        return Results.Ok(new { ok = true, data = stateData });

                    case "history":
                        // L120-133 → EOP history by placement ID
                        var eopHistory = await GetEopHistoryByPlacementId(db, id);
                        var historyData = new List<object>();

                        if (eopHistory != null && eopHistory.Count > 0)
                        {
                            foreach (var item in eopHistory)
                            {
                                historyData.Add(new
                                {
                                    update_on = ToDisplayDate(item.UpdateOn),
                                    proposed_date = ToDisplayDate(item.ProposedDate),
                                    item.EopStatusTypeId,
                                    item.EopWorkflowStatusId,
                                    item.Notes
                                });
                            }
                        }

                        return Results.Ok(new { ok = true, data = historyData });

                    case "validate":
                        // L136-180 → EOP date validation cascade
                        var validateId = req.Id > 0 ? req.Id : 0;
                        var eopDate = ParseDisplayDate(req.EopDate ?? "01/01/2000");
                        var errors = new List<string>();
                        var resultValue = 0;

                        if (validateId == 0)
                        {
                            errors.Add("ID provided does not exists");
                            resultValue = 2;
                        }
                        else
                        {
                            // L144-150 → date validations
                            var startDate = await GetPlacementStartDate(db, validateId);
                            if (startDate > eopDate)
                            {
                                errors.Add("Proposed date is Invalid, date should be later than start date.");
                                resultValue = 2;
                            }

                            var lastTsDate = await GetLastEnteredTsDate(db, validateId);
                            if (lastTsDate > eopDate)
                            {
                                errors.Add("Proposed date is Invalid, date should be later than last entered timesheet.");
                                resultValue = 2;
                            }

                            // L153-178 → EOP workflow status check and minimum wage validation
                            var eopProcessed = await db.Set<EopProcessed>()
                                .Where(e => e.ContractorPlacementId == validateId)
                                .FirstOrDefaultAsync();

                            if (eopProcessed != null)
                            {
                                var eopWorkflowStatusId = eopProcessed.EopWorkflowStatusId ?? 0;
                                var onBenchPendingId = await GetEopWorkflowStatusId(db, "OnBench Pending Approval");

                                if (eopWorkflowStatusId == onBenchPendingId)
                                {
                                    var eopStatusTypeId = req.EopStatusTypeId ?? 0;
                                    var approvedStatusId = await GetEopStatusTypeId(db, "Approved");

                                    if (eopStatusTypeId == approvedStatusId)
                                    {
                                        // L161-177 → minimum wage check for onbench approved
                                        if (profile != null)
                                        {
                                            var worksite = await db.Set<Address>()
                                                .FindAsync(profile.WorksiteAddrId);

                                            if (worksite != null)
                                            {
                                                var workZip = worksite.Zip ?? "";
                                                var workStateId = TranslateStateId(worksite.State ?? "");
                                                var payRateId = req.PayRateId ?? 0;
                                                var payRate = req.PayRate ?? 0.0m;

                                                var startDatePlus1 = eopDate.AddDays(1);
                                                var minimumPayRate = await GetMinimumBenchPayRate(
                                                    db, workZip, workStateId, startDatePlus1, payRateId);

                                                if (payRate < minimumPayRate)
                                                {
                                                    errors.Add($"Pay rate should be at least $ {minimumPayRate} for this role.");
                                                    resultValue = 2;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        return Results.Ok(new
                        {
                            ok = resultValue == 0,
                            errors,
                            result_value = resultValue
                        });
                }
            }
            else
            {
                // L184-203 → ops-based dispatch when id <= 0
                var ops = req.Ops ?? "";

                if (ops == "checkcustomerclientpartner")
                {
                    var placementId = req.Id > 0 ? req.Id : 0;
                    var customerId = req.CustomerId ?? 0;
                    var isCustomerClientPartner = "N";
                    var clientPartnerId = 1;

                    if (customerId > 0)
                    {
                        clientPartnerId = await GetCustomerClientPartnerId(db, customerId);
                        if (clientPartnerId > 1)
                        {
                            isCustomerClientPartner = "Y";
                        }
                    }

                    return Results.Ok(new
                    {
                        ok = true,
                        result = 0,
                        message = "",
                        is_customer_client_partner = isCustomerClientPartner,
                        client_partner_id = clientPartnerId
                    });
                }

                // L204 → parent::read fallback — return 404 or generic read
                return Results.BadRequest(new { ok = false, errors = new[] { "Invalid request" } });
            }

            return Results.BadRequest(new { ok = false, errors = new[] { "No matching operation" } });
        }).RequireAuthorization(AuthPolicies.ContractorPlacementRead);

        return app;
    }

    // Contractor_placementEntityController.php L75-206 → read
    // Helper methods for EOP and state lookups
    private static async Task<List<object>> GetEopReasonByEmploymentTypeId(
        AppDbContext db, int? employmentTypeId, int agreementTypeId)
    {
        var reasons = await db.Set<EopReasonType>()
            .Where(r => r.EmploymentTypeId == employmentTypeId && r.AgreementTypeId == agreementTypeId)
            .Select(r => new { r.Id, r.Description })
            .Cast<object>()
            .ToListAsync();
        return reasons;
    }

    private static async Task<List<object>> GetEopReasonForExtension(AppDbContext db)
    {
        var reasons = await db.Set<EopReasonType>()
            .Where(r => r.ReasonType == "extension")
            .Select(r => new { r.Id, r.Description })
            .Cast<object>()
            .ToListAsync();
        return reasons;
    }

    private static async Task<List<object>> GetEopReasonForBenchPlacements(AppDbContext db)
    {
        var reasons = await db.Set<EopReasonType>()
            .Where(r => r.ReasonType == "bench")
            .Select(r => new { r.Id, r.Description })
            .Cast<object>()
            .ToListAsync();
        return reasons;
    }

    private static async Task<List<(string Code, string? Value)>> GetStatesList(
        AppDbContext db, bool param1, bool param2, bool selectOne, string[]? except = null)
    {
        var states = await db.Set<States>()
            .Where(s => except == null || !except.Contains(s.Description ?? ""))
            .Select(s => new { s.Code, s.Description })
            .ToListAsync();

        var result = new List<(string, string?)>();
        if (selectOne)
        {
            result.Add(("0", "-- Select One --"));
        }
        foreach (var s in states)
        {
            result.Add((s.Code ?? "", s.Description));
        }
        return result;
    }

    private static string TranslateStateCode(string code)
    {
        // Placeholder: map state description to code (e.g., "Ontario" -> "ON")
        // This would be a lookup in the States table or a hardcoded map.
        return code.Length > 2 ? code.Substring(0, 2).ToUpper() : code;
    }

    private static string TranslateStateId(string state)
    {
        // Reverse of TranslateStateCode — map state name/code to ID
        return state;
    }

    private static async Task<List<EopProcessedDto>> GetEopHistoryByPlacementId(
        AppDbContext db, int placementId)
    {
        var history = await db.Set<EopProcessed>()
            .Where(e => e.ContractorPlacementId == placementId)
            .OrderByDescending(e => e.UpdateOn)
            .Select(e => new EopProcessedDto
            {
                UpdateOn = e.UpdateOn,
                ProposedDate = e.ProposedDate,
                EopStatusTypeId = e.EopStatusTypeId,
                EopWorkflowStatusId = e.EopWorkflowStatusId,
                Notes = e.Notes
            })
            .ToListAsync();
        return history;
    }

    private static DateTime ParseDisplayDate(string displayDate)
    {
        // Convert MM/DD/YYYY to DateTime
        if (DateTime.TryParseExact(displayDate, "MM/dd/yyyy", System.Globalization.CultureInfo.InvariantCulture,
            System.Globalization.DateTimeStyles.None, out var result))
        {
            return result;
        }
        return new DateTime(2000, 1, 1);
    }

    private static string ToDisplayDate(DateTime? date)
    {
        return date?.ToString("MM/dd/yyyy") ?? "";
    }

    private static async Task<DateTime> GetPlacementStartDate(AppDbContext db, int placementId)
    {
        var placement = await db.Set<ContractorPlacement>().FindAsync(placementId);
        return placement?.StartDate ?? DateTime.MinValue;
    }

    private static async Task<DateTime> GetLastEnteredTsDate(AppDbContext db, int placementId)
    {
        var lastTs = await db.Set<Timesheet>()
            .Where(t => t.ContractorPlacementId == placementId)
            .OrderByDescending(t => t.EnteredDate)
            .Select(t => t.EnteredDate)
            .FirstOrDefaultAsync();
        return lastTs ?? DateTime.MinValue;
    }

    private static async Task<int> GetEopWorkflowStatusId(AppDbContext db, string statusName)
    {
        var status = await db.Set<EopWorkflowStatusType>()
            .Where(s => s.Description == statusName)
            .Select(s => s.Id)
            .FirstOrDefaultAsync();
        return status;
    }

    private static async Task<int> GetEopStatusTypeId(AppDbContext db, string statusName)
    {
        var status = await db.Set<EopStatusType>()
            .Where(s => s.Description == statusName)
            .Select(s => s.Id)
            .FirstOrDefaultAsync();
        return status;
    }

    private static async Task<decimal> GetMinimumBenchPayRate(
        AppDbContext db, string zip, string stateId, DateTime startDate, int payRateId)
    {
        var minRate = await db.Set<OnbMinimumPayStateMap>()
            .Where(m => m.Zip == zip && m.StateId == stateId && m.EffectiveDate <= startDate)
            .OrderByDescending(m => m.EffectiveDate)
            .Select(m => m.MinimumRate)
            .FirstOrDefaultAsync();
        return minRate ?? 0m;
    }

    private static async Task<int> GetCustomerClientPartnerId(AppDbContext db, int customerId)
    {
        var customer = await db.Set<Customer>().FindAsync(customerId);
        return customer?.ClientPartnerId ?? 1;
    }
}

public sealed record ContractorPlacementCreateDto(
    string? Op,
    string EmployeeId,
    string CustomerId,
    string? EndclientId,
    string? PrimaryOfficeId,
    string? EmploymentTypeId,
    string? Status);

public sealed record ContractorPlacementReadRequest(
    int Id,
    string? SearchType,
    string? ReqType,
    string? Country,
    string? EopDate,
    int? EopStatusTypeId,
    int? PayRateId,
    decimal? PayRate,
    string? Ops,
    int? CustomerId);

public sealed record EopProcessedDto(
    DateTime? UpdateOn,
    DateTime? ProposedDate,
    int? EopStatusTypeId,
    int? EopWorkflowStatusId,
    string? Notes);
