// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: src/main/kotlin/com/realworld/springmongo/api/UserController.kt
//
package user

import (
	"encoding/json"
	"errors"
	"github.com/go-chi/chi/v5"
	"net/http"
	"projbb8df72812/internal/platform/auth"
	"projbb8df72812/internal/platform/httpx"
)

// UserController.kt L16-18 → signup
func (h *Handler) Signup(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req SignupRequest
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    user, err := h.svc.Signup(r.Context(), req)
    if errors.Is(err, ErrEmailAlreadyInUse) {
        httpx.WriteError(w, http.StatusConflict, "EMAIL_IN_USE", "email already in use")
        return
    }
    if errors.Is(err, ErrUsernameAlreadyInUse) {
        httpx.WriteError(w, http.StatusConflict, "USERNAME_IN_USE", "username already in use")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusCreated, user)
}

// UserController.kt L22-24 → login
func (h *Handler) Login(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req LoginRequest
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        var maxErr *http.MaxBytesError
        if errors.As(err, &maxErr) {
            httpx.WriteError(w, http.StatusRequestEntityTooLarge, "PAYLOAD_TOO_LARGE", "request body exceeds 1 MiB")
            return
        }
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userView, err := h.svc.Login(r.Context(), req)
    if err != nil {
        if errors.Is(err, ErrInvalidCredentials) {
            httpx.WriteError(w, http.StatusUnauthorized, "INVALID_CREDENTIALS", "invalid username or password")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userView)
}

// UserController.kt L27-30 → getCurrentUser
func (h *Handler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
    userID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }

    user, token, err := h.svc.GetCurrentUserSession(r.Context(), userID)
    if errors.Is(err, ErrNotFound) {
        httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "user session not found")
        return
    }
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }

    userView := user.ToUserView(token)
    userWrapper := userView.ToUserWrapper()
    httpx.WriteJSON(w, http.StatusOK, userWrapper)
}

// UserController.kt L33-36 → updateUser
func (h *Handler) UpdateUser(w http.ResponseWriter, r *http.Request) {
    r.Body = http.MaxBytesReader(w, r.Body, 1<<20) // 1 MiB body limit
    var req UserWrapper[UpdateUserRequest]
    if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
        httpx.WriteError(w, http.StatusBadRequest, "BAD_JSON", "invalid request body")
        return
    }
    if err := req.Validate(); err != nil {
        httpx.WriteValidationError(w, err)
        return
    }
    userID, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    userView, err := h.svc.UpdateUser(r.Context(), req.Content, userID)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, userView)
}

// UserController.kt L39-42 → getProfile
func (h *Handler) GetProfile(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    currentUser, err := h.svc.GetCurrentUserSessionOrNull(r.Context())
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    profile, err := h.svc.GetProfile(r.Context(), username, currentUser)
    if err != nil {
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profile)
}

// UserController.kt L45-48 → follow
func (h *Handler) Follow(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    currentUser, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    profile, err := h.svc.Follow(r.Context(), username, currentUser)
    if err != nil {
        if errors.Is(err, ErrNotFound) {
            httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "user not found")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profile)
}

// UserController.kt L51-54 → unfollow
func (h *Handler) Unfollow(w http.ResponseWriter, r *http.Request) {
    username := chi.URLParam(r, "username")
    currentUser, err := auth.UserIDFromContext(r.Context())
    if err != nil {
        httpx.WriteError(w, http.StatusUnauthorized, "UNAUTHORIZED", "user not authenticated")
        return
    }
    profile, err := h.svc.Unfollow(r.Context(), username, currentUser)
    if err != nil {
        if errors.Is(err, ErrNotFound) {
            httpx.WriteError(w, http.StatusNotFound, "NOT_FOUND", "user not found")
            return
        }
        httpx.WriteInternal(w, r, err)
        return
    }
    httpx.WriteJSON(w, http.StatusOK, profile)
}
