// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-kotlin-to-go-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: chat/src/main/kotlin/com/plcoding/chirp/api/controllers/ChatController.kt
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Proj406b62972f.Endpoints;

public static class ChatEndpoints
{
    public static IEndpointRouteBuilder MapChatEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/chat").WithTags("Chat");

        // ChatController.kt L59-63 → getChatsForUser
        func (h *Handler) GetChatsForUser(w http.ResponseWriter, r *http.Request) {
            chats, err := h.svc.GetChatsForUser(r.Context(), requestUserId)
            if err != nil {
                httpx.WriteInternal(w, r, err)
                return
            }
            httpx.WriteJSON(w, http.StatusOK, chats)
        }

        return app;
    }


}


