// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/EntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Magicbox.Api.Data;
using Magicbox.Api.Auth;

namespace Application.Endpoints;

public static class EntityControllerEndpoints
{
    public static IEndpointRouteBuilder MapEntityControllerEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/entitycontroller").WithTags("EntityController");

        // EntityController.php L44-47 → MapGetSaveLabel
        grp.MapGet("/save-label", async (string? text, AppDbContext db) =>
        {
            // L46 → call parent method with default handling
            var label = string.IsNullOrEmpty(text) ? "Save" : text;
            return Results.Ok(label);
        }).RequireAuthorization(AuthPolicies.EntityRead);

        // EntityController.php L49-51 → MapGet
        grp.MapGet("/hasApprovalRights", async (AppDbContext db) =>
        {
            // L50 → check approval rights
            var hasRights = await _isAllowed("entity", modelname.ToLower(), "update", "approve");
            return Results.Ok(new { hasRights });
        }).RequireAuthorization(AuthPolicies.EntityUpdate);

        // EntityController.php L100-103 → MapGet
        grp.MapGet("/onCancel", async (HttpContext ctx) =>
        {
            // L102 → retrieve session value with default
            var prevRequest = ctx.Session.TryGetValue("PREVREQUEST", out var value) ? value.ToString() : "";
            return Results.Ok(prevRequest);
        }).RequireAuthorization(AuthPolicies.Default);

        // EntityController.php L139-141 → MapGet
        grp.MapGet("/exists", async () =>
        {
            // L140 → always returns true
            return Results.Ok(true);
        });

        // EntityController.php L175-177 → MapGet
        grp.MapGet("/isMandatory/{field}", async (string field, AppDbContext db) =>
        {
            // L175-177 → check if the field is mandatory
            var mandatoryFields = new List<string> { /* populate with actual mandatory fields */ };
            return Results.Ok(fromBoolToInt(mandatoryFields.Contains(field)));
        }).RequireAuthorization(AuthPolicies.EntityRead);

        return app;
    }


}


