// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — Kotlin extension fn stubs.
//
// Kotlin uses extension functions extensively (``fun User.toUserView``).
// Go has no equivalent — translate each as a method on the receiver
// type. Stubs panic until the wiring pass replaces them with real
// translations of the Kotlin body.
package user

// Kotlin source declared ``class UserRepository`` (plain, not data class)
// — stub struct so the extension methods below are valid Go.
type UserRepository struct{}

// Extension: Kotlin ``fun ProfileView.toProfileWrapper()``
func (x ProfileView) ToProfileWrapper(args ...any) any {
	panic("TODO(wiring): translate Kotlin ProfileView.toProfileWrapper extension")
}

// Extension: Kotlin ``fun UserRepository.findByUsernameOrFail(username: String)``
func (x UserRepository) FindByUsernameOrFail(args ...any) any {
	panic("TODO(wiring): translate Kotlin UserRepository.findByUsernameOrFail extension")
}

// Extension: Kotlin ``fun UserRepository.findByEmailOrFail(email: String)``
func (x UserRepository) FindByEmailOrFail(args ...any) any {
	panic("TODO(wiring): translate Kotlin UserRepository.findByEmailOrFail extension")
}

// Extension: Kotlin ``fun UserRepository.findAuthorByArticle(article: Article)``
func (x UserRepository) FindAuthorByArticle(args ...any) any {
	panic("TODO(wiring): translate Kotlin UserRepository.findAuthorByArticle extension")
}

// Extension: Kotlin ``fun User.toProfileView(viewer: User? = null)``
func (x User) ToProfileView(args ...any) any {
	panic("TODO(wiring): translate Kotlin User.toProfileView extension")
}

// Extension: Kotlin ``fun User.toUnfollowedProfileView()``
func (x User) ToUnfollowedProfileView(args ...any) any {
	panic("TODO(wiring): translate Kotlin User.toUnfollowedProfileView extension")
}

// Extension: Kotlin ``fun User.toFollowedProfileView()``
func (x User) ToFollowedProfileView(args ...any) any {
	panic("TODO(wiring): translate Kotlin User.toFollowedProfileView extension")
}

// Extension: Kotlin ``fun User.toOwnProfileView()``
func (x User) ToOwnProfileView(args ...any) any {
	panic("TODO(wiring): translate Kotlin User.toOwnProfileView extension")
}

// Extension: Kotlin ``fun User.toUserView(token: String)``
func (x User) ToUserView(args ...any) any {
	panic("TODO(wiring): translate Kotlin User.toUserView extension")
}
