// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — per-package layer scaffold.
//
// Receiver struct for the translated `func (s *articleFacadeImpl)`
// methods in this package, with dependency-interface-typed fields
// so the layer's outbound calls resolve. A real wiring pass swaps
// the interfaces for concrete collaborators.
package articlefacade

type articleFacadeImpl_articleRepoDep interface {
	FindBySlug(args ...any) (any, error)
}

type articleFacadeImpl_repoDep interface {
	DeleteBySlug(args ...any) error
	FindBySlug(args ...any) (RepoFindBySlugResult, error)
	FindNewestArticlesByAuthorIds(args ...any) ([]any, error)
	Save(args ...any) (RepoSaveResult, error)
	SaveAllTags(args ...any) error
	SaveArticle(args ...any) (RepoSaveArticleResult, error)
}

type articleFacadeImpl_userRepoDep interface {
	Save(args ...any) error
}

type RepoFindBySlugResult interface {
	IsAuthor(args ...any) any
}

type RepoSaveArticleResult struct {
	Tags any
}
func (r RepoSaveArticleResult) ToArticleView(_ ...any) any { panic("stub") }

type RepoSaveResult interface {
	ToAuthorArticleView(args ...any) any
}

type articleFacadeImpl struct {
	articleRepo articleFacadeImpl_articleRepoDep
	repo articleFacadeImpl_repoDep
	userRepo articleFacadeImpl_userRepoDep
}

func (s *articleFacadeImpl) mapToArticleView(args ...any) (ArticleView, error) { panic("stub: sibling method") }
