// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent — cross-pkg fallback funcs.
package user

func ToUserView(args ...any) (any, error) {
	panic("TODO(wiring): translate cross-pkg call site for `user.ToUserView` — undeclared in package user")
}
