// SPDX-License-Identifier: Apache-2.0
// Generated by MethodTranslatorSubAgent (translator-php-to-csharp-v1.0) — DO NOT hand-edit without preserving provenance comments.
//
// Source: Controller/Contractor_placement_hr_checklist_detailsEntityController.php
//
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MagicboxNext.Endpoints;

public static class ContractorplacementhrchecklistdetailsEndpoints
{
    public static IEndpointRouteBuilder MapContractorplacementhrchecklistdetailsEndpoints(this IEndpointRouteBuilder app)
    {
        var grp = app.MapGroup("/api/v1/contractorplacementhrchecklistdetails").WithTags("Contractorplacementhrchecklistdetails");

        // Contractor_placement_hr_checklist_detailsEntityController.php L48-60 → MapPost
        grp.MapPost("/", async (
            HttpRequest request,
            AppDbContext db) =>
        {
            var op = request.Form.TryGetValue("op", out var opValue) ? opValue.ToString() : "";
            switch (op)
            {
                case "":
                    return await CreateEntity(request, db);
                    break;

                default:
                    break;
            }
            return Results.BadRequest();
        }).RequireAuthorization(AuthPolicies.ContractorWrite);

        return app;
    }

    // Contractor_placement_hr_checklist_detailsEntityController.php L48-60 → create
    private static async Task<IResult> CreateEntity(HttpRequest request, AppDbContext db)
    {
        // L256-294 → inline parent create logic
        var obj = await ValidateAsync(request);
        if (obj == null)
        {
            return Results.ValidationProblem(new { error = "Validation failed" });
        }

        // Save logic
        if (!await PreSaveAsync() || !await SaveAsync(obj))
        {
            return Results.BadRequest(new { error = "Problem saving entry (New)" });
        }

        var url = PostSave();
        if (request.Form.TryGetValue("output", out var output) && output == "json")
        {
            return Results.Ok(obj);
        }
        else if (url is string)
        {
            return Results.Redirect(url);
        }
        return Results.NoContent();
    }
}


